### ISSUE TITLE
"Helm Chart" vs "Helm chart"

### ISSUE THREAD

**Issue by paul-hammant** [hashicorp/consul-helm#1]
Pick one in the documentation online and READMEs

**Comment by mitchellh** [comment]
I thought we used "chart" everywhere when paired with "Helm" but I just corrected a handful of areas. I of course leave the area where want title cases (navigation titles, section titles, etc.) This is fixed in Git but not deployed yet.

**Comment by paul-hammant** [comment]
Wait, you're moving to "Helm chart" for the project/product name?
