### ISSUE TITLE
Upgrade after extra config changes

### ISSUE THREAD

**Issue by pbetkier** [hashicorp/consul-helm#106]
Changes in `server.extraConfig` or `client.extraConfig` alone don't cause my Consul pods to upgrade. From Kubernetes perspective my definitions don't change, because config map changes are not tracked.

I used to use this approach in my charts before switching to `consul-helm`: [Automatically Roll Deployments When ConfigMaps or Secrets change](https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change) from the Helm docs. Consul-helm doesn't use it. Note: my release name is set to a constant value.

What is the recommended way of ensuring that Consul pods get upgraded with changes in extra config? Should my release name change on every change to params?

**Comment by micksear** [comment]
I also have issues with using this chart.  Helm flatly refuses to upgrade when, e.g. client is enabled.

Example errors:

```
➜  consul helm upgrade --install --namespace=consul consul ./consul-helm
Error: UPGRADE FAILED: no ConfigMap with the name "consul-client-config" found
➜  consul helm upgrade --install --namespace=consul consul ./consul-helm
Error: UPGRADE FAILED: no Service with the name "consul-dns" found
➜  consul helm upgrade --install --namespace=consul consul ./consul-helm
Error: UPGRADE FAILED: no ServiceAccount with the name "consul-connect-injector-webhook-svc-account" found
```

**Comment by lkysow** [comment]
Hi Piotr, good questions.

In addition, some config changes only request a reload and others require a full restart. We'd also want to be careful about restarting servers. I think a mechanism like you linked would be the best solution. I don't think renaming the release makes sense.
