### ISSUE TITLE
Allow specifying a default policy / role for namespace mirroring

### ISSUE THREAD

**Issue by chrisjohnson** [hashicorp/consul-helm#1073]
We need to grant a global-read policy to our namespaces to allow for cross-namespace communication.

In order to do that we want to be able to set a global default policy and/or default role for the namespaces that consul-helm creates. A single value is acceptable that would apply to all namespaces that get created.

**Comment by lkysow** [comment]
Hi Chris, I'm just curious what your Helm values look like? We actually do this automatically for you depending on your config so I'm guessing we don't trigger that behaviour for you config for some reason.

**Comment by chrisjohnson** [comment]
Yep I think this can be closed, when working with support we identified this as a need but didn't realize it was already handled for you. Thanks for the feedback.
