### ISSUE TITLE
Installing on multiple namespaces on EKS

### ISSUE THREAD

**Issue by kfirbreger** [hashicorp/consul-helm#110]
While trying to install the helm chart on EKS I kept getting failures in provisioning the PVC, with the error that the storage class was not given (it was, in the chart).

After digging around, I remembered that we have the same chart installed on another namespace on the same cluster.
Changing the metadata name in the volumeClaimTemplates that the chart generates manually solved this problem.

I am not sure why this is happening as the actual PV generated at the end have different names and, of course, the pvc are namespaced. Still, it might me worthwhile to make that name a variable in the values.

### How to reproduce

Install, at the very least, the server from the helm chart. Then do that again in a different namespace.

**Comment by SamDecrock** [comment]
Are you sure it was namespaced? We have multiple instances of our software, all using the same pvc names in different namespaces. It works perfectly.

**Comment by lkysow** [comment]
> Are you sure it was namespaced? We have multiple instances of our software, all using the same pvc names in different namespaces. It works perfectly.

Hi Sam, it does look like Kube supports the same PVC names across namespaces so this may not have been necessary. Were you looking for us to change this back to not have the namespace? Unfortunately that would result in all the PVCs for existing users being deleted so I think we need to keep the name as is.

**Comment by SamDecrock** [comment]
Yes, I was looking into removing the namespace from pvc names so it looks cleaner.
But good point about the pvc's. Upgrading would indeed break previous setups.

**Comment by lkysow** [comment]
> Yes, I was looking into removing the namespace from pvc names so it looks cleaner.

Agreed that this would look nicer. Maybe this is something we can change in a 1.0 release but I think we're stuck with it as it is now until then.
