### ISSUE TITLE
Support running with HTTP listeners disabled

### ISSUE THREAD

**Issue by reidab** [hashicorp/consul-helm#129]
I just set up a cluster using this helm chart and was able to inject most of the configuration I needed to get TLS configured fairly easily using `extraVolumes`. The one thing I wasn't able to do without patching the chart was to run agents with HTTP listeners disabled.

(Context:  Since [client agents are run as a DaemonSet](https://www.consul.io/docs/platform/k8s/run.html#client-agents) and can't bind to a local-only host port, it seems like the [secure practice](https://www.consul.io/docs/internals/security.html#secure-configuration) is to run them HTTPS-only with the HTTP listeners disabled.)

There are a few issues with the chart that prevent this from working without modification:

1. The recommended HTTPS port, 8501 is not included in the containers `ports` config.
2. The container's readiness probes uses HTTP on 8500, so it's never treated as ready if there's not an HTTP listener
3. Switching the readiness check to HTTPS still requires the curl command to include the relevant cert/key paths in order to connect

The minimal change this use case might be to add `8501` to `ports` and provide some way to override the client and server readiness checks via a passed value. Ideally, I'd like to see this chart gain support for TLS configuration directly, making all of these manual overrides unnecessary.

**Comment by lkysow** [comment]
Related to #136

**Comment by ishustava** [comment]
Hey @reidab, we've just shipped full TLS support in the [latest Helm chart version](https://github.com/hashicorp/consul-helm/releases/tag/v0.16.0) that should address your concerns. 

I'm going to close this for now, but please don't hesitate to comment here to re-open or open a new issue. Thanks!
