### ISSUE TITLE
support for prefixes when registering in Consul

### ISSUE THREAD

**Issue by kgignatyev-inspur** [hashicorp/consul-helm#140]
It would be nice if it was possible to specify **ConsulPrefix** for Kubernetes -> Consul sync, the same way as it is possible to specify k8sPrefix for Consul->Kubernetes sync. 
Purpose: easily register all services while disambiguating services with common names which belong to different clusters. 

Rational: lets say we have 2 k8s clusters in a single data center, they might be running many 'system' services liker rook, kubernetes, etc. Which we would like to register with Consul, but current behavior will create pool of nodes belonging to different clusters under the same service name, which is not desirable. It would be better to use  ConsulPrefix to create  names like prefix1-rook and prefix2-rook for services with the same names running in different clusters when syncCatalog.default=true. Annotations would allow to use current behavior: services will have common name (unprefixed) and instances running on different clusters will still be registered under single name in Consul.

**Comment by adilyse** [comment]
Hi @kgignatyev-inspur,

I agree, it makes sense to allow this functionality in both directions. This feature is currently under development and should be available soon.

**Comment by adilyse** [comment]
This functionality has been added and will be available in the next release, v0.8.0, which will be released soon. Details of the implementation can be seen here: [consul-k8s](https://github.com/hashicorp/consul-k8s/pull/89), [consul-helm](https://github.com/hashicorp/consul-helm/pull/152).

Thanks for helping make this a better product!
