### ISSUE TITLE
how to filter by prefix (Kubernetes ->  Consul sync) 

### ISSUE THREAD

**Issue by moris1amar** [hashicorp/consul-helm#145]
I can "filter" Consul services that will appear to Kubernetes (Consul -> Kubernetes sync) with "k8sPrefix" in helm values.
But I need to implement the other side, means I want to mention only k8s services in Consul UI with a particular prefix. Can we do this?

 thanks
Maurice

**Comment by adilyse** [comment]
Hi @moris1amar,

We'll be adding the ability to prefix k8s services synced into Consul soon! Please watch #140 for future updates.

Closing this, as the request is tracked elsewhere.
