### ISSUE TITLE
Run as user and group configurable

### ISSUE THREAD

**Issue by jheiss** [hashicorp/consul-helm#147]
Currently this chart generates configs that hard code fsGroup to [1000](https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L55) but do not support setting runAsUser or (new in kubernetes 1.14) runAsGroup. This appears to derive from the configuration of the official consul docker image which assumes that it is being run as root and, after some setup, switches to a (sorta) hardcoded UID 100, GID 1000: hashicorp/docker-consul#103

In our environment we use Pod Security Policies to restrict users to running as their own UID, with similar limits on fsGroup. As such for us to use this helm chart we would need to be able to control the values of runAsUser, runAsGroup, and fsGroup. I'm happy to work on a PR if nobody objects.

**Comment by adilyse** [comment]
Hi @jheiss,

I would definitely be willing to take a look at a PR that supports this. It would be good to keep the current behavior as the default, then allow for the option to update as needed. As part of adding additional Helm chart configuration options, we like to make sure things are unit tested, so I recommend taking a look at the [Readme](https://github.com/hashicorp/consul-helm#writing-unit-tests) for details on implementing them.

Thanks!

**Comment by isaaccarrington** [comment]
@jheiss hello, did you get anywhere with this? Does anyone have any hints to make the sidecars run with a specific user ID?

**Comment by jheiss** [comment]
Shortly after creating this my need for Consul evaporated and I moved on to other projects.

**Comment by isaaccarrington** [comment]
That's a shame. Anyone know how to configure connect to run the injected sidecar proxies with a UID e.g 1001?

**Comment by isaaccarrington** [comment]
I'm going to raise a PR. Relates to https://github.com/hashicorp/consul-k8s/issues/347

**Comment by isaaccarrington** [comment]
I'm going to raise a PR. Relates to https://github.com/hashicorp/consul-k8s/issues/347

**Comment by ishustava** [comment]
As of Helm chart version [`0.29.0`](https://github.com/hashicorp/consul-helm/releases/tag/v0.28.0), we now run Consul containers as non-root and support configuring security context for Consul pods. As we have other issues tracking running sidecar containers as non-root, I'm going to close this issue. Please let us know if you think we should re-open!
