### ISSUE TITLE
Cloud Auto-joining not working with gce

### ISSUE THREAD

**Issue by sc7565** [hashicorp/consul-helm#16]
Setting up the Auto-join values in values.yaml results in error
 
join:
    - "provider=gce project_name=test-0 tag_value=consul-server" 

Error - 

==> config: Unknown extra arguments: [project_name=test-0 tag_value=consul-server -domain=consul]

Is this valid error or something is wrong with my configuration

**Comment by adilyse** [comment]
This change made for another issue was potentially causing problems here as well:
* [Missing command continuation characters](https://github.com/hashicorp/consul-helm/pull/40/files)

Additionally, try one of these formats for the flags instead:
`join: ["provider=gce", "project_name=test-0", "tag_value=consul-server"]`

or

```
join:
  - "provider=gce"
  - "project_name=test-0"
  - "tag_value=consul-server"
```

I'll see if I can make the documentation clearer about the desired format in this case.

@sc7565 @jailson-silva If these changes don't solve your problem, feel free to reopen this issue!

**Comment by adilyse** [comment]
Following up on this issue: it turns out that there were missing quotes in the template file that were causing problems. The original syntax is correct, and should work now that [this PR](https://github.com/hashicorp/consul-helm/pull/61) is merged. Sorry for the confusion!
