### ISSUE TITLE
Changes in `templates/_helpers.tpl` from 0.7.0 to 0.8.0 is breaking

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/consul-helm#167]
My Helm release for Consul is called `consul`. The changes introduced [here](https://github.com/hashicorp/consul-helm/compare/hashicorp:0f7ccd2...hashicorp:ac6ece5#diff-93c03d74bec56c58046cc102d9474f25) causes a rename of resources which is breaking because it causes a new `StatefulSet` with new names to be created, causing new PVCs to be created and breaks the entire setup.

Workaround is to set `fullnameOverride`. 

Please make a note of this in the changelog, or revert to the old behaviour.

**Comment by djanjic** [comment]
I have the same problem. Statefulset name was `consul-server` and after this change is `consul-consul-server`.

**Comment by lawliet89** [comment]
There is also no clear/easy upgrade path for users from 0.7.x to 0.8.x.

**Comment by fusionx86** [comment]
I was able to work around the problem by setting fullnameOverride:

`fullnameOverride: "consul"`

Almost all everything went back to the single consul name, but two secrets still show up with the annoying double name:

consul-consul-bootstrap-acl-token
consul-consul-client-acl-token

**Comment by lawliet89** [comment]
Thanks for the workaround. At least the PVC and services won't break.

**Comment by ttyS0** [comment]
FWIW, I also had to remove the `-{{ .Release.Namespace }}` from the Volume names. I was coming from 0.6, so perhaps that was added in 0.7. In any event, my PVCs are named like `data-consul-server-0`, and adding the namespace into the PVC naming meant they couldn't be found. Since PVCs can't be renamed, it might be useful to make it clear that if the storage names don't line up, one is looking at either a template modification or a Consul restore from snapshot.

**Comment by lkysow** [comment]
Hey all, we're sorry this broke the upgrade process. It was getting to be too complicated to support the special case of detecting with `consul-` prefix and we were bound to miss this and break something later on.

We should definitely document the upgrade process though.

**Comment by lkysow** [comment]
We've added support for setting `global.name` or `fullnameOverride` in https://github.com/hashicorp/consul-helm/pull/307. In order to upgrade you'll need to set either of these keys to `consul`:
```
# option 1
fullnameOverride: consul

# option 2
global:
  name: consul
```

I've updated the CHANGELOG for 0.7.0 to indicate this.
