### ISSUE TITLE
consul client use emptydir, Health check will not be lost?

### ISSUE THREAD

**Issue by wyw64962771** [hashicorp/consul-helm#168]

**Comment by lkysow** [comment]
@wyw64962771 can you give us some more information for this issue? Thanks!

**Comment by lkysow** [comment]
I think this is about if the service is registered with Consul through the agent API, when the agent gets restarted it will lose its data and any health check. This can either be solved by https://github.com/hashicorp/consul-helm/pull/233 or by using the service sync feature when health checks are supported (they are not currently).

**Comment by lkysow** [comment]
I'm going to close this because syncing health checks is tracked by https://github.com/hashicorp/consul-k8s/issues/29 and losing the data is tracked by #233
