### ISSUE TITLE
DNS Service: Allow a specific service cluster IP to be specified

### ISSUE THREAD

**Issue by ewbankkit** [hashicorp/consul-helm#170]
For [integration](https://www.consul.io/docs/platform/k8s/dns.html#coredns-configuration) between Consul DNS and CoreDNS it will be helpful to allow a specific DNS service cluster IP to be specified as this IP address value must be hard-coded into the CoreDNS configuration.

**Comment by lkysow** [comment]
Feature would be to expose an optional `ClusterIP` field that would map to the `ClusterIP` of the `consul-dns` service.

**Comment by adilyse** [comment]
Fixed by #171 that was merged as #219.
