### ISSUE TITLE
bootstrapACLs job timing errors

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-helm#186]
Sometimes when the server-acl-init job's pods come up, they reach a broken state.

One attempt at the job gives this:
`Error creating client agent token: Unexpected response code: 500 (The ACL system is currently in legacy mode.) `

Then all further attempts at the job give this:
`Error bootstrapping Consul agent: Unexpected response code: 403 (Permission denied: ACL bootstrap no longer allowed (reset index: 6)) `

This does not happen every time but has occurred more than once for me.

The fix seems like it should be pretty easy though: check if the bootstrap token is already available, and if so, skip that step of the init job.

**Comment by lkysow** [comment]
Closed by https://github.com/hashicorp/consul-k8s/pull/143, available in `consul-helm` `v0.10.0`
