### ISSUE TITLE
Stuck on "Terminating" in EKS

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-helm#189]
Often when we're draining nodes in EKS, our Consul server pods are getting stuck in "Terminating" with events that look like the following:

```
    Events:
  Type     Reason             Age   From                                                Message
  ----     ------             ----  ----                                                -------
  Warning  FailedPreStopHook  6m4s  kubelet, ip-10-14-6-121.us-west-2.compute.internal  Exec lifecycle hook ([/bin/sh -c consul leave]) for Container "consul" in Pod "consul-ctnp-uswest2-addon-server-2_consul-ctnp-uswest2(600580f8-8878-11e9-b516-02d6e6b431b4)" failed - error: command '/bin/sh -c consul leave' exited with 137: , message: ""
  Warning  FailedKillPod      2m6s  kubelet, ip-10-14-6-121.us-west-2.compute.internal  error killing pod: [failed to "KillContainer" for "consul" with KillContainerError: "rpc error: code = Unknown desc = operation timeout: context deadline exceeded"
, failed to "KillPodSandbox" for "600580f8-8878-11e9-b516-02d6e6b431b4" with KillPodSandboxError: "rpc error: code = DeadlineExceeded desc = context deadline exceeded"
]
  Normal   Killing            39s (x2 over 4m6s)  kubelet, ip-10-14-6-121.us-west-2.compute.internal  Killing container with id docker://consul:Need to kill Pod
  Warning  FailedPreStopHook  39s                 kubelet, ip-10-14-6-121.us-west-2.compute.internal  Exec lifecycle hook ([/bin/sh -c consul leave]) for Container "consul" in Pod "consul-ctnp-uswest2-addon-server-2_consul-ctnp-uswest2(600580f8-8878-11e9-b516-02d6e6b431b4)" failed - error: rpc error: code = Unknown desc = container not running (consul), message: ""
```

This puts the pod in a stuck state that requires force-deletion, which is not easily scalable with many deployments.

**Comment by lkysow** [comment]
Hi @infa-bsurber, I think I recognize you from the Atlantis repo?

Sorry this one fell through the cracks. We removed the prestop hook in [0.16.0](https://github.com/hashicorp/consul-helm/blob/master/CHANGELOG.md#0160-jan-10-2020) so I hope this has been resolved?

**Comment by ishustava** [comment]
Hey @infa-bsurber, 

I'm going to close this issue because we haven't heard back from you in a while, but I hope you have resolved your issue. If you still experience problems, please don't hesitate to comment here or open a new issue.

**Comment by yevgeniyo** [comment]
getting the same in 0.26.0

`  Warning  FailedPreStopHook       2m25s (x2 over 3m6s)   kubelet, ip-x.x.x.x.ec2.internal  Exec lifecycle hook ([/bin/sh -c consul leave]) for Container "consul" in Pod "hashicorp-consul-server-2_consul`

**Comment by lkysow** [comment]
@yevgeniyo does this cause any other issues in the cluster?
