### ISSUE TITLE
Add component label to services

### ISSUE THREAD

**Issue by infa-bsurber** [hashicorp/consul-helm#196]
I need some way to select between the UI and Server services based on their labels.
Currently these services have the same set of labels.

An easy fix seems to be adding a "component" label like the one in the deployed pods:
https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L36

**Comment by lkysow** [comment]
That makes sense to me.

**Comment by lkysow** [comment]
This was closed in https://github.com/hashicorp/consul-helm/pull/480!
