### ISSUE TITLE
Idea: More robust server-acl-init-job

### ISSUE THREAD

**Issue by paulbouwer** [hashicorp/consul-helm#198]
When the `server-acl-init-job` runs, sometimes the `.spec.backoffLimit` default of 6 retries (capped at 6 minutes) is not sufficient and other times it is more than enough. There are also a number of jobs in an `Error` state along the way to success.

I used the following to pause the `server-acl-init-job` job via an `initContainer` until the required number of Consul servers were running. This seemed to be more efficient and led to more success.

Something similar to the below approach could help resolve #186. It solved the issue for me.

**templates/server-acl-init-job.yaml**

```yaml
29     spec:
30       restartPolicy: Never
31       serviceAccountName: {{ template "consul.fullname" . }}-server-acl-init
--> INSERT FROM HERE
32       initContainers:
33         - name: init-post-install-job
34           image: bitnami/kubectl:1.13
35           command:
36             - "/bin/bash"
37             - "-c"
38             - |
39               COUNT=0; while [[ $COUNT -lt {{ .Values.server.replicas }} ]]; do COUNT=$(kubectl get pods -n {{ .Release.Namespace }} -l "app=consul,component=server" --field-selector=status.phase=Running -o 'jsonpath={range .items[*]}{.metadata.name}{"\n"}{end}' | wc -l); echo "waiting for {{ .Values.server.replicas }} servers ... $COUNT"; sleep 10s; done
<-- TO HERE
40       containers: 
41         - name: post-install-job 
42           image: {{ .Values.global.imageK8S }} 
43           env: 
44             - name: NAMESPACE 
45               valueFrom: 
46                 fieldRef: 
47                   fieldPath: metadata.namespace 
48           command:
```

Thoughts on whether to use as is, or build a custom `consul-xxx` image for the task?

/cc @nicholasjackson

**Comment by lkysow** [comment]
Don't we need a leader to be elected before the server-acl-init-job runs (cc @adilyse)? I'm wondering if we should use a similar technique but actually call the consul api to figure out if there's a leader since there's still the chance that the pods are up but there's no leader with this proposed solution.

**Comment by HansK-p** [comment]
Is it an option to make the server-acl-init-job more robust in itself? Typically make it wait for the Consul cluster to reach an acceptable state or a timeout to be reached - before actually bootstrapping those ACLs (or exiting with an error message if a timeout was reached)?

It would also be nice i the acl init job were able to handle most/all error conditions of type "a previous version of the same job partly succeeded, let us continue from where it failed".

**Comment by lkysow** [comment]
My thinking was that the `consul-k8s server-acl-init` command shouldn't hang indefinitely waiting for a leader but should exit immediately if it can't complete. So instead of building the smarts into that command I'd prefer doing the waiting a different way.

**Comment by HansK-p** [comment]
Currently the deployment (often) leaves acl-init pods in an error state and the server-acl-init command sometimes leaves the ACL bootstrap process in a state where manual intervention is needed in order to solve the problem.

It would probably be good to address both these issues and I agree that the proposed solution will close to eliminate both issues. "Close to" as I assume that server-acl-init will still leave the ACL bootstrap process in a bad state on rare occasions.

I've been testing the Consul Helm chart in a low performance K8s (test)cluster. As a result I probably have more issues with the ACL bootstrapping process than what can be expected in a more performant cluster.

**Comment by lkysow** [comment]
Good points, I'll confer with @adilyse

**Comment by dschaaff** [comment]
I cannot get bootstrapAcls to work, even with this change. It correctly generates the master token and enables acl's on the server but it never creates a client token and the helm install fails. The error is always `Error bootstrapping Consul agent: Unexpected response code: 403 (Permission denied: ACL bootstrap no longer allowed `.

**Comment by dschaaff** [comment]
Update, I did get this work by adding a very long sleep before the acl bootstrap runs in the init container. 

```
sleep 300s; COUNT=0; while [[ $COUNT -lt {{ .Values.server.replicas }} ]]; do COUNT=$(kubectl get pods -n {{ .Release.Namespace }} -l "app=consul,component=server" --field-selector=status.phase=Running -o 'jsonpath={range .items[*]}{.metadata.name}{"\n"}{end}' | wc -l); echo "waiting for {{ .Values.server.replicas }} servers ... $COUNT"; sleep 10s; done
```

Its an ugly hack but it worked.

**Comment by blakeblackshear** [comment]
This version of an initContainer is working well for me. It looks to make sure that the pods are ready, not just Running, and then it waits just a little longer to allow time for leader election.
```
      initContainers:
        - name: init-post-install-job
          image: bitnami/kubectl:1.13
          command:
            - "/bin/bash"
            - "-c"
            - |
              echo "waiting for {{ .Values.server.replicas }} servers...";
              COUNT=0; 
              while [[ $COUNT -lt {{ .Values.server.replicas }} ]]; do 
                COUNT=$(kubectl get pods -n {{ .Release.Namespace }} -l "app=consul,component=server" | grep -E '([0-9]+)/\1' | wc -l); 
                echo "waiting for {{ .Values.server.replicas }} servers ... $COUNT"; 
                sleep 10s; 
              done; 
              sleep 10s;
```

**Comment by dschaaff** [comment]
That makes more sense than a long sleep (added out of frustration lol).

**Comment by ljupchokotev** [comment]
I have tried the init container from @blakeblackshear but it doesn't seem to work for me. I still get
```Error bootstrapping Consul agent: Unexpected response code: 403 (Permission denied: rpc error making call: ACL bootstrap no longer allowed (reset index: 17))``` on the `server-acl-init` job. Has anybody identified why this happens?

**Comment by ljupchokotev** [comment]
I have tested with the init container from @blakeblackshear and it worked for me, I got the `server-acl-init` job to successfully bootstrap ACL on the cluster. 

Note for people who have TLS encryption enabled based on the PR #137, the enterprise-license job will fail since it uses curl to update the license on the cluster, but it doesn't send the ACL token.

**Comment by blakeblackshear** [comment]
@ljupchokotev Don't forget that deleting the helm release does not remove persistent volumes. You will need to delete them manually if you want to rerun the helm chart again in the same namespace. Or deleting the namespace will work as well. You will get this error if the new helm install tries to use the old volumes.
