### ISSUE TITLE
Clarify that the pod service account name must be equal the Consul service name when ACLs are enabled

### ISSUE THREAD

**Issue by HansK-p** [hashicorp/consul-helm#202]
I just spent an embarrassingly amount of time on troubleshooting why sidecar injection didn't work as soon as ACLs were enabled in the Helm Chart. After a lot of debugging and looking into source code, I finally understood that the pod service account name (K8s: ServiceAccount) has to match the Consul service name exactly (Annotation: consul.hashicorp.com/connect-service) when ACLs are enabled.

This is possible to understand from the existing documentation and I assume most people do this correctly, but I must admit I didn't understand this requirement until after I had spent time troubleshooting the issue.

One option is to make the text in https://www.consul.io/docs/platform/k8s/helm.html, where the option aclBindingRuleSelector is described, even clearer as to this requirement.

**Comment by nicholasjackson** [comment]
Hi, yes, the ServiceAccount name must be the same as the service name. 

The name of the service is inferred from two possible sources:

This can be stated explicitly using the annotation `consul.hashicorp.com/connect-service`
[https://www.consul.io/docs/platform/k8s/connect.html#consul-hashicorp-com-connect-service](https://www.consul.io/docs/platform/k8s/connect.html#consul-hashicorp-com-connect-service)

Or the service name will be automatically configured based on the name of the first container in the pod.

**Comment by HansK-p** [comment]
It took far too long before I understood that ACL tokens were created based on the K8s service account name. At first I thought it was sufficient that the service name wasn't "default".

Which means that the serviceAccountName used in the pod has to be exactly the same as the name of the first container in the pod or as is set by the annotation consul.hashicorp.com/connect-service (as you have already written).

I think it would be wise to state this more explicitly in the documentation (and it's quite possible that it's stated in the right place and that I just haven't seen it).

**Comment by lkysow** [comment]
Hi @HansK-p, thanks for the issue. Agreed that we should document this!
