### ISSUE TITLE
(connectInject) acl-init job does not work unless chart is deployed in "default" namespace

### ISSUE THREAD

**Issue by jtcressy** [hashicorp/consul-helm#215]
Ok, so this is really because the "kubernetes" service is only in the default namespace, by default.

Edit: Looks like connectInject needs to setup the kubernetes auth method and causes this error when getting the "kubernetes" service.

consul-chart version: v0.8.1
helm/tiller version: 2.14.3
I'm running this on a GKE cluster version 1.13.7.

Commands used to deploy the chart:
```
git clone https://github.com/hashicorp/consul-helm
cd consul-helm
git checkout v0.8.1
cd ..
helm upgrade
      --install
      --namespace consul-13748846
      --force
      --set global.bootstrapACLs=true
      --set connectInject.enabled=true
      --set connectInject.centralConfig.enabled=true
      --set client.grpc=true
      consul-server
      ./consul-helm
```

I grabbed the logs from the job:
```
> $ kubectl logs consul-test-consul-server-acl-init-9brzt
2019-08-13T16:22:18.804Z [INFO ] 10.24.46.29:8500
2019-08-13T16:22:18.804Z [INFO ] 10.24.57.9:8500
2019-08-13T16:22:18.804Z [INFO ] 10.24.54.12:8500
Error getting kubernetes service: services "kubernetes" not found
```

I ran this in a namespace called "consul-13748846", and since it wasn't the "default" namespace, it didnt have the "kubernetes" service. The cluster is properly bootstrapped with acls, but because it never writes the acl token to a secret, the deployment is effectively failed and you have a perma-locked consul installation. I have to manually clean up the job and pvc resources after deleting (with --purge) the chart.

So, either the kubernetes service needs to be called by its FQDN, or the helm chart needs to create a kubernetes service in the namespace that points to the cluster's api endpoint(s).

At the moment, the only workaround is to just deploy the chart in the default namespace. Afterall, it doesn't matter *too* much which namespace it's in because the helm chart sets up cluster-wide rbac but without a doubt there are going to be operators who desire the separation.

**Comment by infa-bsurber** [comment]
I've been using bootstrapACLs in a different namespace for a long time now. The server & client ACL tokens are written to the same namespace as K8s secrets.

However, the job to do the acl initialization can hit a race condition and fail infinitely (see https://github.com/hashicorp/consul-helm/issues/186 https://github.com/hashicorp/consul-helm/issues/198), or it may not have the right access required to finish.

You can confirm this with `kubectl get pods --namespace=consul-13748846`. You should see that the acl init job pods are all in "error" state. If they're not there, the job probably succeeded and you can check for the new server and client acl tokens via `kubectl get secret --namespace=consul-13748846`.

**Comment by jtcressy** [comment]
The job never succeeds, but I just noticed that it *does* create the secrets. What I don't understand, is if it created the secrets, why does it say `services "kubernetes" not found`?

Additionally, the next pod that gets started by the job fails with "Permission denied: ACL bootstrap no longer allowed" since the cluster was successfully bootstrapped in the previous job attempt.

Here's the output of two consecutive job attempts:
```
> $ kubectl logs consul-test-consul-server-acl-init-7rt7p
2019-08-13T17:21:07.842Z [INFO ] 10.24.46.31:8500
2019-08-13T17:21:07.842Z [INFO ] 10.24.57.23:8500
2019-08-13T17:21:07.842Z [INFO ] 10.24.54.14:8500
Error getting kubernetes service: services "kubernetes" not found
```
Then,
```
> $ kubectl logs consul-test-consul-server-acl-init-4g4cw
2019-08-13T17:21:47.679Z [INFO ] 10.24.46.31:8500
2019-08-13T17:21:47.680Z [INFO ] 10.24.57.23:8500
2019-08-13T17:21:47.680Z [INFO ] 10.24.54.14:8500
Error bootstrapping Consul agent: Unexpected response code: 403 (Permission denied: ACL bootstrap no longer allowed (reset index: 14))
```

Additionally, this happens *every time* I run the chart in a namespace other than default. If this were a race condition, wouldn't it sometimes complete successfully?

Extra info:
```
> $ kubectl get secret | grep acl
consul-test-consul-bootstrap-acl-token                            Opaque                                1      6m58s
consul-test-consul-client-acl-token                               Opaque                                1      6m57s
consul-test-consul-server-acl-init-token-8xp42                    kubernetes.io/service-account-token   3      7m34s
```
```
> $ kubectl get pod | grep acl
consul-test-consul-server-acl-init-4g4cw                          0/1     Error     0          6m52s
consul-test-consul-server-acl-init-57db2                          0/1     Error     0          4m12s
consul-test-consul-server-acl-init-5zb9d                          0/1     Error     0          8m2s
consul-test-consul-server-acl-init-6pcpm                          0/1     Error     0          8m4s
consul-test-consul-server-acl-init-7rt7p                          0/1     Error     0          7m32s
consul-test-consul-server-acl-init-n6rcn                          0/1     Error     0          7m52s
```

**Comment by infa-bsurber** [comment]
Interesting, which chart + k8sImage versions are you using?

**Comment by infa-bsurber** [comment]
Ah, found the acl-init job code for what you're hitting. This explains why I've never seen this error (I don't use ConnectInject):
https://github.com/hashicorp/consul-k8s/blob/master/subcommand/server-acl-init/command.go#L303-L310

**Comment by jtcressy** [comment]
Chart is v0.8.1 and the k8sImage is the default defined in the chart.
These are the exact commands I use to deploy:
```
git clone https://github.com/hashicorp/consul-helm
cd consul-helm
git checkout v0.8.1
cd ..
helm upgrade
      --install
      --namespace consul-13748846
      --force
      --set global.bootstrapACLs=true
      --set connectInject.enabled=true
      --set connectInject.centralConfig.enabled=true
      --set client.grpc=true
      consul-test
      ./consul-helm
```

**Comment by jtcressy** [comment]
Ah, if this is specific to connect inject I can edit the title of this issue to better indicate scope

**Comment by lkysow** [comment]
FYI, I just merged #107 which fixes the issue with namespaces and the `kubernetes` service.

**Comment by lkysow** [comment]
I think that fixes your issue but if not please comment and I can re-open.

**Comment by jtcressy** [comment]
@lkysow Did you mean to link a PR? #107 looks like an issue from way back, and unrelated.

**Comment by lkysow** [comment]
Oops, this is the one: https://github.com/hashicorp/consul-k8s/pull/107
