### ISSUE TITLE
Getting ACL master token.

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#218]
Good morning guys, I'm deploying consul as a service discovery on my Kubernetes framework and trying to enable ACL he's asking for a SecretID or Master Token, but what I got from Kubernetes Secret didn't work out. Where can I get this token?

versions
Consul server - 1.5.0
consul-helm 0.9

_Originally posted by @cristhianbicca in https://github.com/hashicorp/consul-helm/issues/180#issuecomment-517767696_

**Comment by jshdcmpbll** [comment]
Hey @lkysow I am also having this issue. I assume issue #202 wasn't your solution to this problem, correct?

**Comment by jshdcmpbll** [comment]
Also having this issue.

Helm presents the following error after waiting about 8 minutes for consul to complete its ACL bootstrap: `Error: timed out waiting for the condition`.

Here are the secrets in Kubernetes:

**Comment by lkysow** [comment]
To get the bootstrap token:
1. Get your helm release name:
    ```sh
    $ helm list
    NAME          REVISION  UPDATED                   STATUS    CHART         APP VERSION NAMESPACE
    virulent-bobcat  3         Mon Sep 16 17:29:54 2019  DEPLOYED  consul-0.9.0              default
    ```
1. Get the secret with name `<release-name>-consul-bootstrap-acl-token`:
    ```sh
    $ kubectl get secret virulent-bobcat-consul-bootstrap-acl-token -o yaml
    apiVersion: v1
    data:
      token: MmM3ODJiMjgtY2MwZi1hZjAzLTI2YzktZDMxYmY4YjljZmU3
    kind: Secret
    metadata:
      creationTimestamp: "2019-09-11T19:17:57Z"
      name: virulent-bobcat-consul-bootstrap-acl-token
      namespace: default
      resourceVersion: "25410476"
      selfLink: /api/v1/namespaces/default/secrets/virulent-bobcat-consul-bootstrap-acl-token
      uid: dc99d72a-d4c8-11e9-8faa-42010a800122
    type: Opaque
    ```
1. Use `base64 -D` to decode the token:
    ```sh
    $ echo MmM3ODJiMjgtY2MwZi1hZjAzLTI2YzktZDMxYmY4YjljZmU3 | base64 -D
    2c782b28-cc0f-af03-26c9-d31bf8b9cfe7
    ```


As a one-liner:
```sh
$ kubectl get secrets/virulent-bobcat-consul-bootstrap-acl-token --template={{.data.token}} | base64 -D
2c782b28-cc0f-af03-26c9-d31bf8b9cfe7%
```

**Comment by lkysow** [comment]
@jshdcmpbll I think your issue is different from the original poster's issue.

I think #198 is the problem you were having which is fixed in v0.9.0

**Comment by lkysow** [comment]
I'm going to close this because I think the original question is answered.

**Comment by seguidor777** [comment]
Hi,

I am working with version 1.8.1
Is there an easier way to get the ACL bootstrap token? Maybe a programmatic approach or an initial installation with a custom token

**Comment by ishustava** [comment]
Hey @seguidor777 

Did you see the one-liner Luke posted above: `kubectl get secrets/virulent-bobcat-consul-bootstrap-acl-token --template={{.data.token}} | base64 -D`? Maybe you could explain a bit what you mean by a programmatic approach. Maybe something within the consul CLI that helps you get the token or uses the kube secret?

You could provide your own token by setting [`global.acls.bootstrapToken`](https://www.consul.io/docs/k8s/helm#v-global-acls-bootstraptoken).

**Comment by seguidor777** [comment]
Hi @ishustava, thanks for your quick reply

I already saw that command and actually is the approach that I am following.
In that case I think that I have to use the K8s API to get the token from a Golang program.
As far as I understand the global.acls.bootstrapToken is for providing a token from a previous installation when an ACL initialization is not longer required for the servers.
I would like to make an initial installation and be able to provide the bootstrap token by the first time, when I try to do that with the bootstrapToken setting, it is ignored and consul generates a new one into the release-consul-bootstrap-acl-token secret

**Comment by ishustava** [comment]
I see what you mean. I think you can provide a [`master` token](https://www.consul.io/docs/agent/options#acl_tokens_master) either via `server.extraConfig` or `server.extraVolumes`. You would then also have to save it as a secret and provide it via the bootstrap token property so that the rest of the helm chart will use ACLs too.

**Comment by seguidor777** [comment]
Just tried with the master token option as well as the bootstrap token property as you mentioned but I got this error
`Error getting Kubernetes secret: secrets "consul-consul-client-acl-token" not found`
Am I missing anything else?
Please let me know if you want me to create a new issue to address this

**Comment by ishustava** [comment]
Hey @seguidor777 

Yes, I think this warrants a new issue! Thank you 🙏

**Comment by seguidor777** [comment]
https://github.com/hashicorp/consul-helm/issues/569
