### ISSUE TITLE
support container image repository override

### ISSUE THREAD

**Issue by dorsany** [hashicorp/consul-helm#221]
in case of air gap cluster installation, We need to pass the container registry to the container image so the consul containers (server,client,sync catlaog and etc...) will be able to pull the image from the [local docker registry](https://docs.docker.com/registry/deploying/) in order to avoid ```ImagePullBackOff```

For example:
https://github.com/hashicorp/consul-helm/blob/11b1a12a16715c62e43e7aa0d5af124ef2bacfd4/templates/server-statefulset.yaml#L74

can be change to:
```
image: "{{ .Values.global.localRegistry }}{{ default .Values.global.image .Values.server.image }}"
```
and the default value ```.Values.global.localRegistry``` should be ```null``` in ```values.yaml``` , and on air-gap installation we will be able to change it to ```.Values.global.localRegistry: <registry url>/```
possible also to add this to each service. something like:
```
image: "{{ .Values.server.localRegistry | default .Values.global.localRegistry }}{{ default .Values.global.image .Values.server.image }}"
```

inspired from : https://github.com/helm/charts/tree/master/stable/nginx-ingress#configuration

I can make a PR if needed

**Comment by lkysow** [comment]
@dorsany thanks for the ticket.

Can't you set the repository using the existing values?
```yaml
global:
  image: my.private.registry/consul:1.5.0
```

**Comment by dorsany** [comment]
I will. Thanks
