### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by ALuongIBM** [hashicorp/consul-helm#229]
Hi there, I'm trying to deploy a 3 server, 3 client Consul to my IBM Cloud Kubernetes cluster using this Helm chart and although the pods end up in a `0/1` running state, I keep getting this error. I'm open to any suggestions, having searched previous issues this looks like an affinity error (so I've set `affinty: null` to no avail).
``` Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  19s (x4 over 83s)  default-scheduler  pod has unbound immediate PersistentVolumeClaims (repeated 3 times)

**Comment by ALuongIBM** [comment]
Also worth noting,
when I `kubectl describe pv pvc-a82a6414-da1b-11e9-84f5-4e450`, I get this:
```Status:          Bound
Claim:           default/data-default-consul-consul-server-0```

**Comment by ALuongIBM** [comment]
Hi all this was a bug on my end with configuring my personal Kubernetes cluster. For anyone that might find this: https://cloud.ibm.com/docs/infrastructure/vlans?topic=vlans-vlan-spanning Might help if you are on IBM Kubernetes Service.

**Comment by lkysow** [comment]
For future readers what did you have to do for vlan spanning to stop getting this error?

**Comment by ALuongIBM** [comment]
There is a toggle in IBM Cloud to enable VLAN spanning under Classic Infrastructure > Network > VLAN, flip `VLAN Spanning` to `On`, hope that helps @lkysow and apologies as I know this is not specifically related to Consul at all :D

**Comment by lkysow** [comment]
No worries thanks for letting the next person know!
