### ISSUE TITLE
Consul DNS not working with external DNS calls

### ISSUE THREAD

**Issue by prendi** [hashicorp/consul-helm#230]
Hello!

I'm trying to make DNS calls to services outside my k8s cluster (e.g. RDS instance) but it seems that once I configure CoreDNS's configmap with:
```
Corefile: |
    .:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . <CONSUL DNS SERVICE IP>
        cache 30
        loop
        reload
        loadbalance
        log
        whoami
    }
```
the calls to every external service stop working. Nevertheless, internal cluster calls still work.

Thanks in advance!

**Comment by lkysow** [comment]
Hi Gonçalo,
Can you give me an example DNS lookup (using `dig` or `nslookup` or `curl`) and the error you get back please?

**Comment by prendi** [comment]
Hi Luke, sorry for the delay!

Running a pod that executes: `dig +search <database url>` I get the following response:

`Fri Sep 20 10:50:07 UTC 2019

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> +search <database url>
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 30130
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;<database url> IN A

;; Query time: 1 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; WHEN: Fri Sep 20 10:50:07 UTC 2019
;; MSG SIZE  rcvd: 75

Fri Sep 20 10:50:07 UTC 2019
Could not resolve hostname.`

**Comment by lkysow** [comment]
I think you need the `consul` blog to be outside the `.:53` block:
```
  Corefile: |
    .:53 {
        <Existing CoreDNS definition>
    }
    consul {
      errors
      cache 30
      proxy . <consul-dns service cluster ip>
    }
```

**Comment by prendi** [comment]
I've tried this and the errors go away, however, that means that I would be proxying DNS requests ending in .consul right? Which is not the kind of requests I'm testing since I want to call services outside the cluster. Please let me know if I'm wrong

**Comment by lkysow** [comment]
Yes you're correct, however you shouldn't be using Consul DNS to resolve anything that isn't a Consul registered service. So in your case of using RDS, there's no need to use Consul to resolve that hostname since it's not a Consul service.

Maybe I'm missing something though. Can you help me understand why you want to use Consul DNS in this case? Thanks!

**Comment by prendi** [comment]
hum I see, I was actually trying to use consul to resolve all DNS requests (inside and outside the cluster) hoping that the caching would help us with some DNS problems we are having. Is this not a valid use case?

**Comment by lkysow** [comment]
Actually I'm incorrect. Consul can be configured to resolve queries outside of its domain via the `-recursors` flag (see https://www.consul.io/docs/agent/options.html#recursors). Sorry for the confusion.

When you were testing did you set this flag?

Regarding caching, according to [the docs](https://www.consul.io/docs/agent/options.html#dns_use_cache):
> use_cache - When set to true, DNS resolution will use the agent cache described in agent caching. This setting affects all service and prepared queries DNS requests. Implies allow_stale

We don't perform caching for external queries, so I'm not sure it would help. I haven't tested this though.

**Comment by prendi** [comment]
@lkysow Sorry for the (very) delayed response. I guess we will give it a try and see if it helps! I'm closing this for now as it doesn't seem to be an issue, just a misconfiguration.
