### ISSUE TITLE
Document how to use the chart without tiller

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#232]
Document how to use `helm template`

**Comment by filintod** [comment]
I had this problem, and one issue to use it without Helm is that some parts, like server ACL init, do require the usage of helm hooks to execute after installation if you want to use the ACL parts.  What I have done is partition this to execute everything but the server-acl-init-job, that is only created when an extra variable is added, in my case I called it bootstarpACLsInit.

**Comment by lkysow** [comment]
Now that Helm 3 is released tiller is not required. This chart supports Helm 3.
The chart relies on Helm hooks for some of its features like TLS, ACL Init. These features won't work if using `helm template` so it no longer makes sense to document this.
