### ISSUE TITLE
Support for annotations on ServiceAccounts

### ISSUE THREAD

**Issue by kri5** [hashicorp/consul-helm#235]
In order to be able to use feature such as [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), it would be great to allow user to specify annotations for the various services accounts supported by this chart.

One use case would be, you want to deploy the clients on k8s, to out-of-cluster servers, using cloud auto-join discovery (gce here), and you need to have permission to do so. Annotations would allow to "inject" the google credentials to the kubernetes services account and allow the clients to discover the servers.

**Comment by jtcressy** [comment]
👋 Adding support for service account annotations will also enable workload identity in AWS. IAM Roles for Service Accounts uses annotations to control injection of credentials.
