### ISSUE TITLE
Reconsider global variables in values.yaml

### ISSUE THREAD

**Issue by tongpu** [hashicorp/consul-helm#238]
Because of the way global variables are implemented in this and the vault chart it is currently impossible to configure the consul chart as a dependency/subchart of the vault chart, because `global.image` with the value `vault:1.2.2` from the vault chart will also be rendered in the consul templates, because it too uses `global.image` for the configuration of the image version.

It is not recommended to use global variables in helm charts in this way and I would propose to switch to the normal way this is implemented in helm/charts, e.g.

```yaml
image:
  repository: consul
  tag: 1.6.1
```

For vault this change might be rather straightforward, because not many variables are currently defined in global, but for consul more variables are already defined as global variables.

The issue is also tracked in vault-helm: hashicorp/vault-helm#68

**Comment by lkysow** [comment]
Hi Lukas,
Thanks for the issue. This is unfortunate that helm treats that variable differently. I'm guessing we didn't know that at the time.

I can look at what it would take to use a different name and keep backwards compatibility.

**Comment by lkysow** [comment]
Hi Lukas, unfortunately I don't think we're ever going to be able to change the `global` variable. It would break backwards compatibility too much.

Since vault has made the change to `server.image` I think this does solve the particular problem you're encountering.
