### ISSUE TITLE
Consul DNS delay on k8s

### ISSUE THREAD

**Issue by luanbon** [hashicorp/consul-helm#244]
I have a consul and kubernetes cluster running on Azure, my kubernetes is running consul agents as client installed by Helm Chart. Both servers and clients are running consul 1.6.0.

I enabled DNS on kubernetes with coredns, it is working as expected, but sometimes the dns delays some seconds to responde or it returns the follow message, **Could not resolve host: participant-api.service.consul** when trying to make an http request like http://participant-api.service.consul/api/environment. Doing tests with a container (kubectl run --generator=run-pod/v1 -it --rm --image anubhavmishra/tiny-tools dnstools), running '**dig consul.service.consul**', i need to try 3 times or more to get the properly response. These problems is affecting the communication between two microservices running inside the k8s cluster through consul dns.

Should I need enable a kind cache on consul clients running inside k8s ? If yes, which documentation i need to follow to get working properly ?

**Comment by tylrd** [comment]
@luanbon do you node autoscaling enabled on your cluster? 

We are seeing a similar issue and it seems to be correlated with autoscaling events.

**Comment by lkysow** [comment]
@tylrd @luanbon are you both still seeing this issue?

**Comment by luanbon** [comment]
> @tylrd @luanbon are you both still seeing this issue?

Yes, i implemented a retry mechanism in all my apis as a workaround, sometimes consul cannot process dns requests.

**Comment by tylrd** [comment]
@lkysow We added a new service that targets consul agents on a node pool without autoscaling enabled. We added the ClusterIp of the service as a secondary entry in the kube-dns configmap. We have not had any unknown host exceptions since this change.

**Comment by lkysow** [comment]
Thanks so much for your response. We'll keep this open then since it still needs investigation.

**Comment by lkysow** [comment]
Closing because this has been without activity for a long time.
