### ISSUE TITLE
Consul_Kubernetes_Installation Issue

### ISSUE THREAD

**Issue by Yukeshraja** [hashicorp/consul-helm#252]
Hi Team,

I have a Kubernetes 3Node cluster with rook as a storage class (Default). I tried to install the consul in kubernetes facing below issues.

I added rook as storage class in the volume.yaml but still the issue persists. 
![image](https://user-images.githubusercontent.com/15683376/66912160-ad1d0480-f02f-11e9-9f73-c9a9eec9d1b5.png)

Running a fresh installation using bootstrapACLs is running into a deadlock
The consul-server-acl-init job is responsible for bootstrapping ACLs on the server (generating the bootstrap token & generating the server token) and is a job with a post-install hook.
The consul client pod has an initContainer "client-acl-init" which is stuck waiting for that bootstrap token secret and so, pod installation won't finish until the bootstrap token exists.
So, the consul-server-acl-init job will only kick off when installation is finished but installation can't finish until the consul-server-acl-init job runs.

Thanks in advance.

**Comment by lkysow** [comment]
Hi @Yukeshraja,
The consul-server-acl-init Job needs the Consul servers to elect a leader before it can succeed. What does the output of `kubectl get pod | grep consul` say? I would look at the logs for the Consul servers and see if they're running and have elected a leader successfully. Also can you show us the logs for the `server-acl-init` Job?

Finally, the latest version of this chart (v0.11.0) has some bugfixes so I'd recommend trying with that.

**Comment by Yukeshraja** [comment]
![image](https://user-images.githubusercontent.com/15683376/68849862-dc8b6380-06f8-11ea-8f9a-6be9e4c132fe.png)

**Comment by Yukeshraja** [comment]
Hi,

Facing below issue.

![image](https://user-images.githubusercontent.com/15683376/68923683-e10d5600-07a4-11ea-96f7-372b72eb406b.png)

**Comment by adilyse** [comment]
Related: #10
