### ISSUE TITLE
helm test fails when ACLs enabled

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#258]
```
$ helm test lazy-quail
RUNNING: lazy-quail-consul-test
FAILED: lazy-quail-consul-test, run `kubectl logs lazy-quail-consul-test --namespace default` for more info
Error: 1 test(s) failed
```

```
$ kubectl logs lazy-quail-consul-test --namespace default
Error deleting key _consul_helm_test: Unexpected response code: 403 (rpc error making call: Permission denied)
```

**Comment by ashwin-venkatesh** [comment]
After a conversation with @lkysow and @ishustava , updating the test to use `consul members` as a solution will provide a useful smoke test for the time being. The status of the `consul-server` will be used to determine if the installation was successful. 

Additionally, it made sense to expand the responsibility of the `helm test`  to provide better debugging information. The specifics of what that test will look like are yet to be determined, but shall be raised as a separate issue.
