### ISSUE TITLE
When using 'extraVolumes' to mount secrets, Consul errors on start with 'data_dir is empty'

### ISSUE THREAD

**Issue by thisLambo** [hashicorp/consul-helm#26]
When using the `extraVolumes` configuration option in the `values.yaml`, the Helm chart fails to start Consul correctly with the error `data_dir is empty`.

All secrets exist and when tested by telling the chart by setting them to `load: false` Consul starts correctly.

Upon further investigation the issue appears to be a missing `\` in the loop that adds the extra config directories for the statefulset and the daemonset:

https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L91
https://github.com/hashicorp/consul-helm/blob/master/templates/client-daemonset.yaml#L77

I would submit a Pull Request but the company I work for currently doesn't have a policy in place for contributing to open source software.

**Comment by adilyse** [comment]
Good catch! The fix is now merged, so it will be available in the next release.
