### ISSUE TITLE
Support monitoring through prometheus operator

### ISSUE THREAD

**Issue by faheem-nadeem** [hashicorp/consul-helm#262]
Hi,

It would be awesome if support for Prometheus operator can be integrated for collecting metrics. 

Support can be added using a simple ServiceMonitor or PodMonitor crd. 

**API Reference:**
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitor

**Example:** 
https://github.com/coreos/prometheus-operator/blob/master/example/user-guides/getting-started/example-app-service-monitor.yaml

**Comment by david-yu** [comment]
Hi @faheem-nadeem I'm going to close this as we have an identical issue #494. Thank you for filing, this is on our radar but not something we have planned on doing in the short term.
