### ISSUE TITLE
Consul members unable to elect a leader

### ISSUE THREAD

**Issue by tsturzl** [hashicorp/consul-helm#264]
Basically what I'm seeing is all of the consul pods in the statefulset are running, but their readiness probes never succeed because the consul peers never elect a leader. I had previously had a cluster up and running, but removed it since it wasn't needed immediately. This was about 3 days ago. I deleted the PVC's from the stateful set after purging through helm, and when I recreated I'm unable to get the cluster working again. Nothing in the helm values have changed.

All of the logs from each of the 3 nodes looks like this:

```
bootstrap_expect > 0: expecting 3 servers
==> Starting Consul agent...
           Version: 'v1.6.1'
           Node ID: 'c63f2fbf-6a8a-647d-d4e2-61ae0b7f5276'
         Node name: 'vault-consul-consul-server-0'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
      Cluster Addr: 100.96.12.37 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

    2019/10/22 20:36:39 [INFO]  raft: Initial configuration (index=0): []
    2019/10/22 20:36:39 [INFO]  raft: Node at 100.96.12.37:8300 [Follower] entering Follower state (Leader: "")
    2019/10/22 20:36:39 [INFO] serf: EventMemberJoin: vault-consul-consul-server-0.dc1 100.96.12.37
    2019/10/22 20:36:39 [INFO] serf: EventMemberJoin: vault-consul-consul-server-0 100.96.12.37
    2019/10/22 20:36:39 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
    2019/10/22 20:36:39 [INFO] consul: Adding LAN server vault-consul-consul-server-0 (Addr: tcp/100.96.12.37:8300) (DC: dc1)
    2019/10/22 20:36:39 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
    2019/10/22 20:36:39 [INFO] consul: Handled member-join event for server "vault-consul-consul-server-0.dc1" in area "wan"
    2019/10/22 20:36:39 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
    2019/10/22 20:36:39 [INFO] agent: started state syncer
==> Consul agent running!
    2019/10/22 20:36:45 [WARN]  raft: no known peers, aborting election
    2019/10/22 20:36:46 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:37:02 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:37:21 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:37:25 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:37:51 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:37:55 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:38:19 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:38:21 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:38:43 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:38:47 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:39:11 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:39:16 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:39:34 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:39:47 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:40:11 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:40:14 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:40:37 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:40:39 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:41:05 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:41:14 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:41:27 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:41:48 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:41:54 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:42:17 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:42:24 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:42:40 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:42:58 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:43:05 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:43:25 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:43:30 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:43:54 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:44:02 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:44:19 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:44:26 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:44:46 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:44:53 [ERR] agent: Coordinate update error: No cluster leader
    2019/10/22 20:45:17 [ERR] agent: failed to sync remote state: No cluster leader
    2019/10/22 20:45:18 [ERR] agent: Coordinate update error: No cluster leader
```

All of the pods are running:

```
vault-consul-consul-server-0                                      0/1     Running     0          12m
vault-consul-consul-server-1                                      0/1     Running     0          12m
vault-consul-consul-server-2                                      0/1     Running     0          12m
```

Trying to grab the peer list with `kubectl exec -it vault-consul-consul-server-0 -- consul operator raft list-peers` gives me: `Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 500 (No cluster leader)` and additionally see `2019/10/22 20:49:39 [ERR] http: Request GET /v1/operator/raft/configuration, error: No cluster leader from=127.0.0.1:50946` in the vault-consul-consul-server-0 pod's logs.

Here's a [gist of my helm values](https://gist.github.com/tsturzl/6adb1cd573aa39f509127192e54542e7). Created with the command `helm install ./consul-helm --name vault-consul -f consul-oveerrides.yaml`. I've created against the master branch, and `v0.11.0` tag, both with the same result.

**Comment by tsturzl** [comment]
I manually got all of the consul peers to join eachother by invoking `consul join <podIP>`, to get 2 of the nodes to join one. If I delete a pod and let it come back it gets stuck in again not being able to find it's peers. Because of this behavior this is not a suitable solution. It seems as though my peers have trouble finding each other. I'm not exactly sure how the peers find each other, I'm not sure how discovery is being done, but it seems to be giving me a different result compared to 3 days prior. Is this DNS based? Does it use the k8s api to query other peers in its statefulset? Should I examine my ClusterRoles?

**Comment by s3than** [comment]
I'm seeing the same issue now k8s version 1.14.8

**Comment by s3than** [comment]
@tsturzl Can you advise what Helm version you are using?

I've found that the following section isn't being added to the statefulset with helm v2.15.0

```
{{- range $index := until (.Values.server.replicas | int) }}
-retry-join=${CONSUL_FULLNAME}-server-{{ $index }}.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
{{- end }}
```

**Comment by tsturzl** [comment]
@s3than great find. This would explain the issue for me likely as well as I've recently upgraded helm and thats the only thing that I can think of that would be different from a few days prior when I wasn't having this issue. Seems like it could be a simple thing to fix. I can make some changes locally and submit a PR when I can verify it working, unless you'd rather address the issue.

**Comment by tsturzl** [comment]
This is likely the issue, I'm using helm 2.15.0. Would you recommend downgrading for the time being?

**Comment by s3than** [comment]
The fix for 2.15.0 is to quote the number in the values file

```
server:
   replicas: "3"
```

I'm not sure what impact that has on people who are still on 2.14.x though

I've looked through the current unit test cases and see that it doesn't include anything about replica set counts.

I can look at adding a PR for adding the tests and updating the values

**Comment by s3than** [comment]
Resolution is same as #265

**Comment by tsturzl** [comment]
@s3than I appreciate your quick response. I'll try your solution this morning and see what I come back with. Does your PR #266 fix this issue?

**Comment by tsturzl** [comment]
I actually took @filintod advice in your PR and upgraded helm to 2.5.1 which fixed my issue. This seems to be an issue with helm.

**Comment by lkysow** [comment]
Nice! Yeah I think that's the best solution.
