### ISSUE TITLE
Make `-acl-auth-method ` configurable

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#271]
See https://github.com/hashicorp/consul-k8s/issues/131, when using external Consul servers and configuring ACLs yourself, we need to make the `-acl-auth-method` flag configurable so users can set it to whichever auth method name they create:

https://github.com/hashicorp/consul-helm/blob/master/templates/connect-inject-deployment.yaml#L55-L57

**Comment by ishustava** [comment]
@lkysow I think we [do](https://github.com/hashicorp/consul-helm/blob/327ce4f484769f0a7948a0e65462e18d1ec1e1bd/templates/connect-inject-deployment.yaml#L88-L92) via the [`connectInject.overrideAuthMethodName`](https://github.com/hashicorp/consul-helm/blob/327ce4f484769f0a7948a0e65462e18d1ec1e1bd/values.yaml#L892-L894). Should we close this?

**Comment by lkysow** [comment]
Yep, looks like it!
