### ISSUE TITLE
Consul Agent not setting -retry-join

### ISSUE THREAD

**Issue by jeromebaude** [hashicorp/consul-helm#273]
For some reasons, the client-daemonset.yaml didn't launch consul with the -retry-join 

When looking more closely, the following range action was not working as expected:

Although server.replicas = 1, the following action didn't create the -retry-join
     
{{- range $index := until (.Values.server.replicas | int) }}
-retry-join=${CONSUL_FULLNAME}-server-{{ $index }}.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \

(Using helm charts 0.11.0 and Helm version 2.15.0 - client and server)

**Comment by lkysow** [comment]
Hi @jeromebaude you need to upgrade to helm 2.15.1. There's a bug in helm 2.15.0.

Release notes: https://github.com/helm/helm/releases/tag/v2.15.1
Related: https://github.com/hashicorp/consul-helm/issues/264, https://github.com/hashicorp/consul-helm/issues/265.
