### ISSUE TITLE
Unable to access consul servers from external datacenter

### ISSUE THREAD

**Issue by tomwganem** [hashicorp/consul-helm#28]
If I want to connect a kubernetes consul cluster with another consul cluster in another datacenter over WAN, the communication only works one way, because this helm chart does not expose a route to the consul servers. So within the kubernetes cluster, I can resolve services that are running in the external datacenter. But if I'm in the external datacenter, I'm unable to resolve services that are running in the kubernetes cluster. The error given is `500 (rpc error: No path to datacenter)`

**Comment by lkysow** [comment]
This has been solved in Consul 1.8.0 with WAN Federation via mesh gateways. See https://www.consul.io/docs/k8s/installation/multi-cluster/overview for more details.
