### ISSUE TITLE
Support OpenShift

### ISSUE THREAD

**Issue by kawsark** [hashicorp/consul-helm#283]
I am trying to deploy `consul-helm` on OpenShift but the StatefulSet and DaemonSet are not deploying. Need instructions for creating appropriate Security context on OpenShift. More details below:
**OpenShift version**
```
[ec2-user@ip-10-0-1-75 ~]$ oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://ip-10-0-1-75.ec2.internal:8443
openshift v3.11.0+bd0bee4-337
kubernetes v1.11.0+d4cacc0
```
**Statefulset**
```
[ec2-user@ip-10-0-1-75 ~]$ kubectl get statefulset/consul-oc-consul-server
NAME                      DESIRED   CURRENT   AGE
consul-oc-consul-server   3         0         7h
[ec2-user@ip-10-0-1-75 ~]$ kubectl describe statefulset/consul-oc-consul-server
```
Warning  FailedCreate  3s (x959 over 7h)  statefulset-controller  create Pod consul-oc-consul-server-0 in StatefulSet consul-oc-consul-server failed error: pods "consul-oc-consul-server-0" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group]

**DaemonSet**
```
[ec2-user@ip-10-0-1-75 ~]$ kubectl get daemonset/consul-oc-consul
NAME               DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
consul-oc-consul   0         0         0         0            0           <none>          7h
[ec2-user@ip-10-0-1-75 ~] kubectl describe daemonset/consul-oc-consul
```
Events:
  Type     Reason        Age                From                  Message
  ----     ------        ----               ----                  -------
  Warning  FailedCreate  3m (x110 over 7h)  daemonset-controller  Error creating: pods "consul-oc-consul-" is forbidden: unable to validate against any security context constraint: [spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 8500: Host ports are not allowed to be used spec.containers[0].securityContext.containers[0].hostPort: Invalid value: 8502: Host ports are not allowed to be used]

**Comment by kawsark** [comment]
I am documenting some workarounds/remediations below for these 2 errors. These assume that consul template yaml were generated previously using helm. Below are the example commands:
```
mkdir -p ./manifests
helm template --name consul-oc --output-dir ./manifests -f oc.values.yaml .
cd ./manifests/consul/templates/
```

**Server Statefulset**:
A security context will need to be created for consul servers that specifies MustRunAs range of 1000.
The consul server service account will need to be added to this security context. Here is an example consul server scc definition modified from the restricted scc [consul-server-scc.yaml](https://github.com/kawsark/consul-helm-openshift-experimental/blob/master/manifests/consul/templates/server/consul-server-scc.yaml).
```
oc apply -f server-serviceaccount.yaml
oc apply -f consul-server-scc.yaml
oc get scc consul-server
oc adm policy add-scc-to-user consul-server -z consul-oc-consul-server
```

**Client Daemonset**:
A security context will need to be created for consul clients with `allowHostPorts: true`. The consul client service account will need to be added to this security context. Here is an example consul client scc definition modified from the restricted scc [consul-client-scc.yaml](https://github.com/kawsark/consul-helm-openshift-experimental/blob/master/manifests/consul/templates/client/consul-client-scc.yaml).
```
oc apply -f client-serviceaccount.yaml
oc apply -f consul-client-scc.yaml
oc get scc consul-client
oc adm policy add-scc-to-user consul-client -z consul-oc-consul-client
```

**Comment by kawsark** [comment]
I think it would be good to add a flag in `values.yaml` to auto-generate security contexts by helm. This will provide a better UX for installing consul in OpenShift. With the above contexts, I tested the helm chart successfully on OpenShift 4.2 without any other adjustments. Below is a link to example security contexts:
- [consul-client-scc.yaml](https://github.com/kawsark/consul-helm-openshift/blob/master/security-contexts/consul-client-scc.yaml)
- [consul-server-scc.yaml](https://github.com/kawsark/consul-helm-openshift/blob/master/security-contexts/consul-server-scc.yaml)

**Comment by kawsark** [comment]
I wanted to provide an update on this issue. By setting `enablePodSecurityPolicies: true` in `values.yaml`, it will generate a set of Pod Security Policy object definitions. These generated objects  should suffice on a default OpenShift install. If `SecurityContextConstraints` objects are being used, then you may need to convert the generated Pod Security Policies to SecurityContextConstraints.

**Comment by mrafieee** [comment]
when we get this feature?

**Comment by david-yu** [comment]
Hi @kawsark This is now supported in Helm 0.25, please try out our Openshift support for Consul on Kubernetes and provide any feedback if possible. Please reply with any feedback.
