### ISSUE TITLE
fullnameOverride prevents acl job from completing successfully

### ISSUE THREAD

**Issue by sbuzonas** [hashicorp/consul-helm#286]
Companion issue reported in hashicorp/consul-k8s#165

Given the following configuration values.yaml provided to helm:
```
fullnameOverride: consul
global:
  bootstrapACLs: true
```

The StatefulSet will be named `consul-server` and the bootstrap job will fail

**Comment by lkysow** [comment]
This is fixed in v0.15.0. Thanks!
