### ISSUE TITLE
node(s) didn't find available persistent volumes to bind.

### ISSUE THREAD

**Issue by itsecforu** [hashicorp/consul-helm#299]
Hello! 

I try to deply consul cluster on k8s.

Same pods with statr "Pending":

![2](https://user-images.githubusercontent.com/38696837/70140445-bcbae000-16a5-11ea-8989-86ae342cbc8f.png)

Persistent Volume Claims the same:

![1](https://user-images.githubusercontent.com/38696837/70140455-c2b0c100-16a5-11ea-8545-10e55bbda435.png)

``kubectl get pods
NAME                                     READY   STATUS    RESTARTS   AGE
minio-7fcf7bdfb5-xzdd9                   1/1     Running   0          27d
minio-deployment-5496b7cf8c-75j75        1/1     Running   0          27d
quarreling-hummingbird-consul-2clgq      0/1     Running   0          38s
quarreling-hummingbird-consul-52cdt      0/1     Running   0          38s
quarreling-hummingbird-consul-hx8fm      0/1     Running   0          38s
quarreling-hummingbird-consul-nk4hv      0/1     Running   0          38s
quarreling-hummingbird-consul-pt7gc      0/1     Running   0          38s
quarreling-hummingbird-consul-server-0   0/1     Pending   0          38s
quarreling-hummingbird-consul-server-1   0/1     Pending   0          38s
quarreling-hummingbird-consul-server-2   0/1     Pending   0          38s
quarreling-hummingbird-consul-vpx5w      0/1     Running   0          38s
quarreling-hummingbird-consul-xrdjw      0/1     Running   0          38s``

``# kubectl describe pod quarreling-hummingbird-consul-server-0
Name:           quarreling-hummingbird-consul-server-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app=consul
                chart=consul-helm
                component=server
                controller-revision-hash=quarreling-hummingbird-consul-server-59d88b5bbd
                hasDNS=true
                release=quarreling-hummingbird
                statefulset.kubernetes.io/pod-name=quarreling-hummingbird-consul-server-0
Annotations:    consul.hashicorp.com/connect-inject: false
Status:         Pending
IP:
Controlled By:  StatefulSet/quarreling-hummingbird-consul-server
Containers:
  consul:
    Image:       consul:1.6.2
    Ports:       8500/TCP, 8301/TCP, 8302/TCP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP
    Command:
      /bin/sh
      -ec
      CONSUL_FULLNAME="quarreling-hummingbird-consul"

      exec /bin/consul agent \
        -advertise="${POD_IP}" \
        -bind=0.0.0.0 \
        -bootstrap-expect=3 \
        -client=0.0.0.0 \
        -config-dir=/consul/config \
        -datacenter=dc1 \
        -data-dir=/consul/data \
        -domain=consul \
        -hcl="connect { enabled = true }" \
        -ui \
        -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
        -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
        -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
        -server
    Readiness:  exec [/bin/sh -ec curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
grep -E '".+"'
] delay=5s timeout=5s period=3s #success=1 #failure=2
    Environment:
      POD_IP:      (v1:status.podIP)
      NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /consul/config from config (rw)
      /consul/data from data-default (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from quarreling-hummingbird-consul-server-token-pqvp4 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  data-default:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-default-quarreling-hummingbird-consul-server-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      quarreling-hummingbird-consul-server-config
    Optional:  false
  quarreling-hummingbird-consul-server-token-pqvp4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  quarreling-hummingbird-consul-server-token-pqvp4
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  12s (x4 over 82s)  default-scheduler  0/7 nodes are available: 7 node(s) didn't find available persistent volumes to bind.``

Plz help to deploy it normally!

**Comment by ishustava** [comment]
Hey @itsecforu,

I noticed that you're using the local `storageClass`. With the local storage class you have to provision volumes manually. See [these docs](https://www.consul.io/docs/platform/k8s/helm.html#v-server-storageclass) for reference.

Hope this helps!

**Comment by itsecforu** [comment]
Hello, @ishustava !
Thx u for feedback
Is it default settings for Consul?

**Comment by ishustava** [comment]
By default, the Helm chart sets `storageClass` to `null`, which means that it will use Kubernetes cluster's default storage class.

**Comment by ishustava** [comment]
Hey @itsecforu, we haven't heard from you in a while. I hope you were able to resolve this. 

I'm closing this, but please feel free to comment here to re-open if you're still seeing issues.
