### ISSUE TITLE
TLS-related paths passed via ENV variables have no effect

### ISSUE THREAD

**Issue by grozan** [hashicorp/consul-helm#306]
Hi,

I'm trying to enable TLS encryption everywhere, starting with the agents in server mode.
Using the 0.13.0 version of the chart.
In my values file, `server` section, I set (only the relevant part below)

```
extraEnvironmentVars:
    CONSUL_CACERT: "/consul/userconfig/consul-certs/consul-agent-ca.pem"
    CONSUL_CLIENT_CERT: "/consul/userconfig/consul-certs/home-consul-server-0.pem"
    CONSUL_CLIENT_KEY: "/consul/userconfig/consul-certs/home-consul-server-0-key.pem"

  extraConfig: |
    {
      "log_level": "DEBUG",
      "verify_incoming": true,
      "verify_outgoing": true,
      "ports": {
        "https": 8501
      }
    }

  extraVolumes:
    - type: "secret"
      name: "consul-certs"
      load: false
```

To my surprise, this does NOT work. It crashes with

```
bootstrap_expect > 0: expecting 3 servers
==> Starting Consul agent...
           Version: 'v1.6.2'
           Node ID: '915e9c34-52d4-e391-d6ac-0de11579e18e'
         Node name: 'home-consul-server-0'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: 8501, gRPC: -1, DNS: 8600)
      Cluster Addr: 10.2.229.54 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: true, TLS-Incoming: true, Auto-Encrypt-TLS: false

==> Log data will now stream in as it occurs:

    2019/12/09 19:50:22 [DEBUG] tlsutil: Update with version 0
==> Error starting agent: VerifyOutgoing set, and no CA certificate provided!
    2019/12/09 19:50:22 [INFO] agent: Exit code: 1
```

It surprises me because I thought the 3 env variables I set would be equivalent to the `ca_file`, `cert_file` and `key_file` directives, respectively, in the hcl config file. So in my mind I passed the CA certificate to use...

To make it work I need to specify them in the hcl config file. The following does work

```
  extraEnvironmentVars: {}
  
  extraConfig: |
    {
      "log_level": "DEBUG",
      "verify_incoming": true,
      "verify_outgoing": true,
      "ca_file": "/consul/userconfig/consul-certs/consul-agent-ca.pem",
      "cert_file": "/consul/userconfig/consul-certs/home-consul-server-0.pem",
      "key_file": "/consul/userconfig/consul-certs/home-consul-server-0-key.pem",
      "ports": {
        "https": 8501
      }
    }

  extraVolumes:
    - type: "secret"
      name: "consul-certs"
      load: false
```

How come that the env variables have no effect?
Thanks

**Comment by lkysow** [comment]
Hi @grozan,
I think this is because those environment variables are only used by the CLI when you're running Consul commands to query a client or server. So for example if your server was already configured and you were to port-forward and run `consul members` locally, you could set the `CONSUL_CACERT` environment variable.

Looking through the code, I can't see them being used when starting the servers. This is very similar to this issue reported here: https://github.com/hashicorp/consul/issues/6228 about how it's not clear how to use environment variables in config. I think the real answer is that you can't!

Sorry for the confusion. I'll try to update those docs.

**Comment by grozan** [comment]
Thanks for the feedback!
Yes, hopefully the doc can be more explicit about where those env variables are used/useful for

The problem I'm having then is that in my case I want to use "dynamic" values for those cert-related parameters. Sharing the same certificates on all pods seems wrong to me. What I really want is `cert_file` to be `/consul/userconfig/consul-certs/$(POD_NAME).pem`, which is not possible to do right now using the chart.

I'm going to have to use `kustomize` to modify the output of `helm template` to do that. Totally doable, but IMO two little modifications to the chart would make its output directly usable, and would make the chart more flexible overall.

Those are:
- give the possibility to inject ENV variables from the downward API. Today only "basic" ENV variables can be injected
- give the possibility to give a list of additional consul command line parameters, which would get appended to the `consul` command's container (the one defined by the statefulset)

what do you think?
or is it worth opening separate issues for those?

Thanks

**Comment by lkysow** [comment]
We're actually working on full TLS support right now so maybe it would be best to wait for that?

**Comment by grozan** [comment]
ah, good to know!
not asking for a release date, of course, but we are talking like one week, one month, more?

**Comment by lkysow** [comment]
I'd say 1 month maximum. Also just chatted with @ishustava who's working on it and she's planning on using an init container to generate the individual client certs (partly I imagine to avoid the issue you're running into!).

**Comment by lkysow** [comment]
Also FYI, I've updated those Consul docs about env vars so they're not misleading anymore! (https://github.com/hashicorp/consul/pull/6912)

**Comment by grozan** [comment]
Thanks a lot for the support!
