### ISSUE TITLE
Changing `envoy_tracing_json` does not take effect until the PV is deleted and consul redeployed

### ISSUE THREAD

**Issue by kevinjqiu** [hashicorp/consul-helm#309]
Here's the portion of my consul-helm chart config:

```
        connectInject:
          enabled: true
          imageEnvoy: envoyproxy/envoy-alpine:v1.12.1
          centralConfig:
            enabled: true
            defaultProtocol: http
            proxyDefaults: |
              {
                "envoy_extra_static_clusters_json": {{ readFile "envoy_extra_static_clusters.json" | quote }},
                "envoy_tracing_json": {{ readFile "envoy_tracing.json" | quote }}
              }
```

I'm using helmfile, so I can store the envoy configs as plain json file, and use `readFile` template func to read them in and escape raw config using `|quote`.

The issue here is that when I update `envoy_tracing_json` or `envoy_extra_static_cluster_json`, it updates these in the configmap, but they don't take effect until the PV that has the consul data is deleted.  This isn't going to work well with any existing consul deployment.

**Comment by lkysow** [comment]
Hi Kevin,
If you run `consul reload` on a server does it not pick up the new configs?

If you plan on updating these frequently and that doesn't work for now I'd recommend not managing these through the helm chart and instead creating your own proxy defaults config file that you manage updates to yourself, e.g. by port-forwarding to the Consul server and running `consul config write`, maybe through Jenkins or Terraform or your own Kubernetes deployment.

In the future, we're looking at allowing you to manage this through CRDs but that's not available right now.

**Comment by kevinjqiu** [comment]
> If you run consul reload on a server does it not pick up the new configs?

No I didn't.  That's probably the missing piece.

Should there be a reloader sidecar to detect config changes and trigger consul reload, similar to how prometheus does?  Or maybe document this behaviour in the official docs.

> If you plan on updating these frequently and that doesn't work for now I'd recommend not managing these through the helm chart and instead creating your own proxy defaults config file that you manage updates to yourself, e.g. by port-forwarding to the Consul server and running consul config write, maybe through Jenkins or Terraform or your own Kubernetes deployment.

I don't think I'll change them frequently once it's deployed but during the experiment stage, they do get changed quite often.  I'll do `consul reload` manually for now.

Thanks for responding.

**Comment by lkysow** [comment]
> Should there be a reloader sidecar to detect config changes and trigger consul reload, similar to how prometheus does?

I think that's a good idea. This ticket is asking for the same thing: https://github.com/hashicorp/consul-helm/issues/106

> Or maybe document this behaviour in the official docs.

Yes, I'll create a PR to update the values docs for now.

**Comment by kevinjqiu** [comment]
Thanks @lkysow

**Comment by lkysow** [comment]
Hey FYI `consul reload` won't work. I just found https://github.com/hashicorp/consul/issues/6703 which is the same issue in Consul. I'll update the docs to say that after the cluster is brought up, any changes to the configs must be done via the API.

**Comment by lkysow** [comment]
I've added some docs about this to https://github.com/hashicorp/consul-helm/pull/302
