### ISSUE TITLE
Document what actions need to be taken for each config value to take effect

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#312]
Many of the keys in our `values.yaml` don't take effect after `helm upgrade` without further steps. For example, changes to the config maps don't run `consul reload` automatically and even then, some config options aren't reloadable (https://www.consul.io/docs/agent/options.html#reloadable-configuration).

This makes it difficult for users to make changes to their consul installation and could potentially be very frustrating to figure out why config that is set isn't working.

We should document each key in a consistent way and describe what changing that key after initial installation would do and what additional steps may be necessary.

**Comment by ashwin-venkatesh** [comment]
Closed by #582
