### ISSUE TITLE
consul connect sidecar can not work

### ISSUE THREAD

**Issue by thetruechar** [hashicorp/consul-helm#318]
After deploying the example from https://www.consul.io/docs/platform/k8s/connect.html#accepting-inbound-connections, init container failed with the following logs:

Error registering service "static-server-sidecar-proxy": Put http://172.16.30.51:8500/v1/agent/service/register: dial tcp 172.16.30.51:8500: connect: connection refused

**Comment by thetruechar** [comment]
also when i enable catalog in helm, the consul-sync-catalog pod failed with the following logs:
[GET /health/ready] Error getting leader status: Get http://172.18.2.135:8500/v1/status/leader: dial tcp 172.18.2.135:8500: connect: connection refused

Seem the pod can not connect to the node

**Comment by lkysow** [comment]
Hi, it sounds like your Consul clients aren't running. The Consul clients listen on host port 8500. Can you show the output of `kubectl get pod`?

**Comment by thetruechar** [comment]
❯ k get pods
NAME                                          READY   STATUS                  RESTARTS   AGE
consul-consul-qcrc8                           1/1     Running                 0          94s
consul-consul-server-0                        1/1     Running                 0          94s
consul-consul-server-1                        1/1     Running                 0          94s
consul-consul-sync-catalog-64f497f97d-j5hml   0/1     Running                 2          94s
consul-consul-wvpn9                           1/1     Running                 0          94s
static-server                                 0/3     Init:CrashLoopBackOff   129        10h


I helm installed again, only modified the syncCatalog.enable to true in values.yaml

**Comment by thetruechar** [comment]
k get DaemonSet
NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
consul-consul   2         2         2       2            2           <none>          6m18s

**Comment by thetruechar** [comment]
update: 
My environment is Alibaba cloud ack, their engineer said that the ack does not support hostport, only support service nodeport, so how can I workaround this?

**Comment by thetruechar** [comment]
@lkysow hi, i used anubhavmishra/tiny-tools you mentioned in[ issue-319](https://github.com/hashicorp/consul-helm/issues/319 ) to deploy in alibaba ack, it successfully deployed, and no log output, so it's weird why pod encounter connection refused when connect to consul agent

**Comment by thetruechar** [comment]
@lkysow 
Have  a question, i don't find hostport definition in [client-daemonset.yaml ](https://github.com/hashicorp/consul-helm/blob/master/templates/client-daemonset.yaml), why the result will produce hostPort?

**Comment by thetruechar** [comment]
@lkysow 
I found a way to workaround hostport limitations in Alibaba ack,
I commented out all hostport in client-daemonset.yaml, and add the following in template.spec
```yaml
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
```
I run static-server/static-client, it works.
Can you verify this modification? Maybe we can put this option in helm?

**Comment by lkysow** [comment]
Yeah we need to find the time to try it out on ACK and then we can update
accordingly.

**Comment by lkysow** [comment]
hostNetwork support was merged in https://github.com/hashicorp/consul-helm/pull/496!
