### ISSUE TITLE
consul-helm not functioning on Kind

### ISSUE THREAD

**Issue by eelcoh** [hashicorp/consul-helm#322]
I can't get the consul-helm to result in a working consul install on [kind](https://kind.sigs.k8s.io/) 

Using 
* kind v0.6.1 go1.13.4 darwin/amd64
* Helm v3.0.1

```
brew install helm
brew install kind
kind create cluster --name consul
helm install ./consul-helm
```

```
→ kb get pods
NAME                        READY   STATUS    RESTARTS   AGE
hashicorp-consul-p4kg7      0/1     Running   0          3m7s
hashicorp-consul-server-0   0/1     Running   0          3m7s
hashicorp-consul-server-1   0/1     Pending   0          3m7s
hashicorp-consul-server-2   0/1     Pending   0          3m7s
```

```
→ kb logs hashicorp-consul-p4kg7
    2020/01/02 21:48:15 [ERR] consul: "Coordinate.Update" RPC failed to server 10.244.0.9:8300: rpc error making call: No cluster leader
    2020/01/02 21:48:15 [ERR] agent: Coordinate update error: rpc error making call: No cluster leader
```

```
→ kb get svc
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                   AGE
hashicorp-consul-dns      ClusterIP   10.100.195.100   <none>        53/TCP,53/UDP                                                             3m41s
hashicorp-consul-server   ClusterIP   None             <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   3m41s
hashicorp-consul-ui       ClusterIP   10.106.163.207   <none>        80/TCP                                                                    3m41s
kubernetes                ClusterIP   10.96.0.1        <none>        443/TCP                                                                   36m
```

**Comment by lkysow** [comment]
Can you share the logs from each of the consul server pods?

**Comment by eelcoh** [comment]
created a clean install:


```
→ helm inspect chart ./consul-helm
apiVersion: v1
description: Install and configure Consul on Kubernetes.
home: https://www.consul.io
name: consul
sources:
- https://github.com/hashicorp/consul
- https://github.com/hashicorp/consul-helm
- https://github.com/hashicorp/consul-k8s
version: 0.15.0


→ kind create cluster --name consul
Creating cluster "consul" ...
 ✓ Ensuring node image (kindest/node:v1.16.3) 🖼
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
Set kubectl context to "kind-consul"
You can now use your cluster with:

kubectl cluster-info --context kind-consul

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂


→ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
hashicorp-consul-j2mpd      0/1     Running   0          3m15s
hashicorp-consul-server-0   0/1     Running   0          3m14s
hashicorp-consul-server-1   0/1     Pending   0          3m14s
hashicorp-consul-server-2   0/1     Pending   0          3m14s


→ kubectl get svc
NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                   AGE
hashicorp-consul-dns      ClusterIP   10.110.105.144   <none>        53/TCP,53/UDP                                                             3m32s
hashicorp-consul-server   ClusterIP   None             <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   3m32s
hashicorp-consul-ui       ClusterIP   10.101.124.36    <none>        80/TCP                                                                    3m32s
kubernetes                ClusterIP   10.96.0.1        <none>        443/TCP                                                                   5m57s
```

The `kubectl logs hashicorp-consul-server-*` are all empty. The other output is attached.


`→ helm get all hashicorp`
[helm-get-all-hashicorp.txt](https://github.com/hashicorp/consul-helm/files/4020742/helm-get-all-hashicorp.txt)

`→ helm status hashicorp`
[helm-status-hashicorp.txt](https://github.com/hashicorp/consul-helm/files/4020743/helm-status-hashicorp.txt)

`→ kubectl logs hashicorp-consul-j2mpd`
[kubectl-logs-hashicorp-consul-j2mpd.txt](https://github.com/hashicorp/consul-helm/files/4020744/kubectl-logs-hashicorp-consul-j2mpd.txt)

**Comment by codyde** [comment]
I can say for sure that I have the Consul Helm chart working with kind in my environment, using the same kind node image as you. Just out of curiosity, if you have kind deploy additional worker nodes - do you have a different experience? I typically end up using [this](https://gist.github.com/codyde/b83966dd87d338eb80ad0d6f923b868d) config for clusters (1 master/3 workers)

I've linked my values.yaml file [here](https://gist.github.com/codyde/0c013e79dc7f5bba865dec1049ab504b) that I use for deploying Consul in kind. Also, the chart works with Helm3 if you want to use that, FWIW. 

My "flow" for creating a Consul cluster in KIND is something like... 

- Create cluster with the above cluster manifest
- Apply Metallb as a simple load balancer 
- Deploy Consul helm chart with the values.yaml I included in this post 
- Wait for services to come up

**Comment by lkysow** [comment]
Thanks for those logs and your excellent formatting!! So the problem right now is that consul-server's 1 and 2 are stuck in Pending. Consul won't start until it has quorum which means it needs all 3 servers. To figure out what's going on there I'll need you to show the output of `kubectl describe` for those pods.

If you don't need 3 servers (unlikely on Kind) you can also set:
```yaml
server:
  replicas: 1
  bootstrapExpect: 1
```
To only bring up one server.

I suspect that you're getting an error because the consul servers have a default anti-affinity so they can't be scheduled on the same node.

**Comment by eelcoh** [comment]
> I can say for sure that I have the Consul Helm chart working with kind in my environment, using the same kind node image as you. Just out of curiosity, if you have kind deploy additional worker nodes - do you have a different experience? I typically end up using [this](https://gist.github.com/codyde/b83966dd87d338eb80ad0d6f923b868d) config for clusters (1 master/3 workers)
> 
> I've linked my values.yaml file [here](https://gist.github.com/codyde/0c013e79dc7f5bba865dec1049ab504b) that I use for deploying Consul in kind. I've been running it exclusively with Helm 3 (editited this because originally I didn't see you were using Helm 3).
> 
> My "flow" for creating a Consul cluster in KIND is something like...
> 
> * Create cluster with the above cluster manifest
> * Apply Metallb as a simple load balancer
> * Deploy Consul helm chart with the values.yaml I included in this post
> * Wait for services to come up

Tried this setup. With much more succes. I will have to look into that crash loop back off later. 

```
→ kubectl get pods
NAME                                                              READY   STATUS             RESTARTS   AGE
hashicorp-consul-87nqd                                            1/1     Running            0          40s
hashicorp-consul-8vzfl                                            1/1     Running            0          40s
hashicorp-consul-connect-injector-webhook-deployment-fcc65lgchz   0/1     CrashLoopBackOff   2          40s
hashicorp-consul-lwsln                                            1/1     Running            0          40s
hashicorp-consul-server-0                                         1/1     Running            0          29s
hashicorp-consul-server-1                                         1/1     Running            0          28s
hashicorp-consul-server-2                                         1/1     Running            0          27s
hashicorp-consul-sync-catalog-5d976d45c6-nc4qm                    1/1     Running            0          40s
```

**Comment by eelcoh** [comment]
> Thanks for those logs and your excellent formatting!! So the problem right now is that consul-server's 1 and 2 are stuck in Pending. Consul won't start until it has quorum which means it needs all 3 servers. To figure out what's going on there I'll need you to show the output of `kubectl describe` for those pods.
> 
> If you don't need 3 servers (unlikely on Kind) you can also set:
> 
> ```yaml
> server:
>   replicas: 1
>   bootstrapExpect: 1
> ```
> 
> To only bring up one server.
> 
> I suspect that you're getting an error because the consul servers have a default anti-affinity so they can't be scheduled on the same node.

Yes. That works. 

I had tried the `replicas: 1`, but was not aware of the `bootstrapExpect: 1`. That did the trick. Thanks!

**Comment by eelcoh** [comment]
> I can say for sure that I have the Consul Helm chart working with kind in my environment, using the same kind node image as you. Just out of curiosity, if you have kind deploy additional worker nodes - do you have a different experience? I typically end up using [this](https://gist.github.com/codyde/b83966dd87d338eb80ad0d6f923b868d) config for clusters (1 master/3 workers)
> 
> I've linked my values.yaml file [here](https://gist.github.com/codyde/0c013e79dc7f5bba865dec1049ab504b) that I use for deploying Consul in kind. I've been running it exclusively with Helm 3 (editited this because originally I didn't see you were using Helm 3).
> 
> My "flow" for creating a Consul cluster in KIND is something like...
> 
> * Create cluster with the above cluster manifest
> * Apply Metallb as a simple load balancer
> * Deploy Consul helm chart with the values.yaml I included in this post
> * Wait for services to come up

One more thing on this one, as i had a crash loop back off on the `consul-connect-injector-webhook-deployment`.
```
→ kb logs hashicorp-consul-connect-injector-webhook-deployment-fcc657nvcz
flag provided but not defined: -consul-k8s-image
```

Turned out i had to remove this line from `consul-helm/templates/connect-inject-deployment.yaml` to resolve that:
`-consul-k8s-image="{{ default .Values.global.imageK8S .Values.connectInject.image }}" \
`

**Comment by eelcoh** [comment]
I think running on Kind is a great way to explore the possibilities of Consul, so you may want to support it, perhaps through [documentation](https://www.consul.io/docs/platform/k8s/index.html). 

As far as i am concerned, this issue can be closed.

**Comment by lkysow** [comment]
> Turned out i had to remove this line from consul-helm/templates/connect-inject-deployment.yaml to resolve that:

I think because the values.yaml isn't using the latest consul-k8s version.

I got it working with either:
```yaml
server:
  replicas: 1
  bootstrapExpect: 1
```

or
```yaml
server:
  affinity: ""
```

I've created https://github.com/hashicorp/consul-helm/issues/324 to track documenting this. Good idea.
