### ISSUE TITLE
Chart version is out of sync with the last couple of releases

### ISSUE THREAD

**Issue by stk0vrfl0w** [hashicorp/consul-helm#333]
Similar to #95 and #50, https://github.com/hashicorp/consul-helm/blob/85093b663326b54b06eb2b3e9571cac153949b63/Chart.yaml#L3 references 0.15.0 instead of 0.16.1.

**Comment by lkysow** [comment]
Good catch! We're going to do a new release and update the version this time.

**Comment by lkysow** [comment]
Fixed by https://github.com/hashicorp/consul-helm/pull/334
