### ISSUE TITLE
Support for Telemetry/DogStatsD

### ISSUE THREAD

**Issue by scrossan** [hashicorp/consul-helm#339]
Hi,

Similar to https://github.com/hashicorp/consul-helm/issues/262 it would be great if the chart could support configuring telemetry options. We're using Datadog for monitoring/alerting and it seems that only a subset of metrics are ingested by the datadog-agent via Consul's API (down to `consul.peers` [in this list](https://docs.datadoghq.com/integrations/consul/#metrics)), which I configured by adding autodiscovery annotations to our server and client pods. According to the Consul overview on Datadog's Integration page:

> The Consul Agent can provide further metrics via DogStatsD.

The problem is, the chart doesn't easily allow me to configure DogStatsD. The two ways of configuring DogStatsD seem to be either [mounting a Unix Domain Socket](https://docs.datadoghq.com/agent/kubernetes/dogstatsd/#use-dogstatsd-over-a-unix-domain-socket) or [using a hostPort](https://docs.datadoghq.com/agent/kubernetes/dogstatsd/#alternatively-use-hostport). Respectively:

1. It's not possible to mount a volume using `hostPath` because the chart only support extra volumes that are either secrets or configmaps. Also, I don't think [Consul itself supports a file path](https://www.consul.io/docs/agent/options.html#telemetry-dogstatsd_addr) being passed as the value of `telemetry.dogstatsd_addr`
2. The only way it's possible currently to pass a `host:port` value to `telemetry.dogstatsd_addr` is by adding it to `extraConfig`, but that prevents us using `HOST_IP` since that isn't exposed in the container environment and since Consul can't be configured using environment variables in its config files.

The way we've approached this now is by exposing port 8125 on our datadog-agent pods as a service so we can hard-code the value of `telemetry.dogstatsd_addr` as `dogstatsd.namespace:8125` in `extraConfig`, but I think the ideal way of shipping metrics to DogStatsD is by sending them to the datadog-agent running on the same host as the sending pod ([Datadog say to configure DogStatsD in this way in their documentation](https://docs.datadoghq.com/agent/kubernetes/dogstatsd/#pass-the-node-s-ip-address-to-your-application)). One thing we've noticed is that we can't tie our metrics reliably to the k8s worker they originate from since a Consul pod is sending the metrics to a service, which resolves to one of a number of datadog-agent pods and not always the one running on the same k8s worker, and the `host` tag on the metrics seems to reflect the host the datadog-agent is deployed to, but for us there's still value is being able to see the cluster-wide status by looking at the  metrics in aggregate.

I thought the way that you would implement telemetry support would be by adding options to `values.yaml` such that you can toggle the command line flags for telemetry options, but it looks like the telemetry options can only be passed in configuration files ([see the Consul configuration docs](https://www.consul.io/docs/agent/options.html#configuration-files)). If that's the case, then I'm not sure how you would pass the right host IP to the pod, depending on the worker node it is deployed to?

Maybe it's possible to do something similar to vault-helm and render the config with the host IP? See: https://github.com/hashicorp/vault-helm/blob/master/templates/_helpers.tpl#L112-L124

**Comment by woz5999** [comment]
I'm running into this same issue. I took a brief look at the code and I *think* `dogstatsd_addr` will accept a unix socket because that value is ultimately getting passed directly to the datadog statsd sink. Which is fortunate, because I think the unix socket is the correct approach as it will work for both consul and envoy proxies for those of us using consul connect. the sed approach from the vault chart would probably be the simplest and easiest solution for the pure consul use case, but isn't sufficient for properly setting `envoy_dogstatsd_url` in `proxyDefaults`.

I'm going to see about working up a PR to support mounting the unix socket.

**Comment by woz5999** [comment]
My hunch was wrong and consul will crash if you attempt to set a unix socket for the `dogstatsd_addr`

I ended up exposing the dogstatsd port as a cluster service. Hopefully the client in recent consul versions i new enough to allow to allow dogstatsd UDP origin discovery to work well.

**Comment by david-yu** [comment]
Hi @scrossan I'm going to close this in favor of https://github.com/hashicorp/consul-helm/issues/657, which would be the correct way of exposing the DogStatsD agent according to https://docs.datadoghq.com/developers/dogstatsd/?tab=kubernetes#client-instantiation-parameters
