### ISSUE TITLE
Support for snapshot cronjob

### ISSUE THREAD

**Issue by tomwganem** [hashicorp/consul-helm#344]
It would be great if this chart could also install a cronjob that ran `consul snapshot` and uploaded it to s3 storage.

**Comment by lkysow** [comment]
Hi Tom,
FYI, we do support the consul snapshot agent (https://www.consul.io/docs/commands/snapshot/agent.html) but this is only available for consul enterprise.

**Comment by tomwganem** [comment]
Yes, I did notice that. It's a great solution for those with an enterprise license. Alas, I am a unlicensed plebeian.

**Comment by adilyse** [comment]
Hey @tomwganem, I wanted to link to some prior discussion about another HashiCorp project from @mitchellh to try and set some context here.

https://github.com/hashicorp/vault/issues/132#issuecomment-320880698

We try to be very careful in selecting features for the proprietary version of our product that best align with what we believe larger scale organizations need, in an effort to ensure we can build a sustainable business and support the open source functionality in the long term. This is a tough balance, and the needs of all sizes of organizations differ, but we do our best to work through the details for each feature and make our decision carefully. At the moment, we believe that the snapshot agent as a feature is in this category. We recognize the criticality of standing behind liberally licensed OSS philosophically but make trade-offs to ensure the success of the project.

Thank you for opening this issue and bringing this up. We are definitely open to questions and are happy to explain our reasoning for the decision.
