### ISSUE TITLE
Document meshGateway values in Helm Chart Reference

### ISSUE THREAD

**Issue by blake** [hashicorp/consul-helm#351]
Mesh Gateway support was added to the Helm chart in #203. However, the config values are not documented on the [Helm Chart Reference](https://www.consul.io/docs/platform/k8s/helm.html).

It would be great if these config values were documented so that the availability of this feature is more apparent to those browsing the documentation.

**Comment by blake** [comment]
Closed via hashicorp/consul#7492.

**Comment by tasansga** [comment]
That's similar to https://github.com/hashicorp/consul-helm/issues/667
I'd like better documentation on this one too, when can we expect an update?

**Comment by lkysow** [comment]
Mesh gateway docs are up to date now: https://www.consul.io/docs/k8s/helm#v-meshgateway so I'm going to close this.

@tasansga we'll use #667 to track documenting that issue.
