### ISSUE TITLE
more strict RBAC rules wherever possible

### ISSUE THREAD

**Issue by grozan** [hashicorp/consul-helm#354]
Hi,

I'm looking at the resources generated by the chart when TLS is enabled.
I *think* it's possible to be a bit more strict, with regards to RBAC rules.
For example, for the _tls-init_ and _tls-init-cleanup_ stuff, couldn't _Role_ and _RoleBinding_ be used instead of _ClusterRole_ and _ClusterRoleBinding_? Everything happens in one namespace, right, so the _tls-init_ service account does not need to be able to create secrets in ALL namespaces.

No?

**Comment by lkysow** [comment]
Hey I think you're very much correct! It looks like we don't need to be at the cluster level for a lot of these permissions.

**Comment by kschoche** [comment]
Hi there! We've merged several PR's over the past 24h into master which progressively back out unnecessary ClusterRole usage, including tls-init (#498). Thank you for raising this issue!

With the specific change that this issue references (#498) you will still have a tls-init clusterrole+binding that hangs around after a `helm upgrade` which should be safe to manually remove once you've upgraded.  It shouldn't be harmful to leave in place but it is indeed unnecessary.

I'll put a comment in the ChangeLog reflecting this but wanted to let you know in advance!
