### ISSUE TITLE
Support external-to-k8s Consul clients

### ISSUE THREAD

**Issue by larssb** [hashicorp/consul-helm#358]
**THE ISSUE**

Connecting `Consul` clients external to a K8S cluster, when `Pod` IP's are not route-able. 

**SETUP**

* K8S v1.14.6
* Docker v18.3.1
* Using the Official Consul Helm chart found [here](https://hub.helm.sh/charts/stable/consul). v0.16.2
* Consul agent running on a Windows node outside the cluster
  * Agent commandline: `.\consul.exe agent -retry-join 'provider=k8s kubeconfig="./consul-conf/kubeconfig" label_selector=""app=consul,component=server""' -enable-local-script-checks -data-dir="./consul-data" -config-dir="./consul-conf" -log-level=DEBUG`

**ERROR/ISSUE**

```
2020-02-21T10:01:30.622+0100 [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
   2020-02-21T10:01:34.896+0100 [DEBUG] agent: Check status updated: check=service:scanandpay:1 status=passing
   2020-02-21T10:01:36.541+0100 [DEBUG] agent.client.manager: No healthy servers during rebalance, aborting
   2020-02-21T10:01:36.940+0100 [DEBUG] agent: discover: Using provider "k8s": cluster=LAN
   2020-02-21T10:01:37.090+0100 [INFO]  agent: Discovered servers: cluster=LAN cluster=LAN servers="10.42.22.77 10.42.21.65 10.42.20.82"
   2020-02-21T10:01:37.091+0100 [INFO]  agent: (LAN) joining: lan_addresses=[10.42.22.77, 10.42.21.65, 10.42.20.82]
   2020-02-21T10:01:43.328+0100 [WARN]  agent: Check is now critical: check=service:scanandpay:2
   2020-02-21T10:01:45.197+0100 [DEBUG] agent: Check status updated: check=service:scanandpay:1 status=passing
   2020-02-21T10:01:47.093+0100 [DEBUG] agent.client.memberlist.lan: memberlist: Failed to join 10.42.22.77: dial tcp 10.42.22.77:8301: i/o timeout
   2020-02-21T10:01:47.266+0100 [WARN]  agent.client.manager: No servers available
   2020-02-21T10:01:47.267+0100 [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
   2020-02-21T10:01:48.444+0100 [DEBUG] agent: Skipping coordinate updates until servers are upgraded
   2020-02-21T10:01:55.091+0100 [DEBUG] agent: Check status updated: check=service:scanandpay:3 status=passing
   2020-02-21T10:01:55.493+0100 [DEBUG] agent: Check status updated: check=service:scanandpay:1 status=passing
   2020-02-21T10:01:57.094+0100 [DEBUG] agent.client.memberlist.lan: memberlist: Failed to join 10.42.21.65: dial tcp 10.42.21.65:8301: i/o timeout
   2020-02-21T10:02:05.040+0100 [DEBUG] agent: Skipping coordinate updates until servers are upgraded
   2020-02-21T10:02:05.781+0100 [DEBUG] agent: Check status updated: check=service:scanandpay:1 status=passing
   2020-02-21T10:02:06.618+0100 [WARN]  agent.client.manager: No servers available
   2020-02-21T10:02:06.621+0100 [ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
   2020-02-21T10:02:07.096+0100 [DEBUG] agent.client.memberlist.lan: memberlist: Failed to join 10.42.20.82: dial tcp 10.42.20.82:8301: i/o timeout
   2020-02-21T10:02:21.017+0100 [WARN]  agent: (LAN) couldn't join: number_of_nodes=0 error="3 errors occurred:
       * Failed to join 10.42.22.77: dial tcp 10.42.22.77:8301: i/o timeout
       * Failed to join 10.42.21.65: dial tcp 10.42.21.65:8301: i/o timeout
       * Failed to join 10.42.20.82: dial tcp 10.42.20.82:8301: i/o timeout
```

**DEBUGGING**

- Searched the issues of this Helm chart
- Searched the issues of the Consul GitHub repo

I found these two interesting issues:

* [Support external-to-k8s Consul servers ](https://github.com/hashicorp/consul-helm/pull/289)
  * Especially [this comment](https://github.com/hashicorp/consul-helm/pull/289#issuecomment-562350630) is of interest
* [ Consul client is not exposing the 8500 port as mentioned in guide](https://github.com/hashicorp/consul-helm/issues/23)

- Read through the docs and found the following to be interesting
  - [Cloud Auto-join](https://www.consul.io/docs/agent/cloud-auto-join.html#kubernetes-k8s-)
  - [Create a Local Consul Datacenter](https://learn.hashicorp.com/consul/getting-started/join#notes-on-auto-join)
  - [Configuration](https://www.consul.io/docs/agent/options.html#cloud-auto-joining)
  - [Consul Clients Outside of Kubernetes](https://www.consul.io/docs/platform/k8s/clients-outside-kubernetes.html)

**TAKEAWAYS**

As far as I can comprehend the Consul Helm chart supports Consul servers outside of a K8S cluster. However, not Consul servers inside a K8S cluster. In regards to Consul clients joining the cluster.
Although the docs mention that if one configures the deployment to use either `hostNetwork` or `hostPort` then it should work. But, how exactly one does that is nowhere to be found. 

**GETTING TO THE ENDZONE**

I would greatly appreciate some guidance on how-to make it possible to join Consul clients running outside a K8S cluster to join Consul server running inside the cluster.

Thank you very much.

**Comment by larssb** [comment]
Update. So I got it my Consul agent to join the Consul servers inside the K8S cluster. By manually adding the `hostNetwork: true` to the `template:spec` part of the `server-statefulset.yaml` file. What are your thoughts on this. In regards to this solution becoming a part of a future Helm release of this chart.

Thank you

**Comment by lkysow** [comment]
Hi, we actually have an in-progress PR on that already that I think accomplishes the same thing? https://github.com/hashicorp/consul-helm/pull/332/files

**Comment by larssb** [comment]
Hi @lkysow,

I'm not sure that the PR you are referring to solves this challenge. Isn't the K8S auto cloid-join provider fetching the POD IP's from the K8S API, relative to the `kubeconfig` with wich the Consul agent, to be joining the cluster, is started with?

Furthermore. The `hostNetwork` setting is not available to be configured via the `values.yaml` file ... for the server statefulset. And, after playing with terminating the leader, I found out that I had to configure the statefulset with a `dnsPolicy` of `ClusterFirstWithHostNet`. That setting is not available via the chart either.

If these two settings get into this chart. I think a note on these are important. As using `hostNetwork` will result in the Consul agents and Consul server workloads will potentially have port conflicts. Options are:

* Do not deploy agents on K8S. Only servers
* Set the UI to be exposed. So that runs on the servers only via a K8S service

Let me know what you guys think.

Thank you very much.

**Comment by lkysow** [comment]
> I'm not sure that the PR you are referring to solves this challenge. Isn't the K8S auto cloid-join provider fetching the POD IP's from the K8S API, relative to the kubeconfig with wich the Consul agent, to be joining the cluster, is started with?

Ahh sorry I missed this piece. This week is our company off-site

**Comment by larssb** [comment]
Looking forward to that. Thank you.

**Comment by larssb** [comment]
@lkysow next week have arrived. Looking forward to a chirp from your team.

Have a great day 👍

**Comment by fusionx86** [comment]
@lkysow This has been a blocker for me as well. I’m trying to connect consul clients running in VMs to a consul cluster running in k8s. Our enterprise apps run on VMs in private clouds, but we’re shifting to k8s in the same clouds and would like to run the consul servers in k8s with external consul clients running in VMs.

I could work around it using `nodePort` for the consul server and new routes on the VMs for the pod IPs, but that isn’t a good solution long term. The idea larssb had with `hostNetwork` and `dnsPolicy` is also interesting, but it causes problems with consul clients running in k8s…which he mentioned. I really need a good long-term solution for this.

Thanks for bringing this problem up @larssb!

**Comment by lkysow** [comment]
We could use https://github.com/hashicorp/consul-helm/pull/332/files and have you folks set `host_network=true` in the go-discover string, e.g.
```
consul agent -retry-join 'provider=k8s label_selector="app=consul,component=server" host_network=true'
```

This causes go-discover to return the underlying host ips instead of the pod ips. This would sidestep the issue with colliding ports when using hostNetwork=true.

How does that sound? You'd still need to set `client.exposeWANPorts` to true if running clients on Kubernetes since all Consul clients need to be able to gossip with one another.

**Comment by larssb** [comment]
Hmm that is a good solution @lkysow ... when is that #332 being merged? And help me understand why the client `exposeWANPorts` setting is needed, is that because setting the K8S provider to configure `host_network=true` causes this? I'm trying to understand the behind the scenes stuff.
Because, wouldn't the clients be able to communicate with each other, or is Consul server in this case a type of client? Would be weird though.

Thank you very much.

**Comment by lkysow** [comment]
All clients need to be able to gossip with one-another on their advertise ips. This is how Consul agrees which nodes are healthy. 

You said that your pod ips were not routable by clients outside the cluster. This means that the clients outside the cluster would not be able to gossip with the clients inside the cluster unless their advertise ips were routable. It sounds like in your setup, the only way to accomplish this is to use the node ips. If `client.exposeGossipPorts` is set, then the clients will advertise their node ips.

**Comment by larssb** [comment]
Thank you very much @lkysow ...

Is there a timeline on #332 ? Looking forward to get this solution tried out.

**Comment by fusionx86** [comment]
Thanks for the help @lkysow. #332 doesn't work for me, but maybe I misunderstood the goal.

My setup is three consul servers and clients deployed to three k8s workers (192.168.1.13,14,15) using your `expose-servers` branch. External clients are on the same 192 network. Value overrides:

```
server:
  exposeWANPorts: true
client:
  exposeGossipPorts: true
```

A port scan of the k8s workers from the VMs shows ports 8300, 8301, 8302, 8500, 8502 are open. Consul config on an external VM client:

```
{
  "server": false,
  "bind_addr": "192.168.1.18",
  "client_addr": "127.0.0.1",
  "data_dir": "/opt/consul",
  "retry_join": ["provider=k8s label_selector=\"app=consul,component=server\" host_network=true"]
}
```

The external client joins the cluster, but continually throws errors trying to connect to the consul server pod addresses:

```
agent: Joining LAN cluster...
[INFO] agent: Discovered LAN servers: 192.168.1.15 192.168.1.14 192.168.1.13
[INFO] agent: (LAN) joining: [192.168.1.15 192.168.1.14 192.168.1.13]
[DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.15:8301
...
[INFO] serf: EventMemberJoin: consul-server-2 10.42.1.72
[INFO] serf: EventMemberJoin: consul-server-1 10.42.2.217
[INFO] serf: EventMemberJoin: k8sw01 192.168.1.13
[INFO] serf: EventMemberJoin: k8sw02 192.168.1.14
[INFO] serf: EventMemberJoin: consul-server-0 10.42.3.232
[INFO] serf: EventMemberJoin: k8sw03 192.168.1.15
...
[INFO] consul: adding server consul-server-2 (Addr: tcp/10.42.1.72:8300)
[INFO] consul: adding server consul-server-1 (Addr: tcp/10.42.2.217:8300)
[INFO] consul: adding server consul-server-0 (Addr: tcp/10.42.3.232:8300)
[DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.14:8301
[DEBUG] memberlist: Initiating push/pull sync with: 192.168.1.13:8301
...
[INFO] agent: (LAN) joined: 3
...
[DEBUG] memberlist: Failed ping: consul-server-1 (timeout reached)
[ERR] consul: "Catalog.NodeServices" RPC failed to server 10.42.1.72:8300: rpc error getting client: failed to get conn: dial tcp 192.168.1.18:0->10.42.1.72:8300: connect: no route to host
[DEBUG] manager: cycled away from server "consul-server-2"
[DEBUG] memberlist: Failed ping: consul-server-2 (timeout reached)
...
```

It seems that even with `exposeWANPorts: true`, the servers are advertising podIP rather than hostIP. The clients do advertise hostIP correctly though. Thoughts?

**Comment by larssb** [comment]
I can join outside Consul clients to Consul servers running in a K8S cluster. By configuring this `Helm chart` with the following values:

1. `client.enabled: false` in the values.yaml file
1. `spec.template.spec.hostNetwork: true` && `spec.template.spec.dnsPolicy: ClusterFirstWIthHostNet`

and then I use the K8S Consul provider on agent boot. E.g. `.\consul.exe agent -retry-join 'provider=k8s kubeconfig="./consul-conf/kubeconfig" label_selector=""app=consul,component=server""' -enable-local-script-checks -data-dir="./consul-data" -config-dir="./consul-conf" -log-level=DEBUG`

But I created this case, first of all to figure out how-to make this work and to get these configuration settings officially into the chart. So @lkysow where are we at status wise.

Thank you very much

**Comment by lkysow** [comment]
@fusionx86 
> It seems that even with exposeWANPorts: true, the servers are advertising podIP rather than hostIP. The clients do advertise hostIP correctly though. Thoughts?

Good catch. The servers are only advertising the podIP for their WAN address, not their LAN address. That PR needs updating.

@larssb did you try using the solution from https://github.com/hashicorp/consul-helm/issues/358#issuecomment-593469766 as well? In terms of status this on our backlog but unfortunately I don't have other updates.

**Comment by larssb** [comment]
So @lkysow,

I pulled the `expose-servers` branch and set `exposeWANports` to `true` in the values file. However, I then got the following error when the Consul server cluster starts up: 

```
2020-03-11T09:46:54.633Z [WARN]  agent.server.memberlist.lan: memberlist: Failed to resolve hashicorp-consul-server-0.hashicorp-consul-server.default.svc: lookup hashicorp-consul-server-0.hashicorp-consul-server.default.svc on 10.43.0.10:53: no such host
```

I then tried adding `dnsPolicy: ClusterFirstWithHostNet` to the `server-statefulset.yaml` file. The settings goes through on deployment but the above error prevails.

So for some reason the DNS records are not valid. I'm a little lost here. Again. As I describe in [358 comment](https://github.com/hashicorp/consul-helm/issues/358#issuecomment-596505929) I have it working with those settings. Why it is not working with the `expose-servers` branch, I can't say. Hopefully someone can shine a light on that.

Looking forward to hear from you. Thank you.

**Comment by lkysow** [comment]
Are you still running your servers in hostNetwork mode? I'm not sure why they can't resolve their KubeDNS entries otherwise.

**Comment by larssb** [comment]
I'm not. I pulled the `expose-servers` branch to its own folder and did not fiddle around with setting the stateful-server set. Only for debugging as described above, when it didn't work initially.

So?

**Comment by lkysow** [comment]
* Does kube dns work in other pods?
* Can you get me all of the logs please

**Comment by larssb** [comment]
Kube DNS works fine in other POD's. At least we have no DNS issues in other POD's. I don't know when I can give you the logs. ASAP.

**Comment by larssb** [comment]
We've went in another direction. Fetching Consul server IP's via a Shell Script, used when Consul is deployed via Terraform. In this way we can avoid storing kube-config files on different infrastructure servers - where such - high-risk files should really not be.
