### ISSUE TITLE
Acl-token Permission denied

### ISSUE THREAD

**Issue by jiangyongbing24** [hashicorp/consul-helm#359]
I use the token in acl-tokens.json to access consul-ui normally, but I use this token in spring cloud consul to register my service, and the prompt message: Permission Denied. Isn't this token a bootstrap acl token? How do I get a token with sufficient permissions?

**Comment by lkysow** [comment]
Hi, I think this is a duplicate of https://github.com/hashicorp/consul-helm/issues/360?

**Comment by lkysow** [comment]
Closing as duplicate
