### ISSUE TITLE
name for auto generated key doesn't always match

### ISSUE THREAD

**Issue by scott2449** [hashicorp/consul-helm#36]
Dynamic:
https://github.com/hashicorp/consul-helm/blob/master/templates/connect-inject-mutatingwebhook.yaml#L6
Static:
https://github.com/hashicorp/consul-helm/blob/master/templates/connect-inject-deployment.yaml#L53

I'd PR but I'm not sure how you'd want to handle that.. if it's variable or static in both locations just let me know and I can submit one.

**Comment by scott2449** [comment]
this and https://github.com/hashicorp/consul-helm/issues/13 are blockers for this chart launching on vanilla docker for windows/mac

**Comment by scott2449** [comment]
In case this was not clear enough it causes the hook container to fail because it cannot find the certificate.

**Comment by mitchellh** [comment]
Ouch sorry! We'll get this fixed ASAP and cut a patch release this week. Sorry about that.

**Comment by anubhavmishra** [comment]
@scott2449 I just fixed the configuration name that the injector uses. Hopefully, that helps!
