### ISSUE TITLE
Mesh gateways need to be re-registered (same as lifecycle-sidecar)

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#372]
If a consul client pod is restarted (e.g. during an upgrade) it loses all its registrations. We solved this in the case of Connect by running a lifecycle sidecar that re-registers the service. We need to do the same thing for mesh gateways since currently they're only registered when the gateway starts.

The result of the current behaviour is that when the client pod is restarted, the mesh gateways are deregistered and all consul connect traffic between dcs will fail.

**Comment by ishustava** [comment]
Fixed by #380.
