### ISSUE TITLE
how to disable HOST_IP addressing during sidecar proxy injection

### ISSUE THREAD

**Issue by sdeoras** [hashicorp/consul-helm#379]
Hi,

This is a question I need some help with and not a bug. I am trying to use the envoy based sidecar proxy injection, however, I see that the updated pod spec makes reference to convoy services running at $(HOST_IP). This is working fine on GKE, however, I was wondering if there is a way to specify this value statically. We need this to work on a system where HOST_IP based addressing is not working for us, but static assignment to kubernetes service name will work.

In particular, I am starting helm chart to have following service configuration
```
$ kubectl get svc
NAME                                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                                                                   AGE
consul-consul-connect-injector-svc   ClusterIP   10.0.0.50    <none>        443/TCP                                                                   8h
consul-consul-dns                    ClusterIP   None         <none>        53/TCP,53/UDP                                                             8h
consul-consul-server                 ClusterIP   None         <none>        8500/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   8h                                                       8h
kubernetes                           ClusterIP   10.0.0.1     <none>        443/TCP                                                                   12d
vault                                ClusterIP   None         <none>        8200/TCP,8201/TCP                                                         8h
vault-agent-injector-svc             ClusterIP   10.0.0.56    <none>        443/TCP                                                                   8h
```
I would like to have all references to consul service go to `consul-consul-server` and not be referenced via HOST_IP. How can I achieve this? The pod spec with annotation for sidecar injection makes references to consul via HOST_IP and I could not figure out a way to change it. Thanks in advance for your help.

**Comment by guptaarvindk** [comment]
any update on this?

**Comment by lkysow** [comment]
Hi, this isn't something that we're going to be able to support because the sidecar proxy **must** talk to the local consul client on that node. It can't talk to a Kubernetes service IP because that will route to a random consul client in the cluster and that service will be registered there but then will be re-registered on the next random consul client.

If hostPort is not working could you try using client host networking support released on 0.22.0 (https://github.com/hashicorp/consul-helm/releases/tag/v0.22.0)

**Comment by sdeoras** [comment]
Thanks for the feedback. I will give it a try using client host networking.

**Comment by lkysow** [comment]
Okay let us know if there's any issues and we can re-open.
