### ISSUE TITLE
Error in  consul/templates/client-daemonset.yaml

### ISSUE THREAD

**Issue by debjitk** [hashicorp/consul-helm#390]
Error: template: consul/templates/client-daemonset.yaml:176:23: executing "consul/templates/client-daemonset.yaml" at <(.Values.client.join) and (gt (len .Values.client.join) 0)>: can't 
give argument to non-function .Values.client.join

**Comment by lkysow** [comment]
Fixed by https://github.com/hashicorp/consul-helm/pull/383

**Comment by debjitk** [comment]
@lkysow Thanks
