### ISSUE TITLE
Use Role instead of ClusterRole for consul agents

### ISSUE THREAD

**Issue by ltagliamonte-dd** [hashicorp/consul-helm#414]
Agents can use Role instead of ClusterRole.
PodSecurityPolicy can be "used" also in Roles.
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#via-rbac

**Comment by ishustava** [comment]
Hey @ltagliamonte-dd, thanks for the issue. I'm going to close this one because it's a duplicate of #354.

**Comment by ltagliamonte-dd** [comment]
didn't see that thanks!
