### ISSUE TITLE
PVCs are not getting deleted

### ISSUE THREAD

**Issue by rakshitcgupta** [hashicorp/consul-helm#422]
After removing the release, PVCs are not being deleted with the release. Is there a parameter in helm command that I am missing?

**Comment by lkysow** [comment]
Hi Rakshit,
This is a known bug with Helm itself unfortunately: https://github.com/helm/helm/issues/5156. You'll need to run `kubectl delete pvc -l app=consul` after running `helm delete`.

**Comment by jsosulska** [comment]
This helped me out debugging too. Thanks @lkysow
