### ISSUE TITLE
Promoting the consul environment to production

### ISSUE THREAD

**Issue by rakshitcgupta** [hashicorp/consul-helm#429]
Hi,
As I couldn't find this process in any documentations - how promotion workflow is followed for consul. For example, when a user tests intentions/other configurations in SIT/UAT environments and wants to promote that in production where there will be no access, how is the process done in this case?
Thanks & Regards.

**Comment by lkysow** [comment]
Hi @rakshitcgupta, in this scenario we would expect that you use configuration as code for all your consul config, e.g. the helm chart config and using terraform for other Consul configuration like Configuration Entries.

A privileged user like a trusted ci/cd platform or an operator will still need permissions to install and configure the production evironment.

Does that help? Is there a specific workflow you need help with?

**Comment by lkysow** [comment]
Closing because we haven't heard back. If you need more help please comment and we can reopen!

**Comment by rakshitcgupta** [comment]
Hi @lkysow, yes as also suggested by one of the advocates,  Consul Terraform provider seems to be a good solution to this,  however including another tool Terraform can be out of the scope of projects (because of timelines and cost).
Hopefully, in future we can have other solutions like maybe exporting and importing the configs.

**Comment by ishustava** [comment]
Hey @rakshitcgupta, that's true. We're currently adding support for managing intentions and some config entries via CRDs, so you would be able to use kubernetes YAML for that in the future instead of terraform. Will that help your use case?
