### ISSUE TITLE
Consul client within kubernetes failed to start

### ISSUE THREAD

**Issue by debjitk** [hashicorp/consul-helm#442]
Consul client within kubernetes failed to start. Consul server is running outside k8s.

```
config: Unknown extra arguments: [tag_key=xxxxxxx tag_value=xx region=us-west-2 addr_type=private_v4 access_key_id=xxxxxxx secret_access_key=xxxxxxxx -domain=consul]
```

**Comment by ishustava** [comment]
Hey @debjitk,

Thanks for creating an issue. 

Could you tell a bit more about how you're deploying clients? This isn't enough info for us to help you debug the issue. A few pieces of information that would be helpful:
1. Your Helm chart version
1. Your Helm config values

Based on the region name, it looks like you're using AWS possibly with EKS. That would also be helpful to confirm.

**Comment by ishustava** [comment]
Hey @debjitk 

I'm going to close this issue because we haven't heard from you for a while. If you are still seeing problems with your installation, please let us know and we can re-open.
