### ISSUE TITLE
Kubernetes CA is missing complete CA chain makes curl requests to fail

### ISSUE THREAD

**Issue by den-is** [hashicorp/consul-helm#443]
Today when I've tried to install consul-helm for the first time.
I've encountered an issue and cluster were not able to proceed past initial `tls-init-job`
All tls-init-jobs jobs were failing with:
```
==> WARNING: Server Certificates grants authority to become a
    server and access all state in the cluster including root keys
    and all ACL tokens. Do not distribute them to production hosts
    that are not server nodes. Store them as securely as CA keys.
==> Using /consul/tls/ca/cert/tls.crt and /consul/tls/ca/key/tls.key
==> Saved aws-server-consul-0.pem
==> Saved aws-server-consul-0-key.pem
```
After "hacking" tls-init-job and adding verbose output to the *curl* command `-vvv` I've finally got little bit more descriptive error messages:
```
Note: Unnecessary use of -X or --request, POST is already inferred.
* Expire in 0 ms for 6 (transfer 0x55572abd0a40)
*   Trying 100.64.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55572abd0a40)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 100.64.0.1 (100.64.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [15 bytes data]
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
{ [163 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [1040 bytes data]
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
} [2 bytes data]
* SSL certificate problem: unable to get issuer certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (60) SSL certificate problem: unable to get issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

My kops based kubernetes cluster primary CA (apiserver CA) is an intermadiate CA, child CA of the main corporate internal CA.
`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` - unfortunately doesn't contain complete CA chain.

I had to update the chart and pass complete CA chain separately via mount.

**Comment by ishustava** [comment]
Hey @den-is, thanks for creating this issue.

It looks like your k8s cluster is misconfigured. Is your `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` the corporate root CA or the intermediate CA? If it's the root, then your Kube API server needs to serve leaf + intermediate so that the root will work for TLS verification.

We assume that the `ca.crt` included in the service account token works for talking to the kube api. If this is not the case, then other assumptions this helm chart and consul-k8s make will break, not just tls-init. 

This is generally the assumption on Kubernetes. You will see the same problems with any software that's using the [Kubernetes client](https://github.com/kubernetes/client-go/blob/573f9163af8594d7a0df7767101231f3864315ae/rest/config.go#L451-L481).

It does look like though that we need to add better error messaging to the tls-init job so that you don't have to "hack" the job 😃

**Comment by den-is** [comment]
@ishustava I was extremely surprised by myself when I've encountered that issue of missing complete-CA-chain in the ca.crt since that is already a quite old production cluster.
The issue was invisible until I've encountered it.
Cluster is constantly updated, but nobody is going to replace it to "fix" that CA issue :)

` /var/run/secrets/kubernetes.io/serviceaccount/ca.crt` - contains intermediate CA only.

I thought about `Kubernetes client` too. And there were no other related issues for more than year.
The most native implementation - `kubectl` has only that one "intermediate" CA too.
All other services running in that cluster work perfectly fine.
I've just never used pure `curl` for requesting Kubernetes API against that cluster.

**Comment by lkysow** [comment]
Related to https://github.com/hashicorp/consul-helm/issues/512

**Comment by taemon1337** [comment]
I have also seen this issue with certain libraries which require the full chain for validation, fluentd being one of them.

**Comment by david-yu** [comment]
Closing this issue as its related to missing the full CA Chain on Kubernetes cluster.
