### ISSUE TITLE
Init acl job fails "Unexpected response code: 403 (ACL not found)"

### ISSUE THREAD

**Issue by Smana** [hashicorp/consul-helm#460]
I just tried to install a brand new cluster and I just changed two parameters:

```
acls:
  manageSystemACLs: true
  createReplicationToken: true
```

But the job that is supposed to initiate the tokens fails with the following error:
```
2020-05-19T07:46:32.601Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 403 (ACL not found)"
2020-05-19T07:46:32.601Z [INFO]  Retrying in 1s
```

**Comment by Smana** [comment]
Forget about that, when I deployed again that worked.

**Comment by dbhat6** [comment]
Hi @Smana 
Did this issue occur ever again to you?
I'm seeing this as a persistent issue during my implementation.

**Comment by lkysow** [comment]
@dbhat6 make sure if you uninstall that you delete the `bootstrap-acl-token` secret before re-installing.
