### ISSUE TITLE
Surprising behavior on uninstall && re-install

### ISSUE THREAD

**Issue by krancour** [hashicorp/consul-helm#47]
I was struggling with getting even the most basic examples from [da-connect-demo](https://github.com/hashicorp/da-connect-demo) to work. I posted an issue [here](https://github.com/hashicorp/da-connect-demo/issues/5), but eventually concluded that the issue was with the chart and not the examples...

I had been observing that service registration was failing and seemed to be the source of all my problems. As to why it was failing...

I had installed / deleted / re-installed the Consul Helm chart a number of times in the `consul-system` namespace. As noted, on every attempt to make the examples work, service registrations failed... _silently_.

I eventually stumbled upon a realization that things _do_ work when I install the chart in a _new_ namespace. Anytime I re-install to a namespace that previously had the chart installed, things would go back to not working. Clearly, there was some state being left behind that wasn't removed by `helm delete consul --purge`...

What I had initially failed to realize was that when `helm delete consul --purge` deleted the `StatefulSet` for the Consul server, it _does not_ cascade that delete down to PVCs...

So, in any case where I deleted and re-installed in a namespace that already contained those PVCs, I was effectively launching a _new_ cluster of Consul servers backed by _old_ data. I'm not clear on why that doesn't work (one would think it should), but it doesn't.

If I take care to manually delete PVCs (or the entire namespace) after `helm delete consul --purge`, it gets me back on track for the next time I re-install into the same namespace.

So...

I'm reporting one of the two following issues. Either:

1. Re-installation of the chart to a namespace where the PVCs already exist _should_ result in a working Consul cluster

_or_

2. If there's a valid technical reason that no.1 isn't the case, the need to manually delete PVCs after `helm delete consul --purge` should be documented to help others avoid the surprises I was encountering.

**Comment by adilyse** [comment]
It looks like Kubernetes and Helm are specifically designed to not delete persistent volumes and their claims when a [StatefulSet is deleted](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-storage). Given that this is not obvious and even the StatefulSet definition is abstracted away from a Helm chart user, I've added a note to the [docs](https://github.com/hashicorp/consul/pull/4891) that people will need to manually delete these resources.

As for the re-installation of a cluster using the same storage-- there is a lot of information stored in the data directory (like node IDs) that will directly conflict with a new installation, so starting fresh is the only way to make sure it works as expected.
