### ISSUE TITLE
Consul network issues

### ISSUE THREAD

**Issue by joshk132** [hashicorp/consul-helm#477]
I have a consul cluster of 3 server nodes and 2 agents running on a K8 cluster created using KOPS Version 1.16.1 (git-d1b07f7fd6)

I had the same helm chart and config files working on an older cluster that had the exact same setup except different version of K8. 

The cluster setup is the same config as I've done before except I am now using single master and only two worker nodes. I am using flannel for the network portion of the cluster. I have not seen any reboots of the EC2 instances nor had alerts for anything besides restarting of containers and containers pending. Logs seem to correlate the restarts and pending times to times of peaked consul messages found below.

Example of some error messages I am seeing in the logs below. 

```
[WARN] agent: Check "service:70acf9ec-9c72-4a14-8663-a1b6daffa8ff" missed TTL, is now critical

2020/06/01 20:22:27 [ERR] memberlist: Failed fallback ping: write tcp 100.96.1.14:38680->100.96.2.3:8301: i/o timeout

2020/06/01 20:22:27 [INFO] consul: cluster leadership lost

2020/06/01 20:22:27 [WARN] consul: error getting server health from "consul-consul-server-2": context deadline exceeded

2020/06/01 20:22:26 [INFO] consul: New leader elected: consul-consul-server-2

2020/06/01 20:22:26 [INFO]  raft: pipelining replication to peer {Voter 45f5d61b-7eee-9b0e-d62d-7787e2523c66 100.96.1.14:8300}
```

Kubernetes information
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:36:15Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

Gist of my values file
https://gist.github.com/joshk132/6f368a3816a150d3253002d838dbd39a

**Comment by lkysow** [comment]
Hi Josh,
> besides restarting of containers and containers pending. Logs seem to correlate the restarts and pending times to times of peaked consul messages found below.

Are you seeing pods restart, e.g. consul clients or servers? If so then that might explain the io timeouts since pods are actually restarting. Assuming pods are restarting, if you run `kubectl get events` are there any relevant events that give a hint as to why the pods are restarting? What about `kubectl describe` on the pod? Also are there any logs prior to the restart other than the ones you posted?

If the pods aren't restarting, and everything was working fine before the switch to flannel then I'd guess the problem lies there. Is there anything in the flannel logs?

**Comment by lkysow** [comment]
Hi, we're going to close this for now since we haven't heard back. If you would like us to reopen this issue please comment here and we'll be happy to do so.
