### ISSUE TITLE
sidecar container is not injecting when pod is created

### ISSUE THREAD

**Issue by christian1607** [hashicorp/consul-helm#484]
consul-helm does not inject any sidecard container on any pod

**consul-helm version**: 
![image](https://user-images.githubusercontent.com/16766274/83984984-1e7e3000-a8fd-11ea-9c68-de54d83cd58d.png)

My config is:
![image](https://user-images.githubusercontent.com/16766274/83985155-ad8b4800-a8fd-11ea-86b3-61d278840b01.png)

And my deployment file is:
![image](https://user-images.githubusercontent.com/16766274/83985170-b8de7380-a8fd-11ea-9b48-1c6f37d0c702.png)

**Comment by christian1607** [comment]
All pods is runnig ok
![image](https://user-images.githubusercontent.com/16766274/83985193-d4497e80-a8fd-11ea-8374-a5c2aeb7e656.png)

**Comment by lkysow** [comment]
Hi @christian1607 can you follow the logs from the connect-injector pod and re-create the static-server pod? Do you see a log like
```
2020-06-08T16:25:10.761Z [INFO]  handler: Request received: Method=POST URL=/mutate?timeout=30s
```

Or any other logs.

**Comment by christian1607** [comment]
Hi @lkysow, it's a little weird because I just installed again consul  to get the logs you requested and now I can see my consul ui is showing the services
![image](https://user-images.githubusercontent.com/16766274/84062750-752f4c80-a985-11ea-98b1-95c3a8c792c3.png)

Really  don't know what happened.

**Comment by christian1607** [comment]
The logs in the injector shows

`sidecar-injector
Updated certificate bundle received. Updating certs...
sidecar-injector
2020-06-08T17:35:14.682Z [INFO] handler: Request received: Method=POST URL=/mutate?timeout=30s
sidecar-injector
2020-06-08T17:36:10.437Z [INFO] handler: Request received: Method=POST URL=/mutate?timeout=30s
sidecar-injector
2020-06-08T17:36:36.884Z [INFO] handler: Request received: Method=POST URL=/mutate?timeout=30s`

**Comment by christian1607** [comment]
I going to close this issue.

**Comment by lkysow** [comment]
Hmm okay thanks for the update. If there are any other issues let us know!
