### ISSUE TITLE
Sample on official blog does not work (Ingress Gateway)

### ISSUE THREAD

**Issue by ToruMakabe** [hashicorp/consul-helm#504]
I tried sample helm values for Ingress Gateway on official blog, but does not work.
https://www.hashicorp.com/blog/ingress-gateways-in-hashicorp-consul-1-8/

It seems some parameters on consul-helm chart and docker image have not caught up with the blog article yet.  When would the version supports Ingress Gateway be released?

**Comment by david-yu** [comment]
Hi @ToruMakabe thanks for the feedback. You are correct in that we have not released the official helm chart updates. Please stay tuned!

**Comment by lkysow** [comment]
If you're super eager you can use this branch: https://github.com/hashicorp/consul-helm/tree/release/0.22.0

With

```yaml
global:
  image: consul:1.8.0-rc1
  imageK8S: hashicorp/consul-k8s:0.16.0
```

and the rest of the values.

**Comment by ToruMakabe** [comment]
@david-yu @lkysow Thanks! I will wait for the next release and close it after that.

**Comment by ToruMakabe** [comment]
I have tested the new chrat version 0.22.0 with ingress gateway settings. Worked well.

# Looking forward to further integration with helm!

**Comment by david-yu** [comment]
Thanks @ToruMakabe !
