### ISSUE TITLE
Upgrade Issues (Downtime w/ Connect Enabled Services) 1.7.3 to 1.8.0

### ISSUE THREAD

**Issue by kpurdon** [hashicorp/consul-helm#509]
I'm not totally sure what information is useful for this, so I'll be happy to reply with any information requested.

My current setup:
- 1.7.3 installed via Helm w/ connect inject enabled (w/o automatic injection)
- 2 services registered w/ the injector via annotations

Everything is working as expected, to upgrade to 1.8.0 I follow https://www.consul.io/docs/k8s/operations/upgrading to the tee. I upgrade each server 1 by 1 then upgrade the clients.

Everything works until I upgrade the clients. At that point my connect enabled services begin to fail. If I re-deploy those services they work again, but I can't accept downtime during the upgrade. Is there anything I'm missing to not have downtime w/ connect enabled services?

**Comment by lkysow** [comment]
Hey @kpurdon, we're really sorry you're having issues upgrading. I'm wondering what version of consul-k8s you're running? In consul-k8s 0.10.0 we added a lifecycle-sidecar to all connect injected pods that ensures the service is re-registered when the consul clients are upgraded.

If you're not on that version you'll need to upgrade to that version and re-roll all your consul connect injected pods so they pick up the new sidecar.

**Comment by kpurdon** [comment]
I do see the lifecycle sidecar in my connect enabled services. I'm using `hashicorp/consul-k8s:0.15.0` (just using the helm chart defaults).

**Comment by lkysow** [comment]
Hmm, you should be seeing the services re-register thanks to the lifecycle sidecar. It may take up to 20s depending on how fast the client restarts. Can you share the logs from the lifecycle-sidecar container?

You shouldn't need to pin the consul-k8s version if you're already on something >= 0.10

**Comment by kpurdon** [comment]
The current logs are just repeats of something like:

```
2020-06-25 13:08:56.548 MDT Registered service: ceweb
2020-06-25T19:08:56.548Z [INFO]  successfully synced service: output="Registered service: ceweb-sidecar-proxy
```

I'll try an upgrade again soon, and pay more attention to these logs during. A quick review of the logs from the last upgrade appear to be the same though.

**Comment by lkysow** [comment]
Okay, the safest way to upgrade for you would probably be to set the client daemonset updateStrategy to `OnDelete`, then run `helm upgrade`, the clients won't be restarted yet, then drain each node, delete the consul client so it upgrades, then uncordon the node, and repeat.

That way there will be no downtime due to any lag between the connect services on that node re-registering with the new client.

**Comment by lkysow** [comment]
Hi, I think there might be another issue actually (see https://discuss.hashicorp.com/t/consul-1-8-0-proxy-health-fails-at-destination-alias/10632/2). Before consul-k8s 0.16.0 we were setting an alias check incorrectly but it was passing without issue. Now in Consul 1.8.0 that incorrectly set check will fail. To fix this you'll need to upgrade to consul-k8s 0.16.0 and then re-roll your connect pods so they get their alias check set correctly. Then when you roll your consul clients they should be re-registered properly.

**Comment by kpurdon** [comment]
@lkysow interesting! I'll give that a shot ASAP and report back here. Thank you.

**Comment by kpurdon** [comment]
Just rolled through the upgrade without issue after upgrading to `consul-k8s 0.16.0` first. Thanks!
