### ISSUE TITLE
Add bats tests for tls volumes

### ISSUE THREAD

**Issue by adilyse** [hashicorp/consul-helm#513]
From [this comment](https://github.com/hashicorp/consul-helm/pull/503#discussion_r442411103), terminating gateways need to have a test added for tls volumes. This likely extends to mesh and ingress gateways as well, and all other components should also be checked and updated if needed.

**Comment by lkysow** [comment]
I think this is the type of test missing?

https://github.com/hashicorp/consul-helm/blob/327ce4f484769f0a7948a0e65462e18d1ec1e1bd/test/unit/client-daemonset.bats#L476-L494
