### ISSUE TITLE
consul agent on openshift

### ISSUE THREAD

**Issue by Arni777** [hashicorp/consul-helm#520]
Hello,

I am trying to install a consul agent using this helm, on openshift.
My consul cluster(virtual macines) is used as a k/v store, for my Vault application(containers on openshift).
I have used this guide [https://www.consul.io/docs/k8s/installation/deployment-configurations/servers-outside-kubernetes](url).

Is it supported?
(Vault helm has openshift variable, but none here).

btw the versions are
openshift 3.7
vault 1.4.2
consul 1.7.2
helm 3.2.3

Thanks ALOT for the help,

**Comment by kschoche** [comment]
Hello and thank you for raising this issue!
Currently do not have any official support for Openshift installation via consul-helm, but we consider this a high priority feature that we are working on.
Other users have had some success before and there is a good write-up that I'd encourage you to take a look at for testing purposes here: https://github.com/kawsark/consul-helm-openshift#consul-helm-openshift

**Comment by david-yu** [comment]
Hi @Arni777 we now have OpenShift support built into Consul Helm, and you can enable it by setting the global openshift variable "enabled" true" as described here: https://learn.hashicorp.com/tutorials/consul/kubernetes-openshift-red-hat. Thanks for your feedback!
