### ISSUE TITLE
Consul Integration with Azure Application gateway Ingress controller or NGINX Ingress controller

### ISSUE THREAD

**Issue by shubhammicrosoft1** [hashicorp/consul-helm#527]
We are trying to use Pod-Pod mTLS using CA . However we are using Azure Application gateway ingress controller for the same to route traffic inside the kubernetes cluster using Consul
Is there a documentation available for the same to integrate Consul Service mesh with Azure Application gateway ingress controller or with NGINX controller

**Comment by lkysow** [comment]
Hi Shubham,
There is no documentation right now unfortunately. You would need to deploy a Consul ingress gateway and then point your Azure application gateway at the Consul ingress gateway. We are working on docs for the Consul ingress gateway right now.

**Comment by shubhammicrosoft1** [comment]
Sure , @lkysow

**Comment by lkysow** [comment]
Ingress docs are here now: https://www.consul.io/docs/k8s/connect/ingress-gateways
