### ISSUE TITLE
Can we using Vault PKI to create CA?

### ISSUE THREAD

**Issue by ducminhle** [hashicorp/consul-helm#542]
Hi,
I have a question about vault and consul. 
With old datacenters we deployed on VMs, we use Vault PKI to create CA and TLS for Consul servers. How can we continue using Vault PKI for Consul on EKS with helm?
Thank you.

**Comment by david-yu** [comment]
Hi @ducminhle thanks for the question. We currently allow you to use an intermediate CA generated by Vault CA and utilize that the create TLS certs for Consul on Kubernetes. Using Vault to create intermediate CA's would require root capabilities and is something we don't recommend as it would compromise the security model if the Consul on Kubernetes were compromised. Let me know if that helps, if so I will close. 

Here are the docs for providing the CA to Consul on Kubernetes along with the private key: https://www.consul.io/docs/k8s/helm#v-global-tls-cacert

**Comment by ducminhle** [comment]
Thank you @david-yu for your answer :).
