### ISSUE TITLE
Expose Consul DNS as internal LoadBalancer

### ISSUE THREAD

**Issue by slauger** [hashicorp/consul-helm#545]
I'm running consul on GKE in GCP and would like to expose the DNS service via an internal LoadBalancer (`cloud.google.com/load-balancer-type: "Internal"`).

Currently the the service type is harcoded to ClusterIP.

https://github.com/hashicorp/consul-helm/blob/63037756ce11d8824f81af9149e7b0691b3e66c1/templates/dns-service.yaml#L20

Would you accept a PR for that?

**Comment by adilyse** [comment]
Hi @slauger,

It looks like we do default to ClusterIP by leaving out the `type` field entirely on the dns service (see the [ClusterIP](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types) definition). The `clusterIP` value in the template will only be populated if the setting was defined in the values file:
```
{{- if .Values.dns.clusterIP }}
  clusterIP: {{ .Values.dns.clusterIP }}
{{- end }}
```

It would definitely be reasonable to allow users to specify the type of service, so we'd be open to a PR that added that functionality.

**Comment by slauger** [comment]
Could someone have a look at #555?
