### ISSUE TITLE
Question regarding architecture

### ISSUE THREAD

**Issue by hveiga** [hashicorp/consul-helm#576]
Hi all,

I am not fully sure if this is the channel to ask this kind of questions, if not, please let me know where should I direct it.

We are trying to install consul-server with 3 replicas using this helm chart. Our intention is to deploy consul-server in its own Kubernetes namespace and then access it from other namespaces by using some kind of dns name. Is this approach possible? This is the current setup we have outside of Kubernetes, so we thought about following the same.

Any help/suggestion is appreciated.

Thanks.

**Comment by ashwin-venkatesh** [comment]
Hey @hveiga

Feel free to ask these questions at https://discuss.hashicorp.com

But for the situation that you are currently running into, have you been unable to access the consul servers from other namespaces? The consul-server deployment can be configured to have 3 replicas. It is fronted by a service called `consul-service` which should allow communicating with the pods over `kube-DNS`. I think the above deployment is possible.
Have you run into problems with the default helm installation of consul?

**Comment by hveiga** [comment]
Hi @ashwin-venkatesh thanks for the response. We have not started testing and it's good to know it should be possible. Next time I'll use  https://discuss.hashicorp.com for this kind of questions. I'll close this ticket for now. Thanks again.

**Comment by ashwin-venkatesh** [comment]
@hveiga Glad I could help. Good luck!!
