### ISSUE TITLE
Cloud Auto-joining not working with AWS provider

### ISSUE THREAD

**Issue by jailson-silva** [hashicorp/consul-helm#59]
Hi Guys!

I had tried join consul cluster using cloud auto-join in Kubernetes.

I'm using helm for consul with configuration below:

First attempt
```
client:
enabled: true
image: null
join: ["provider=aws", "tag_key=consul-staging", "tag_value=auto-join"]
```

Second attempt
```
join:
- "provider=aws"
- "tag_key=consul-staging"
- "tag_value=auto-join"
```
For the both ways I got the same error:

```
Failed to resolve tag_key=consul-staging: lookup tag_key=consul-staging: no such host
* Failed to resolve tag_value=auto-join: lookup tag_value=auto-join: no such host
    2018/11/09 15:21:35 [WARN] agent: Join LAN failed: <nil>, retrying in 30s
    2018/11/09 15:21:37 [WARN] manager: No servers available
    2018/11/09 15:21:37 [ERR] http: Request GET /v1/status/leader, error: No known Consul servers from=127.0.0.1:59748
    2018/11/09 15:21:47 [WARN] manager: No servers available
    2018/11/09 15:21:47 [ERR] http: Request GET /v1/status/leader, error: No known Consul servers from=127.0.0.1:59818
    2018/11/09 15:21:53 [WARN] manager: No servers available
    2018/11/09 15:21:53 [ERR] agent: failed to sync remote state: No known Consul servers
    2018/11/09 15:21:57 [WARN] manager: No servers available
    2018/11/09 15:21:57 [ERR] http: Request GET /v1/status/leader, error: No known Consul servers from=127.0.0.1:59874
    2018/11/09 15:22:05 [INFO] discover-aws: Address type  is not supported. Valid values are {private_v4,public_v4,public_v6}. Falling back to 'private_v4'
    2018/11/09 15:22:05 [INFO] discover-aws: Region not provided. Looking up region in metadata...
    2018/11/09 15:22:05 [INFO] discover-aws: Region is us-east-1
    2018/11/09 15:22:05 [INFO] discover-aws: Filter instances with =
    2018/11/09 15:22:05 [INFO] agent: Discovered LAN servers:
    2018/11/09 15:22:05 [INFO] agent: (LAN) joining: [tag_key=consul-staging tag_value=auto-join]
    2018/11/09 15:22:05 [WARN] memberlist: Failed to resolve tag_key=consul-staging: lookup tag_key=consul-staging: no such host
    2018/11/09 15:22:05 [WARN] memberlist: Failed to resolve tag_value=auto-join: lookup tag_value=auto-join: no such host
    2018/11/09 15:22:05 [INFO] agent: (LAN) joined: 0 Err: 2 error(s) occurred:
```

Just for test purpose I have changed "join" attribute instead of tag_key and tag_value to consul-cluster IP address:

```
client:
  enabled: true
  image: null
  join: ["10.29.20.137", "10.29.20.148", "10.29.20.60"] # Fake IPs
```
With this configuration passing IP address I got join on cluster successfully.

For troubleshooting:

- I've checked role permissions attached in kubernetes node  - OK.

- I've checked communications between nodes and consul-server - OK for ALL ports.

- I've have other consul clients using cloud-discovery and that clients works perfectly.

- I've followed instruction from issue #16 but unsuccessfully.

Can help me?

If you need more detailed information please just let me known.

Thanks,

**Comment by adilyse** [comment]
Thank you for following up @jailson-silva! There is definitely something still wrong here.

It looks like I fixed the documentation so that it would work with a Helm `range` command in the definition of this variable, but it was the `range` command that was wrong! I'll get a fix up soon and update the documentation as well.

Very sorry about the confusion!

**Comment by adilyse** [comment]
Quotes were being lost when this value was being processed, so the failure in #16 looked like the values had to provided with a different syntax. Instead, I've now fixed the underlying issue of missing quotes and updated the documentation to match.

The join should be inputted as:
```
