### ISSUE TITLE
port conflict when more than one consul deployed on a kubernetes cluster

### ISSUE THREAD

**Issue by nixilin** [hashicorp/consul-helm#597]
I have 2 namespaces and want to install 2 consuls for each namespace. But all agents' ready state on second consul is 0/1.
I described related pod and see the following message
0/5 nodes are available: 5 node(s) didn't have free ports for the requested pod ports.

So I guess error reason is about port conflict
Because agents' 8500 port will listen on all kubernetes worknode by using daemonset.
change 8500 to other port may cause other unexpected problem?
The only way to solve this is disable agent . But I dont think is a good idea.
So is there any other way to solve this?
Thanks~

**Comment by ishustava** [comment]
Hey @nixilin,

This was already reported in #126.

Yes, unfortunately, we don't support installing the consul helm chart into two Kubernetes namespaces on the same cluster.
