### ISSUE TITLE
readinessProbe and livenessProbe of the connect inject webhook are to strict

### ISSUE THREAD

**Issue by jsiebens** [hashicorp/consul-helm#610]
For some environments, the `readinessProbe` and `livenessProbe` of the connect inject webhook seem too strict.
For examples on a Raspberry Pi, it takes a little bit longer than allowed by the `initialDelaySeconds`, `periodSeconds` and `failureThreshold`. This result in a CrashLoopBackOff because of the probe failures.

**Comment by lkysow** [comment]
Agreed, I've seen this issue too when running on `kind`. Although I haven't seen a crash loop back-off once the certificate gets provisioned but I've seen it restart 1-2 times on initial install.

**Comment by cerebrate** [comment]
I get this on both the connect-inject container and the consul-server container on my Pi cluster, FWIW.

**Comment by lkysow** [comment]
>  consul-server container

The consul-server statefulset doesn't have any liveness probes so that would have to be another issue.

**Comment by lkysow** [comment]
Right but that won't result in a crash loop. I think it's okay that it marks the servers as unready until they're ready unless I'm missing something. What effect would increasing period/initial delay have?

**Comment by cerebrate** [comment]
...of course it won't. Sorry. Not sure what I was thinking of, then.

**Comment by lkysow** [comment]
No worries! 😄 It's good to have a conversation regardless.
