### ISSUE TITLE
syncCatalog.consulNodeName causes a CrashLoopBackOff on the sync catalog pod

### ISSUE THREAD

**Issue by mariusehr1** [hashicorp/consul-helm#628]
Hi,

I noticed that by enabling the `syncCatalog.consulNodeName` flag, on startup, the sync catalog pod would crash with the following log : 

```
flag provided but not defined: -consul-node-name
Usage: 
-add-k8s-namespace-suffix.  
        If true, Kubernetes namespace will be appended to service names synced to Consul separated by a dash. If false, no suffix will be appended to the service name
[...]
```
In order to make I work I had to manually remove the flag within the deployment.

Is there a way to correct it within the chart ? Should I make a PR?

Thanks.
Marius

**Comment by lkysow** [comment]
Hi, this feature isn't released yet. I'm guessing you're using consul-helm `master` instead of one of our releases (https://artifacthub.io/packages/helm/hashicorp/consul).

**Comment by mariusehr1** [comment]
Hi,

yes I am using the master branch. I probably should have used a release instead. 

Is it related to the version of the `consul-k8s` binary?

Eitherway I can fix it myself or use a stable release.

Thanks.

**Comment by lkysow** [comment]
> Is it related to the version of the consul-k8s binary?

The flag is in the `consul-k8s` master but we haven't cut a release for that yet.
