### ISSUE TITLE
Add support for environment variable HOST_IP

### ISSUE THREAD

**Issue by bsc8180** [hashicorp/consul-helm#657]
We want to send dogstatsd metrics to a Datadog agent on the same node as our Consul pod using the telemetry stanza as follows

(configmap extra-from-values.json)

`{
  "telemetry": [
    {
      "disable_hostname": true,
      "dogstatsd_addr": "HOST_IP:8125",
      "dogstatsd_tags": ["env:weweq","service:consul","version:1.8.0"]
    }
  ]
}`

We currently do this for Vault, courtesy of the HOST_IP environment variable set by default in the [helm template](https://github.com/hashicorp/vault-helm/blob/ee4e532159b023dece6d69ec58666cd50d85a47b/templates/server-statefulset.yaml#L72).

We would like to to see the same functionality in the Consul helm chart, or clearer documentation on how to add complex environment variables to extraEnvironmentVars (the documentation shows only simple k/v pairs).

Should just be a matter of adding 

`            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP`

to [server-statefulset.yaml](https://github.com/hashicorp/consul-helm/blob/203d9073da4ce5c1067fba03d8ce0abcc0f4e20d/templates/server-statefulset.yaml#L107)

**Comment by watsonian** [comment]
Prior art from the vault helm chart:

https://github.com/hashicorp/vault-helm/blob/fc8ebfdd4e596bf9b22f814265ddf57b4a454d69/templates/server-statefulset.yaml#L72-L75

**Comment by watsonian** [comment]
Also worth pointing out this bit from the vault helm chart:

https://github.com/hashicorp/vault-helm/blob/994797cff4dc12887acc9fc7fccb70d34f3254b9/templates/_helpers.tpl#L119-L135

**Comment by yannlambret** [comment]
Would it be possible to simply replace the current implementation of the partial template `consul.extraEnvironmentVars`, so that we can declare environment variables in the native specification format? I don't really see the added value of the map interface here.
