### ISSUE TITLE
Consul configuration issue.

### ISSUE THREAD

**Issue by lebrisg** [hashicorp/consul-helm#670]
I'm trying to connect a VM to a K8s cluster inside the same dc.
I have already read the guide that you provide (https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes) but there are few details inside.
I've got a fully connected network. However, without any additional configuration, no port used by Consul are open to the outside at the K8s cluster level. You need to do something to get it working (use NodePort or add an ingress controller???).
But the guide doesn't provide any clue.

_Originally posted by @lebrisg in https://github.com/hashicorp/consul-helm/issues/653#issuecomment-713009623_

**Comment by lkysow** [comment]
Hi, you will need connectivity between:
* All Consul Server Pods on their advertise IPs (pod ips) and port 8300
* All Consul client pods (the daemonset) and their advertise ips (pod ips) on port 8301
* The VM on its advertise IP and port 8301

If your Kubernetes pod IPs are not routable from the VM then you will not be able to run with this topology right now.

**Comment by lebrisg** [comment]
Thank for this answer.

Now, as I'm not a Kubernetes networking expert, is there any documentation on how to configure the networking part? How to configure a nodePort service or how to install an Ingress controller to deal with this?
I'm asking this question because I didn't find anything on this subject on your website when it's a mandatory task for anybody wanting to deploy Consul on Kubernetes.

**Comment by ishustava** [comment]
Hey @lebrisg 

You don't need a NodePort service or an ingress if your pod IPs are routable from the Consul server VMs. As Luke has said, if the pod IPs are not routable, you won't be able to use this topology, unfortunately. This is because we [don't allow](https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes#networking) currently to expose the Consul servers via hostPort to allow clients to connect using the node IP instead of the pod IP.

We can't use a NodePort service for this purpose because a service won't guarantee reaching a specific node. Rather kubernetes would load balance randomly between consul server pods. This won't work for gossip because Consul needs to be able to reach each agent. The ingress also won't quite work because it only supports TCP ports, and Consul uses UDP for gossip.

Hope this helps!

**Comment by lebrisg** [comment]
As previously described, I've got the following networking architecture:
- 1 Kubernetes cluster (1 master: kube1, 2 workers: kube2 & kube3)
- kube1: VM=CentOS 7, IP=5.X.Y.5
- kube2: VM=CentOS 7, IP=5.X.Y.6
- kube3: VM=CentOS 7, IP=5.X.Y.7
- VM: VM=CentOS 7, IP=5.X.Y.23
- Consul 1.8.4 installed on the Kubernetes cluster (with your Helm chart) and on the VM (official HashiCorp repo).
- All VMs can communicate each other because there are in the same network and there is no firewall (and same DC).
- However, pods and VM can't see each other (10.244.Z.T can't see 5.X.Y.23):
$ kubectl get pod -o wide
NAME                     READY   STATUS    RESTARTS   AGE   IP            NODE                  NOMINATED NODE   READINESS GATES
consul-consul-server-0   1/1     Running   0          17d   10.244.2.15   kube3   <none>           <none>
consul-consul-vxzn6      1/1     Running   0          17d   10.244.1.18   kube2   <none>           <none>
consul-consul-xxchw      1/1     Running   0          17d   10.244.2.14   kube3   <none>           <none>

In this configuration, what can be done?

**Comment by ishustava** [comment]
How are you deploying your Kubernetes cluster? do you know which CNI you're using? 

Whether the pod IPs are routable is largely dependent on the CNI configured on your kubernetes cluster. For example, EKS cluster uses AWS VPC CNI by default, which would make your pod IPs routable since they are allocated from a AWS subnet.

If your kubernetes cluster doesn't allow the pod IPs to be routable, we also have #332 (wip) to expose server's hostPorts.

**Comment by lebrisg** [comment]
My Kubernetes cluster was deployed with kubeadm (kubeadm init --pod-network-cidr=10.244.0.0/16).
The CNI used is Flannel (kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml).

Is there any other information that could help you to better understand my configuration?
What kind of additional configuration do I need to put in place for my VM and pods to see each other?

**Comment by ishustava** [comment]
Thank you, that's all the information I needed! 

Unfortunately, you can't have pods routable with Flannel. You need to wait on that feature I mentioned (#332) where we can expose server's hostPorts so that they can be reachable at the node IP from your clients running on VMs.

**Comment by lebrisg** [comment]
Is there a CNI I could install to get this to work?

**Comment by ishustava** [comment]
As far as I know, this would depend on your cloud provider. Some examples of CNIs that pick pod IPs from your cloud provider network are AWS VPC CNI, GKE CNI, Azure CNI etc. Basically, you'd need a CNI that can select pod IPs from a network that **could** be routable similar to your kubernetes nodes network.

**Comment by lebrisg** [comment]
My VMs run on KVM. I can deploy whatever CNI I want. What CNI do you think would work?

**Comment by ishustava** [comment]
are you running KVMs on-prem or in the cloud? What do you use for your node/VM network?

I'm not an expert when it comes to kube CNIs but I think it really depends on your underlying infrastructure/cloud provider. I find this list from kubernetes.io pretty good to use as a comprehensive list of CNIs:

https://kubernetes.io/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model

**Comment by lebrisg** [comment]
I reinstalled my cluster Kubernetes and chose Calico as CNI plugin.
When launching the cluster creation, I used the following command: "kubeadm init --pod-network-cidr=192.168.0.0/16"

On my Kubernetes cluster, I get the following configuration:
NAME|READY|STATUS|RESTARTS|AGE|IP|NODE|NOMINATED NODE|READINESS GATES
------|------|--------|----------|---|--|----|------------------------|-------------------
consul-consul-q787l|1/1|Running|0|23h|192.168.17.2|kube3.example.com|<none>|<none>
consul-consul-server-0|1/1|Running|0|23h|192.168.17.3|kube3.example.com|<none>|<none>
consul-consul-sr6t8|1/1|Running|0|23h|192.168.8.132|kube2.example.com|<none>|<none>

On my consul client VM, I defined the following configuration:
retry_join = ["provider=k8s label_selector=\"app=consul,component=server\""]

When starting the consul client on my VM, I get the following messages:
==> Starting Consul agent...
Version: '1.8.4'
Node ID: '9a80c024-1846-36e4-27d3-d1aadb78b66f'
Node name: 'consul-ext'
Datacenter: 'dc1' (Segment: '')
erver: false (Bootstrap: false)
Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: -1, DNS: 8600)
Cluster Addr: 5.X.Y.23 (LAN: 8301, WAN: 8302)
Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
==> Log data will now stream in as it occurs:
[WARN]  agent.client.memberlist.lan: memberlist: Binding to public address without encryption!
[INFO]  agent.client.serf.lan: serf: EventMemberJoin: consul-ext 5.X.Y.23
[INFO]  agent.router: Initializing LAN area manager
[INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=tcp
[INFO]  agent: Started DNS server: address=0.0.0.0:8600 network=udp
[INFO]  agent: Started HTTP server: address=[::]:8500 network=tcp
[INFO]  agent: started state syncer
==> Consul agent running!
[INFO]  agent: Retry join is supported for the following discovery methods: cluster=LAN discovery_methods="aliyun aws azure digitalocean gce k8s linode mdns
[INFO]  agent: Joining cluster...: cluster=LAN
[DEBUG] agent: discover: Using provider "k8s": cluster=LAN
[WARN]  agent.router.manager: No servers available
[ERROR] agent.anti_entropy: failed to sync remote state: error="No known Consul servers"
[INFO]  agent: Discovered servers: cluster=LAN cluster=LAN servers=192.168.17.3
[INFO]  agent: (LAN) joining: lan_addresses=[192.168.17.3]
[INFO]  agent: Newer Consul version available: new_version=1.8.5 current_version=1.8.4
[DEBUG] agent.client.memberlist.lan: memberlist: Failed to join 192.168.17.3: dial tcp 192.168.17.3:8301: i/o timeout
[WARN]  agent: (LAN) couldn't join: number_of_nodes=0 error="1 error occurred:"
"* Failed to join 192.168.17.3: dial tcp 192.168.17.3:8301: i/o timeout"

The consul client VM sees the Kubernetes cluster (server=192.168.17.3) but can't join it.
How do I connect my consul client VM with my Kubernetes cluster?

**Comment by lkysow** [comment]
You need your pod ips to be routable from your VM and vice versa. If you're using an overlay network then unless your VM is part of that network (which most of the overlays don't support afaik), you won't be able to route back and forth.

**Comment by lebrisg** [comment]
Could you provide some documentation on your website on how to do that?

**Comment by lkysow** [comment]
For we should do that. I've created https://github.com/hashicorp/consul-helm/issues/743 to track.

**Comment by ishustava** [comment]
Hey @lebrisg, we have [documented](https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes#networking) the network requirements when joining an external Consul client to a k8s cluster. 

Additionally, we now also support joining an external client VM via the host network ([docs](https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes#auto-join-via-host-ports)). I'd recommend using that feature in your case so that you don't have to make pod IPs routable from the external VM and vice versa. 

Hope this helps!
