### ISSUE TITLE
Failed to delete pod from statefulset - hashicorp-consul-server-X - "EKS"

### ISSUE THREAD

**Issue by yevgeniyo** [hashicorp/consul-helm#686]
Failed to delete pod from statefulset - hashicorp-consul-server-X

helm chart - 0.26.0

Stuck on:

```
  Normal   Killing                 104s (x2 over 2m27s)  kubelet, ip-10-x-y-z.ec2.internal  Stopping container consul
  Warning  FailedPreStopHook       104s                  kubelet, ip-10-x-y-z.ec2.internal  Exec lifecycle hook ([/bin/sh -c consul leave]) for Container "consul" in Pod "hashicorp-consul-server-1_consul(10b79ef8-07b0-4161-8dcd-67bb78f77d4d)" failed - error: command '/bin/sh -c consul leave' exited with 126: , message: "OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown\r\n"
  Warning  Unhealthy               44s (x4 over 19m)     kubelet, ip-10-x-y-z.ec2.internal  Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  Unhealthy               41s (x2 over 44s)     kubelet, ip-10-x-y-z.ec2.internal  Readiness probe failed: OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown
```

Thus helm upgrade is not working

**Comment by yevgeniyo** [comment]
https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L214

**Comment by yevgeniyo** [comment]
tls:
  verify: false

fixed it to me, closing

**Comment by yevgeniyo** [comment]
tls:
verify: false

fixed it to me, closing

**Comment by yevgeniyo** [comment]
once stopping container it wont deleted

**Comment by david-yu** [comment]
@yevgeniyo Could you tell me how we could reproduce this? What version of the Helm chart were you on prior to upgrading to 0.26?

**Comment by yevgeniyo** [comment]
Hi @david-yu 
I guess its related to this issue:
https://github.com/hashicorp/consul-helm/issues/687
And see here the latest comment:
https://github.com/kubernetes/kubernetes/issues/39170

My kubernetes version is 1.18 on EKS
It's new deployment so I didnt use prior versions of chart

**Comment by yevgeniyo** [comment]
I found my issue, it was due to gossip key length, I used 16 instead of 32
