### ISSUE TITLE
[feature-request] provide customizable storageclass

### ISSUE THREAD

**Issue by mmisztal1980** [hashicorp/consul-helm#7]
It would be pretty awesome if the chart would support providing a storage class name via the values.yaml file. Is there a chance of having that implemented?

**Comment by mitchellh** [comment]
Yep definitely, feel free to open a PR but we'll also try to get to it soon!

**Comment by mmisztal1980** [comment]
What is the default value, you guys would prefer?

**Comment by mitchellh** [comment]
I would just set it only if the value is set, so we retain the cluster default for now.

**Comment by mmisztal1980** [comment]
I’ll open up a PR in a few hrs

**Comment by mitchellh** [comment]
Closed by #7. Thanks!
