### ISSUE TITLE
connect-injector-webhook TLS Certificate

### ISSUE THREAD

**Issue by abrucker235** [hashicorp/consul-helm#702]
Wondering if there is a simple fix to seeing the following error: http: TLS handshake error from 192.168.X.X:34576: No certificate available.

Kubernetes Version: 1.19.4
Calico Version: 3.16.5
Consul Version: 1.8.6
Consul-K8S Version: 0.20.0

**Comment by abrucker235** [comment]
After some digging I believe the issue is with etcd throughput since I am only using SD Card, going to look at testing different data storage for API Server.

**Comment by lkysow** [comment]
Hi, we see this too occasionally however it should shortly resolve itself. I notice when using `kind` but never on a real cluster.

**Comment by abrucker235** [comment]
I got NVMe drives in and now have the 3 RPi 2GB master nodes booting from them over usb3. This issue is currently gone on my cluster and I will plan on documenting hardware and setup [here](https://github.com/abrucker235/pi-k8s-cluster).
