### ISSUE TITLE
How to access consul dns when acl is enabled?

### ISSUE THREAD

**Issue by rammaram06** [hashicorp/consul-helm#732]
Hi,

I'm using 0.26.0 release and installed consul on our rancher cluster. I have enabled acl's and dns during installation and I would like to access consul dns(I have opened port 8600). Could you guys guide me on how to access consul dns from outside the cluster when acl token is enabled?

Consul version: 1.8.5

Thanks

**Comment by ashwin-venkatesh** [comment]
Hey @rammaram06 

Thanks for the question. Could you elaborate a little bit on the use-case here specifically? Is this so that a service from outside the cluster can access a service running in the cluster?

**Comment by ashwin-venkatesh** [comment]
Quick follow up question @rammaram06. Do you have `dns` enabled? This can be achieved by either having `global.enabled` set to `true` or `dns.enabled` set to `true`. We automatically configure anonymous auth for DNS when ACLs are enabled if DNS is enabled. So you should be able to use it in a fashion similar to how you would have used DNS if ACLs were disabled.
