### ISSUE TITLE
Document how to join an external VM running a Consul client to a Kubernetes cluster

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#743]
Document how to join an external VM running a Consul client to a Kubernetes cluster where servers and clients are running.

(see https://github.com/hashicorp/consul-helm/issues/670)

**Comment by ishustava** [comment]
Closing because these [docs](https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes) now exist!
