### ISSUE TITLE
why consul chart use global?

### ISSUE THREAD

**Issue by yxxhero** [hashicorp/consul-helm#754]
When I use consul as a subchart, I found consul chart contain global, I think this will pollute father global values.

**Comment by lkysow** [comment]
Hi @yxxhero this is a known issue (https://github.com/hashicorp/consul-helm/issues/238). Unfortunately we don't think we can change this at this time because we use the `global` key so heavily.

**Comment by yxxhero** [comment]
ok!  Thanks for your answer!
