### ISSUE TITLE
Support for Kubernetes Ingress for UI

### ISSUE THREAD

**Issue by ryan-dyer-sp** [hashicorp/consul-helm#758]
#### Feature Description

It would be nice if the helm chart supported the addition of using an Ingress for the UI.  Currently the UI only configures a service.  For us, that means its not usable as there's no access to the UI for users.  We have to manually create an ingress pointing to the service which then users can access.  

#### Contributions

Would be happy to add a ui-ingress.yaml template if this is something that would be accepted.  Please direct me to any docs for how testing is done if this is acceptable.

Thanks!

**Comment by ashwin-venkatesh** [comment]
Hey @ryan-dyer-sp 

Thanks for the feature request. This is potentially something we could consider. Out of curiosity, is there any reason why setting up the service type of the Consul UI as a `LoadBalancer` does not work for your use-case? We could potentially setup a template for ingress but could you elaborate on your use-case some more?

**Comment by ryan-dyer-sp** [comment]
Using a LoadBalancer for every service that we run in our k8s gets expensive.  We have over a dozen clusters.  Adding a LoadBalancer for each of the consuls running on these clusters would be expensive versus using the Ingress functionality that we already have.  I think most people use Ingresses instead of LoadBalancer services.

The vault helm chart already supports this functionality: https://github.com/hashicorp/vault-helm/blob/master/templates/server-ingress.yaml

**Comment by thisisnotashwin** [comment]
Addressed by #774

**Comment by ElSamhaa** [comment]
does this work work with Nginx controllers?

**Comment by mbu147** [comment]
> Does this work with Nginx controllers? because seems it doesn't when I tried it on minikube!

we use consul-ui with nginx ingress on Rancher RKE with out problems
in our consul helm deployment we add a custom yaml with ingress definition

**Comment by thisisnotashwin** [comment]
@ElSamhaa Could you share the error you are seeing? We did test this with an Nginx controller on GKE and that did work in our testing. Did the Ingress controller not reconcile the Ingress resource that was created?

**Comment by ElSamhaa** [comment]
@mbu147 @thisisnotashwin I've been able to make some progress.

However, the paths I've been passing to the helm chart don't work.

```sh
helm install consul hashicorp/consul \                                                                                                                  <<<
  --set server.replicas=1 \
  --set ui.ingress.enabled=true \
  --set 'ui.ingress.hosts[0].host=localhost' \
  --set 'ui.ingress.hosts[0].path=/consul' \
  --set 'ui.ingress.hosts[1].host=k8s' \
  --set 'ui.ingress.hosts[1].path=/consul'
```
The ingress always registers the root path `/` and not `/consul`, so it gives me `404` when I try something like `localhost/consul`.

**Comment by thisisnotashwin** [comment]
Hey @ElSamhaa ! Can you try the following command

```
helm install consul hashicorp/consul \                                                                                                                  <<<
  --set server.replicas=1 \
  --set ui.ingress.enabled=true \
  --set 'ui.ingress.hosts[0].host=localhost' \
  --set 'ui.ingress.hosts[0].paths[0]=/consul' \
  --set 'ui.ingress.hosts[1].host=k8s' \
  --set 'ui.ingress.hosts[1].paths[0]=/consul'
 ```

The ingress config supports having a []paths per host and I suspect this was a configuration issue

**Comment by ElSamhaa** [comment]
@thisisnotashwin thanks, I think this is it.
