### ISSUE TITLE
Unable to add service via API call from curl using token with manageSystemACLs enabled

### ISSUE THREAD

**Issue by ufou** [hashicorp/consul-helm#765]
### Overview of the Issue

I've deployed the latest version of consul-helm to my 1.18 k8s (bare-metal) cluster with ACLs enabled and into a namespace called `consul-system`, the install was smooth but I'm unable to PUT service data into the consul via the API and curl

I'm assuming I've missed a step somewhere or missed something that I must enable in order to run consul in production with ACLs enabled?

```
consul version
Consul v1.9.1
Revision ca5c38943
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```

### Reproduction Steps

Steps to reproduce this issue:

1. When running helm install with the following `values.yml`:
```
global:
  datacenter: dc1
  acls:
    manageSystemACLs: true
    createReplicationToken: true
```

1. Exec into a pod that has the curl command available
2. Create payload.json from https://www.consul.io/api-docs/agent/service#sample-payload
3. Try to add service payload via api using curl, eg from https://www.consul.io/api-docs/agent/service#sample-request-2
4. Grab the token from secrets: `kubectl get secrets -n consul-system consul-consul-client-acl-token -o yaml`
5. Extract the token `echo 'ZDdjNzY4MGEtZDM2Zi1kNmRhLTk5Y2UtNGExNDBiOGYyZmY0' | base64 --decode`
6. Try adding the payload again via curl/api this time using the token
7. `export TOKEN=d7c7680a-d36f-d6da-99ce-4a140b8f2ff4`
8. `curl --header "X-Consul-Token: ${TOKEN}" --data @payload.json -XPUT http://consul-consul-server.consul-system:8500/v1/agent/service/register?replace-existing-checks=true`

Also from within a consul pod (either server or client) listing the acl tokens fails:
```
/ $ consul acl token list
Failed to retrieve the token list: Unexpected response code: 403 (rpc error making call: rpc error making call: Permission denied)
```

### Logs

```
2021-01-14T12:24:31.822Z [ERROR] agent.http: Request error: method=PUT url=/v1/agent/service/register from=10.246.13.121:58748 error="Permission denied: Missing service:write on redis"
```

### Expected behavior

I'd expect for the service to be added so that it can be listed via the api

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: `0.22.0`
- `consul-helm` version: `0.28.0`
- `values.yaml` used to deploy the helm chart: as above

**Comment by kschoche** [comment]
Hi @ufou thank you for filing this issue!
I was able to follow your workflow but use the bootstrap acl token instead, can you give that a try?

```
1. CONSUL_HTTP_TOKEN=$(kubectl get secret kyle-consul-consul-bootstrap-acl-token -o jsonpath={.data.token} | base64 -D)
2. kubectl exec -it kyle-consul-consul-7cr45 -- sh
3. curl --request PUT --header "X-Consul-Token: $CONSUL_HTTP_TOKEN" --data @/tmp/payload.json -k http://127.0.0.1:8500/v1/agent/service/register?replace-existing-checks=true
4. curl http://127.0.0.1:8500/v1/agent/services
{"redis1":{"ID":"redis1","Service":"redis","Tags":["primary","v1"],"Meta":{"redis_version":"4.0"},"Port":8000,"Address":"127.0.0.1","TaggedAddresses":{"lan_ipv4":{"Address":"127.0.0.1","Port":8000},"wan_ipv4":{"Address":"127.0.0.1","Port":8000}},"Weights":{"Passing":10,"Warning":1},"EnableTagOverride":false,"Datacenter":"dc1"}}/ $
```
Also just as a general note, since you mentioned that you were considering production use cases, we *highly* recommend using TLS (`global.tls.enabled=true`) whenever ACLs are enabled for additional security!

**Comment by ufou** [comment]
Hi @kschoche ah, great, that worked - did I miss the part about using the bootstrap token in the docs somewhere? Apologies if I did, yes we will enable TLS - we're just evaluating consul atm - thanks so much for responding so quickly, much appreciated!

Presumably it's best to add a token for each kind of access, is there a preferred method for adding tokens in a helm/k8s environment or a doc about this somewhere you can point me at?
