### ISSUE TITLE
Consul configuration should be more declarative 

### ISSUE THREAD

**Issue by ufou** [hashicorp/consul-helm#768]
#### Question

Hi, we're running into some issues with the helm chart for our use case which others may have hit too.

Our use case is to bring up an isolated k8s cluster (one of many, which we bring up/tear down depending on workload) - within the cluster we require the use of consul DNS, so we can dynamically add/remove entries via the consul API - this works - however as we move towards putting this into production some things don't align, eg:

```
... secret contains the Consul ACL bootstrap token. The bootstrap token is a full access token that can perform any operation in the service mesh. In a production scenario, you should avoid using the bootstrap token, and instead create tokens with specific permissions. In this tutorial, you will use it for convenience ...
```

Although we can use the bootstrap token to create service/DNS entries - it's advised not to - so how should we declaratively create the ACL token which has reduced permissions?

Another related question is that when we set `bootstrapToken` secret name/key as a value for the chart and have already created a secret/token prior to this chart being deployed, eg:
```
          acls:
            manageSystemACLs: true
            bootstrapToken:
              secretName: consul-bootstrap-token
              secretKey: token
```
We get errors, I think on the ACL creation jobs which means consul is unusable... 

Hope this makes sense?
Thanks!
Luke

**Comment by lkysow** [comment]
Hi @ufou, thanks for the questions.

> how should we declaratively create the ACL token which has reduced permissions

ACL roles and tokens must be created via API or Terraform. There is no CRD support currently (I think this is probably what you meant by declaratively?).

> when we set bootstrapToken secret name/key as a value for the chart...

This setting is only for Consul clusters that have already had ACLs bootstrapped. It does not support usage as a way to pre-set the bootstrap token. When this is set, we assume that ACLs have already been bootstrapped.

Are you looking to set this ahead of time so that your scripts can be more declarative? I'm wondering if we should open up a feature request.

**Comment by ufou** [comment]
> ACL roles and tokens must be created via API or Terraform. There is no CRD support currently (I think this is probably what you meant by declaratively?).

`created via API`

This seems a bit chicken & egg to me? In order to create ACL roles and tokens we need to use an API token - but we can only obtain the api token from a consul cluster that has already been initialised, however, I understand this use-case might be unique or uncommon - we spin up k8s clusters ad-hoc dependant on workload for the time of day/week - everything that runs on the cluster is deployed via helmfile and secrets are declared within yaml prior to the cluster being brought online...

If the recommended behaviour of the bootstrap token is for it to only be used for bootstrapping related API calls in production, then there should be a way for the helm chart to add an api token with some lower level permissions?


> 
> > when we set bootstrapToken secret name/key as a value for the chart...
> 
> This setting is only for Consul clusters that have already had ACLs bootstrapped. It does not support usage as a way to pre-set the bootstrap token. When this is set, we assume that ACLs have already been bootstrapped.
> 
> Are you looking to set this ahead of time so that your scripts can be more declarative? I'm wondering if we should open up a feature request.

Yes, if we are unable to set an additional API role/token with permissions to add services via helm, then being able to use a pre-configured bootstrap token would suffice - although I understand this is not desired.

I can look into this and create a PR for the chart.

**Comment by lkysow** [comment]
I think the ideal solution would be if bootstrapToken is set *and* ACLs are not yet bootstrapped then we bootstrap them using the bootstrapToken. Let's open up a new issue to track that.

You might be able to approximate that right now by setting https://www.consul.io/docs/agent/options#acl_tokens_master in extraConfig:

```yaml
server:
  extraConfig: |
    {"acl": {"tokens": {"master": "bootstrap-token"}}}
global:
  acls:
    bootstrapToken: # points at secret with same acl value
```

**Comment by lkysow** [comment]
Note to self: the [api](https://www.consul.io/api-docs/acl#bootstrap-acls) we use to bootstrap ACLs doesn't support setting the bootstrap key so we'd need to take that secret and set it as the value of the acl_tokens_master key in each server config.

**Comment by lkysow** [comment]
Created https://github.com/hashicorp/consul-helm/issues/779 to track support for pre-setting the bootstrap token.

**Comment by lkysow** [comment]
I'm going to close this then but feel free to comment if I missed something.
