### ISSUE TITLE
Helm makes HTTP call at the HTTPS port when using external Consul cluster.

### ISSUE THREAD

**Issue by jimm-with-a-j** [hashicorp/consul-helm#771]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

### Overview of the Issue

Working with local dev consul agent and a K8s cluster in Minikube I was trying to use the helm chart and noticed it was trying to communicate with the Consul API over HTTP but tries to use the HTTPS port. I didn't see any values to change this to use HTTPS so I had to 'lie' and set the helm value for httpsPort to 8500 (the HTTP port) and then everything went through.

### Reproduction Steps

Install or upgrade helm chart for client only with external Consul server. Make sure the API is accessible to K8s. When setting the externalServers if you leave the defaults it will try to communicate with Consul API at the HTTPS port but sends HTTP requests so it fails. If you then set the httpsPort value to be the HTTP port it works.

1. When running helm install with the following `values.yml`:
```
# config.yaml
global:
  enabled: false
  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: bootstrap-token-2
      secretKey: token
  tls:
    enableAutoEncrypt: true

client:
  enabled: true
  # Set this to true to expose the Consul clients using the Kubernetes node
  # IPs. If false, the pod IPs must be routable from the external servers.
  grpc: true
  join:
    - "192.168.86.249"

connectInject:
  enabled: true
  default: true
  
externalServers:
  enabled: true
  hosts:
    - "192.168.86.249"
  k8sAuthMethodHost: 'https://XXX:8443'
```
If changed to the below it works:
```
externalServers:
  enabled: true
  httpsPort: 8500
  hosts:
    - "192.168.86.249"
  k8sAuthMethodHost: 'https://XXX:8443'
```
1. View error

### Logs

<details>
  <summary>Logs</summary>

```
2021-01-19T19:25:05.589Z [INFO]  Bootstrap token is provided so skipping Consul server ACL bootstrapping
2021-01-19T19:25:05.593Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 400 (Client sent an HTTP request to an HTTPS server.
)"
2021-01-19T19:25:05.593Z [INFO]  Retrying in 1s
2021-01-19T19:25:06.595Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 400 (Client sent an HTTP request to an HTTPS server.
)"
2021-01-19T19:25:06.595Z [INFO]  Retrying in 1s
2021-01-19T19:25:07.598Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 400 (Client sent an HTTP request to an HTTPS server.
)"
2021-01-19T19:25:07.598Z [INFO]  Retrying in 1s
2021-01-19T19:25:08.601Z [ERROR] Failure: calling /agent/self to get datacenter: err="Unexpected response code: 400 (Client sent an HTTP request to an HTTPS server.
)"
```
</details>

### Expected behavior

Have an option to actually use HTTPS for these calls and make the expected call without having to set the 'lie' configuration.

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: 0.28.0
- `consul-helm` version: 0.28.0
- `values.yaml` used to deploy the helm chart: available above

Any other information you can provide about the environment/deployment.

### Additional Context

Additional context on the problem.

**Comment by lkysow** [comment]
Hi, I think you're missing the option to enable TLS:

```yaml
global:
  tls:
    enabled: true
```

I believe that should work for your use-case.

**Comment by jimm-with-a-j** [comment]
If that is not enabled shouldn't it then try to use the default HTTP port instead of the HTTPS one? That's the part that would be confusing without jumping into the logs.

**Comment by lkysow** [comment]
I don't believe we actually support external servers with HTTP. Hence only having the `httpsPort` option. I don't think this was documented though.

**Comment by jimm-with-a-j** [comment]
It would certainly make sense not to, thanks again!

**Comment by lkysow** [comment]
I've created https://github.com/hashicorp/consul-helm/pull/776 so we can track that there.
