### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by shazinahmed** [hashicorp/consul-helm#773]
### Overview of the Issue

Documentation for [kubernetes deployment guide](https://learn.hashicorp.com/tutorials/consul/kubernetes-deployment-guide) needs to be updated.

### Reproduction Steps

The [values](https://learn.hashicorp.com/tutorials/consul/kubernetes-deployment-guide#complete-example) file in the example uses `global.bootstrapACLs` instead of `global.acls.manageSystemACLs`.

https://github.com/hashicorp/consul-helm/blob/master/CHANGELOG.md#0220-june-18-2020

### Expected behavior

The documentation should use `global.acls.manageSystemACLs` in the example values file.

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: 0.22.0

Any other information you can provide about the environment/deployment.

### Additional Context

Additional context on the problem.

**Comment by lkysow** [comment]
Thanks! Sorry for the trouble, we'll update the guide.

**Comment by DerekStrickland** [comment]
Being addressed in Learn repo PR #2861
