### ISSUE TITLE
Specify an ACL token for the controller deployment

### ISSUE THREAD

**Issue by hamishforbes** [hashicorp/consul-helm#778]
Currently the [controller](https://github.com/hashicorp/consul-helm/blob/master/templates/controller-deployment.yaml#L86) only injects a token when the automagic / helm managed ACLs is enabled?

I'm trying to test out the new Consul 1.9 CRDs but just get a bunch of 403 errors because the controller has no token associated with it.

I want to be able to create a k8s secret and provide it to the helm chart, the same as the catalog sync [deployment](https://github.com/hashicorp/consul-helm/blob/5321326db4361970791cc9373cb68a283636eab8/templates/sync-catalog-deployment.yaml#L64) has `.Values.syncCatalog.aclSyncToken`

**Comment by lkysow** [comment]
A PR to support `controller.aclToken` makes sense.
