### ISSUE TITLE
Unable to install consul-helm with ConnectInject.enabled = true

### ISSUE THREAD

**Issue by raykao** [hashicorp/consul-helm#78]
Helm/tiller version: 2.11.0 with init & RBAC ```--service-account tiller``` set
Kubectl client/server version: 1.11.5
Target Provider/platform: AKS

When deploying consul-helm with value of connectInject.enabled=true, the below error pops up.

If I manually apply the connect-inject service account, role binding, mutatingwebhook and deployment it fails to inject connect even if annotation is added to pod manifest.

**Error Message:**
Error: release consul failed: clusterroles.rbac.authorization.k8s.io "consul-connect-injector-webhook" is forbidden: attempt to grant extra privileges: [{[get] [admissionregistration.k8s.io] [mutatingwebhookconfigurations] [] []} {[list] [admissionregistration.k8s.io] [mutatingwebhookconfigurations] [] []} {[watch] [admissionregistration.k8s.io] [mutatingwebhookconfigurations] [] []} {[patch] [admissionregistration.k8s.io] [mutatingwebhookconfigurations] [] []}] user=&{system:serviceaccount:kube-system:default 6aa4a5a7-f800-11e8-bc17-0a58ac1f0dfd [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "system:discovery" not found]

**Comment by adilyse** [comment]
Hi @raykao ,

The discussion in [this issue](https://github.com/MicrosoftDocs/azure-docs/issues/10719) makes me wonder if there's something odd about the way RBAC is set up for your cluster. Could you post the output of the `kubectl get clusterrole` command? That might help us track down what's happening here.

**Comment by lkysow** [comment]
Hey Raymond, since this issue is 6 months old I'm going to close it. Please reply back if you can provide the information @adilyse asked for and we can re-open.
