### ISSUE TITLE
Container Injected in all namespaces?

### ISSUE THREAD

**Issue by tsia** [hashicorp/consul-helm#787]
#### Question

Hi, i have installed consul using `helm install -n foo -f consul-helm.yaml consul hashicorp/consul --wait`.
It seems that consul is being injected into all pods in all namespaces including the OpenShift system Pods.
I'm pretty sure this is not intended and i'm holding it wrong but i can't find anything how to limit consul injection to one namespace.

**Comment by thisisnotashwin** [comment]
Hey @tsia ,

The helm chart has values under the `connectInject:` stanza named `k8sDenyNamespaces` and `k8sAllowNamespaces` which should allow one to filter the namespaces that consul gets injected onto. In your usecase setting the following in `consul-helm.yaml` (the values file) should solve your problem.
```
connectInject:
  k8sAllowNamespaces: ["foo"]
```

**Comment by tsia** [comment]
thanks a lot that was exactly what i was looking for
