### ISSUE TITLE
connect: connection refused when enable syncCatalog 

### ISSUE THREAD

**Issue by dongtianyi** [hashicorp/consul-helm#80]
2018-12-05T17:28:53.592Z [INFO ] to-consul/sink: ConsulSyncer quitting
ERROR: logging before flag.Parse: E1205 17:28:53.592459       7 controller.go:115] Error syncing cache
2018-12-05T17:28:53.592Z [INFO ] to-consul/source: starting runner for endpoints
ERROR: logging before flag.Parse: E1205 17:28:53.592565       7 controller.go:115] Error syncing cache
2018-12-05T17:28:53.593Z [WARN ] to-consul/sink: error querying services, will retry: err="Get http://192.168.43.4:8500/v1/catalog/services?index=1&stale=&wait=60000ms: dial tcp 192.168.43.4:8500: connect: connection refused"
2018-12-05T17:28:53.593Z [WARN ] to-consul/sink: error querying services, will retry: err="Get http://192.168.43.4:8500/v1/catalog/services?index=1&stale=&wait=60000ms: dial tcp 192.168.43.4:8500: connect: connection refused"
2018-12-05T17:28:53.593Z [WARN ] to-consul/sink: error querying services, will retry: err="Get http://192.168.43.4:8500/v1/catalog/services?index=1&stale=&wait=60000ms: dial tcp 192.168.43.4:8500: connect: connection refused"

**Comment by dongtianyi** [comment]
values.yaml I used:

# Available parameters and their default values for the Consul chart.

# Server, when enabled, configures a server cluster to run. This should
# be disabled if you plan on connecting to a Consul cluster external to
# the Kube cluster.

global:
  # enabled is the master enabled switch. Setting this to true or false
  # will enable or disable all the components within this chart by default.
  # Each component can be overridden using the component-specific "enabled"
  # value.
  enabled: true

  # Domain to register the Consul DNS server to listen for.
  domain: consul

  # Image is the name (and tag) of the Consul Docker image for clients and
  # servers below. This can be overridden per component.
  image: "consul:1.2.3"

  # imageK8S is the name (and tag) of the consul-k8s Docker image that
  # is used for functionality such as the catalog sync. This can be overridden
  # per component below.
  imageK8S: "hashicorp/consul-k8s:0.1.0"

  # Datacenter is the name of the datacenter that the agents should register
  # as. This shouldn't be changed once the Consul cluster is up and running
  # since Consul doesn't support an automatic way to change this value
  # currently: https://github.com/hashicorp/consul/issues/1858
  datacenter: dc1

server:
  enabled: "-"
  image: null
  replicas: 3
  bootstrapExpect: 3 # Should <= replicas count

  # storage and storageClass are the settings for configuring stateful
  # storage for the server pods. storage should be set to the disk size of
  # the attached volume. storageClass is the class of storage which defaults
  # to null (the Kube cluster will pick the default).
  storage: 20Gi
  storageClass: null

  # connect will enable Connect on all the servers, initializing a CA
  # for Connect-related connections. Other customizations can be done
  # via the extraConfig setting.
  connect: true

  # Resource requests, limits, etc. for the server cluster placement. This
  # should map directly to the value of the resources field for a PodSpec.
  # By default no direct resource request is made.
  resources: {}

  # updatePartition is used to control a careful rolling update of Consul
  # servers. This should be done particularly when changing the version
  # of Consul. Please refer to the documentation for more information.
  updatePartition: 0

  # disruptionBudget enables the creation of a PodDisruptionBudget to
  # prevent voluntary degrading of the Consul server cluster.
  disruptionBudget:
    enabled: true

    # maxUnavailable will default to (n/2)-1 where n is the number of
    # replicas. If you'd like a custom value, you can specify an override here.
    maxUnavailable: null

  # extraConfig is a raw string of extra configuration to set with the
  # server. This should be JSON.
  extraConfig: |
    {}

  # extraVolumes is a list of extra volumes to mount. These will be exposed
  # to Consul in the path `/consul/userconfig/<name>/`. The value below is
  # an array of objects, examples are shown below.
  extraVolumes: []
    # - type: secret (or "configMap")
    #   name: my-secret
    #   load: false # if true, will add to `-config-dir` to load by Consul

# Client, when enabled, configures Consul clients to run on every node
# within the Kube cluster. The current deployment model follows a traditional
# DC where a single agent is deployed per node.
client:
  enabled: "-"
  image: null
  join: null

  # grpc should be set to true if the gRPC listener should be enabled.
  # This should be set to true if connectInject is enabled.
  grpc: false

  # Resource requests, limits, etc. for the client cluster placement. This
  # should map directly to the value of the resources field for a PodSpec.
  # By default no direct resource request is made.
  resources: {}

  # extraConfig is a raw string of extra configuration to set with the
  # server. This should be JSON.
  extraConfig: |
    {}

  # extraVolumes is a list of extra volumes to mount. These will be exposed
  # to Consul in the path `/consul/userconfig/<name>/`. The value below is
  # an array of objects, examples are shown below.
  extraVolumes: []
    # - type: secret (or "configMap")
    #   name: my-secret
    #   load: false # if true, will add to `-config-dir` to load by Consul

# Configuration for DNS configuration within the Kubernetes cluster.
# This creates a service that routes to all agents (client or server)
# for serving DNS requests. This DOES NOT automatically configure kube-dns
# today, so you must still manually configure a `stubDomain` with kube-dns
# for this to have any effect:
# https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#configure-stub-domain-and-upstream-dns-servers
dns:
  enabled: "-"

ui:
  # True if you want to enable the Consul UI. The UI will run only
  # on the server nodes. This makes UI access via the service below (if
  # enabled) predictable rather than "any node" if you're running Consul
  # clients as well.
  enabled: "-"

  # True if you want to create a Service entry for the Consul UI.
  #
  # serviceType can be used to control the type of service created. For
  # example, setting this to "LoadBalancer" will create an external load
  # balancer (for supported K8S installations) to access the UI.
  service:
    enabled: true
    type: null

# syncCatalog will run the catalog sync process to sync K8S with Consul
# services. This can run bidirectional (default) or unidirectionally (Consul
# to K8S or K8S to Consul only).
#
# This process assumes that a Consul agent is available on the host IP.
# This is done automatically if clients are enabled. If clients are not
# enabled then set the node selection so that it chooses a node with a
# Consul agent.
syncCatalog:
  # True if you want to enable the catalog sync. "-" for default.
  enabled: true
  image: null

  # toConsul and toK8S control whether syncing is enabled to Consul or K8S
  # as a destination. If both of these are disabled, the sync will do nothing.
  toConsul: true
  toK8S: false

  # k8sPrefix is the service prefix to prepend to services before registering
  # with Kubernetes. For example "consul-" will register all services
  # prepended with "consul-".
  k8sPrefix: null

# ConnectInject will enable the automatic Connect sidecar injector.
connectInject:
  enabled: false
  image: null # image for consul-k8s that contains the injector
  default: false # true will inject by default, otherwise requires annotation

  # imageConsul and imageEnvoy can be set to Docker images for Consul and
  # Envoy, respectively. If the Consul image is not specified, the global
  # default will be used. If the Envoy image is not specified, an early
  # version of Envoy will be used.
  imageConsul: null
  imageEnvoy: null

  # namespaceSelector is the selector for restricting the webhook to only
  # specific namespaces. This should be set to a multiline string.
  namespaceSelector: null

  # The certs section configures how the webhook TLS certs are configured.
  # These are the TLS certs for the Kube apiserver communicating to the
  # webhook. By default, the injector will generate and manage its own certs,
  # but this requires the ability for the injector to update its own
  # MutatingWebhookConfiguration. In a production environment, custom certs
  # should probaly be used. Configure the values below to enable this.
  certs:
    # secretName is the name of the secret that has the TLS certificate and
    # private key to serve the injector webhook. If this is null, then the
    # injector will default to its automatic management mode.
    secretName: null

    # caBundle is a base64-encoded PEM-encoded certificate bundle for the
    # CA that signed the TLS certificate that the webhook serves. This must
    # be set if secretName is non-null.
    caBundle: ""

    # certName and keyName are the names of the files within the secret for
    # the TLS cert and private key, respectively. These have reasonable
    # defaults but can be customized if necessary.
    certName: tls.crt
    keyName: tls.key

**Comment by dongtianyi** [comment]
consul-y-sync-catalog  try to connect hostIP:8500, but I found that consul client run command 

`/bin/sh -ec CONSUL_FULLNAME="consul-y" exec /bin/consul agent \ -advertise="${POD_IP}" \ -bind=0.0.0.0 \ -client=0.0.0.0 \ -config-dir=/consul/config \ -datacenter=dc1 \ -data-dir=/consul/data \ -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \ -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \ -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \ -domain=consul`

**-advertise="${POD_IP}** 

How can I do ?

Thanks!!!

**Comment by dongtianyi** [comment]
Also I run helm : 
`helm install --name consul-y ./ --namespace=consul`

```
(backend5) tt-939:consul-helm tt$ helm version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

```
(backend5) tt-939:consul-helm tt$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-08T16:31:16Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dongtianyi** [comment]
```
(backend5) tt-939:consul-helm tt$ ku describe deployment consul-y-sync-catalog --namespace=consul
Name:                   consul-y-sync-catalog
Namespace:              consul
CreationTimestamp:      Thu, 06 Dec 2018 02:27:16 +0900
Labels:                 app=consul
                        chart=consul-0.1.0
                        heritage=Tiller
                        release=consul-y
Annotations:            deployment.kubernetes.io/revision=1
Selector:               app=consul,chart=consul-0.1.0,component=sync-catalog,release=consul-y
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=consul
                chart=consul-0.1.0
                component=sync-catalog
                release=consul-y
  Annotations:  consul.hashicorp.com/connect-inject=false
  Containers:
   consul-sync-catalog:
    Image:      hashicorp/consul-k8s:0.1.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -ec
      consul-k8s sync-catalog \
  -http-addr=${HOST_IP}:8500 \
  -to-k8s=false \
  -consul-domain=consul \
  -k8s-write-namespace=${NAMESPACE}

    Environment:
      HOST_IP:     (v1:status.hostIP)
      NAMESPACE:   (v1:metadata.namespace)
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   consul-y-sync-catalog-5d557fbfdf (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  24m   deployment-controller  Scaled up replica set consul-y-sync-catalog-5d557fbfdf to 1
(backend5) tt-939:consul-helm tt$ kubectl get statefulset --namespace=consul
NAME              DESIRED   CURRENT   AGE
consul-y-server   3         3         26m
(backend5) tt-939:consul-helm tt$ ku describe statefulset consul-y-server --namespace=consul
Name:               consul-y-server
Namespace:          consul
CreationTimestamp:  Thu, 06 Dec 2018 02:27:16 +0900
Selector:           app=consul,chart=consul-0.1.0,component=server,hasDNS=true,release=consul-y
Labels:             app=consul
                    chart=consul-0.1.0
                    heritage=Tiller
                    release=consul-y
Annotations:        <none>
Replicas:           3 desired | 3 total
Update Strategy:    RollingUpdate
Pods Status:        3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:       app=consul
                chart=consul-0.1.0
                component=server
                hasDNS=true
                release=consul-y
  Annotations:  consul.hashicorp.com/connect-inject=false
  Containers:
   consul:
    Image:       consul:1.2.3
    Ports:       8500/TCP, 8301/TCP, 8302/TCP, 8300/TCP, 8600/TCP, 8600/UDP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/UDP
    Command:
      /bin/sh
      -ec
      CONSUL_FULLNAME="consul-y"

exec /bin/consul agent \
  -advertise="${POD_IP}" \
  -bind=0.0.0.0 \
  -bootstrap-expect=3 \
  -client=0.0.0.0 \
  -config-dir=/consul/config \
  -datacenter=dc1 \
  -data-dir=/consul/data \
  -domain=consul \
  -hcl="connect { enabled = true }" \
  -ui \
  -retry-join=${CONSUL_FULLNAME}-server-0.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
  -retry-join=${CONSUL_FULLNAME}-server-1.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
  -retry-join=${CONSUL_FULLNAME}-server-2.${CONSUL_FULLNAME}-server.${NAMESPACE}.svc \
  -server

    Readiness:  exec [/bin/sh -ec curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
grep -E '".+"'
] delay=5s timeout=5s period=3s #success=1 #failure=2
    Environment:
      POD_IP:      (v1:status.podIP)
      NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /consul/config from config (rw)
      /consul/data from data (rw)
  Volumes:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      consul-y-server-config
    Optional:  false
Volume Claims:
  Name:          data
  StorageClass:  
  Labels:        <none>
  Annotations:   <none>
  Capacity:      20Gi
  Access Modes:  [ReadWriteOnce]
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  26m   statefulset-controller  create Claim data-consul-y-server-0 Pod consul-y-server-0 in StatefulSet consul-y-server success
  Normal  SuccessfulCreate  26m   statefulset-controller  create Pod consul-y-server-0 in StatefulSet consul-y-server successful
  Normal  SuccessfulCreate  26m   statefulset-controller  create Claim data-consul-y-server-1 Pod consul-y-server-1 in StatefulSet consul-y-server success
  Normal  SuccessfulCreate  26m   statefulset-controller  create Pod consul-y-server-1 in StatefulSet consul-y-server successful
  Normal  SuccessfulCreate  26m   statefulset-controller  create Claim data-consul-y-server-2 Pod consul-y-server-2 in StatefulSet consul-y-server success
  Normal  SuccessfulCreate  26m   statefulset-controller  create Pod consul-y-server-2 in StatefulSet consul-y-server successful
```

**Comment by miaowing** [comment]
How to resolve it @dongtianyi, I have the same issue.

**Comment by csayler** [comment]
how did you solve did you use podIP? I have the same issue with one consul-server and no volume
