### ISSUE TITLE
Deploy Vault and consul agent in same pod with TLS using helm

### ISSUE THREAD

**Issue by ram-vibhulaanandh** [hashicorp/consul-helm#816]
#### Question

I m planning to use Vault Service as HA with Consul Backend with TLS using helm deployment for both consul and vault.

I have already deployed consul using helm deployment in my EKS cluster. This would deploy consul client as a daemonset and consul server as a pod
When the vault is deployed using helm, my vault server has to interact with consul client instead of consul server. 
The challenge i face is that I can't provide storage consul address in below vault configuration file as 127.0.0.1:8501 because vault is running as separate pod and consul client as separate pod. so different ips. 

storage "consul" {
address = "<WHAT_SHOULD_I_PROVIDE?>:8501"
path = "vault/"
scheme = "https"
tls_ca_file = ""
tls_cert_file = ""
tls_key_file = ""
token = "<CONSUL_TOKEN>""
}
I have also tweaked it by using HOST_IP:8501 but it throws below error
[WARN] storage migration check error: error="Get "https://10.15.0.7:8501/v1/kv/vault/core/migration": x509: certificate signed by unknown authority"

This is because TLS certificate should include a Subject Alternative Name (SAN) for the IP address, and of course, it should be signed by a trusted CA that you include as part of the ca_file parameter in Consul. But in my consul helm chart configuration, I'm using enableAutoEncrypt: true. So I can't able to use custom certs.

This would resolve if i deploy vault and consul in the same pod. In the vault helm chart configs, I couldn't find the consulAgent configuration in order to deploy the vault and consul agent together. Please help and let me know how to resolve this

**Comment by thisisnotashwin** [comment]
Hey @ram-vibhulaanandh,

You might be able to get around this a few ways.
While create the client certificate, once could pass the following flags:
```
consul tls cert create -client \
  -additional-ipaddress=${HOST_IP} \
  -additional-dnsname=${DNS-NAME} \
  -dc={{ .Values.global.datacenter }} \
  -domain={{ .Values.global.domain }} \
  -ca=/consul/tls/ca/cert/tls.crt \
  -key=/consul/tls/ca/key/tls.key
```

You could create a kubernetes service that can interact with the client and provide the kubeDNS name to the additional DNS name flag above. In its current configuration, I dont think you can have a vault container and consul container deployed in the same pod.

**Comment by thisisnotashwin** [comment]
@ram-vibhulaanandh Could you disable auto-encrypt in this case? That would allow you to mount the consul CA cert into the vault pods then as the certificate will be available as a secret. Auto-encrypt is not the greatest fit for this particular use-case.

**Comment by ram-vibhulaanandh** [comment]
@thisisnotashwin I have exposed consul client as svc named it as "consul-client-svc.vault.svc.cluster.local". Even after providing additional-ipaddress and additional-dnsname  for consul client certs, I'm getting this below error
` storage migration check error: error="Get "https://consul-client-svc.vault.svc.cluster.local:8501/v1/kv/vault/core/migration": x509: certificate is valid for client.dc1.consul, localhost, not consul-client-svc.vault.svc.cluster.local"`  But if i provide address = "HOST_IP:8501", this actually works. what am i missing here

**Comment by thisisnotashwin** [comment]
@ram-vibhulaanandh That seems surprising. Can you verify that the client are using the updated certificates and also that the vault pod is presenting the newly generated certificate? Some components will potentially need a restart even if the secrets have been updated.
In the above case I suspect the difference might have to do with "consul-client-svc.vault.svc.cluster.local" vs "consul-client-svc.vault.svc" ie `cluster.local` but i might be getting by dnsname matching confused.
But it does look like the cert supports the ip address `172.38.0.14` which i suspect is the host IP?

**Comment by thisisnotashwin** [comment]
In either case, I think using the `HOST_IP:8501` is the best next step, given it will avoid the un-necessary hop of kube-dns 😄 
Hope that helps.

**Comment by thisisnotashwin** [comment]
@ram-vibhulaanandh I think this comment here addresses the same problem: https://github.com/hashicorp/consul-helm/issues/784#issuecomment-767118078

**Comment by ram-vibhulaanandh** [comment]
> @ram-vibhulaanandh That seems surprising. Can you verify that the client are using the updated certificates and also that the vault pod is presenting the newly generated certificate? Some components will potentially need a restart even if the secrets have been updated.
> In the above case I suspect the difference might have to do with "consul-client-svc.vault.svc.cluster.local" vs "consul-client-svc.vault.svc" ie `cluster.local` but i might be getting by dnsname matching confused.
> But it does look like the cert supports the ip address `172.38.0.14` which i suspect is the host IP?

Yes I uninstalled completely and redeployed.Not sure why the dns names are not resolved. 172.38.0.14 is the host ip. Since it is working, I'm using this workaround

**Comment by thisisnotashwin** [comment]
@ram-vibhulaanandh Awesome!! I'm glad you're unblocked. Would you mind if I closed this issue?

**Comment by ram-vibhulaanandh** [comment]
Sure.. Closing it
