### ISSUE TITLE
hashicorp/consul-helm won't deploy on k8s 1.18.x 

### ISSUE THREAD

**Issue by enibache** [hashicorp/consul-helm#820]
Please search the existing issues for relevant questions, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing questions.

#### Question

Please provide as many details as you can, including but not limited to
- Helm command you're running
- Any values you've configured
- Your current understanding, and what you're trying to figure out

I get the following error:

´´´
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "extensions/v1"
´´´
Setting .Values.ui.service to true, and running helm install consul -f values.yaml hashicorp/consul, the above error pops up. The release succeeds though with this flag turned off/false but without creating the ingress.
  
Please see attached my custom values.yaml:

´´´

global:
  enabled: true

  name: consul

  domain: consul

  image: "hashicorp/consul:1.9.2"

  imagePullSecrets: []

  imageK8S: "hashicorp/consul-k8s:0.23.0"

  datacenter: STAGING

  enablePodSecurityPolicies: false

  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"

  tls:
    enabled: true

    enableAutoEncrypt: false

    serverAdditionalDNSSANs: []

    serverAdditionalIPSANs: []

    verify: true

    httpsOnly: true

    caCert:
      secretName: null
      secretKey: null

    caKey:
      secretName: null
      secretKey: null

  enableConsulNamespaces: false

server:

  enabled: "-"

  image: null

  replicas: 3

  bootstrapExpect: 3

  enterpriseLicense:
    secretName: null
    secretKey: null

  exposeGossipAndRPCPorts: false

  ports:
    serflan:
      port: 8301

  storage: 15Gi

  storageClass: "managed-nfs-storage"

  connect: true

  resources:
    requests:
      memory: "10Gi"
    limits:
      memory: "10Gi"

  securityContext:
    runAsNonRoot: true
    runAsGroup: 1000
    runAsUser: 100
    fsGroup: 1000

  updatePartition: 0

  disruptionBudget:
    enabled: true

    maxUnavailable: null

  extraConfig: |
    {
      "log_level": "DEBUG"
    }

  extraVolumes: 
    - type: secret
      name: consul-acl-tokens
      load: true

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: {{ template "consul.name" . }}
              release: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

ui:
  enabled: true

  service:
    enabled: true

    type: ClusterIP

    annotations: null

    additionalSpec: null

  ingress:
    enabled: true

    hosts:
      - host: consul.qual.mydomain.local
        paths:
          - /
    tls:
      - hosts:
        - consul.qual.mydomain.local
        secretName: qual.mydomain.local

    annotations: |
        'kubernetes.io/ingress.class': traefik
        'traefik.frontend.rule.type': PathPrefixStrip

tests:
  enabled: true

´´´
More details will help us answer questions more accurately and with less delay :)

**Comment by thisisnotashwin** [comment]
Hey @enibache !! Thanks for raising this issue. The `ingress` service in the latest release of helm has an issue in it as it was tagged with the wrong API version. This bug has been fixed on the `master` branch of consul-helm. Current workaround and currently disabling ui.ingress in the helm values file and explicitly creating an Ingress resource with the supplied values. The alternative would be to use the helm chart on master instead of the latest release version. 

I hope this helps.

**Comment by enibache** [comment]
Hi @thisisnotashwin, thanks very much for the prompt response. Very much appreciate your suggestions as well. I thought i was deploying the chart on the master branch. Could you please give me a directive on how to refer to the chart on the master branch. 
Once again many thanks and keep up the good job.

**Comment by thisisnotashwin** [comment]
Hey @enibache !!
You would have to `git checkout` this repo explicitly and perform a `helm install` using the chart from your filesystem.

Appreciate the kind words a lot :)

**Comment by enibache** [comment]
thanks @thisisnotashwin, not quite an ideal solution but works for now. Many thanks !

**Comment by pedrohdz** [comment]
@enibache 
This appears to have been fixed in `0.30.0`, which was release yesterday.
