### ISSUE TITLE
catalog sync use too much of CPU

### ISSUE THREAD

**Issue by kgignatyev-inspur** [hashicorp/consul-helm#83]
I have deployed the helmchart and disabled everything except sync from k8s to Consul (k8s is running in Docker CE app locally) and all is working BUT CPU consumption shoot to the moon the moment this is deployed.
![image](https://user-images.githubusercontent.com/27866311/49679524-dbf64180-fa40-11e8-8458-8c33c1acb654.png)

the moment the helm chart is undeployed  CPU utilization goes back to normal
![image](https://user-images.githubusercontent.com/27866311/49679534-f3cdc580-fa40-11e8-8490-681653447e75.png)

**Comment by adilyse** [comment]
Hi @kgignatyev-inspur,

Could you post the version of the helm chart and `consul-k8s` you're using, as well as the sync settings in the values file? That will help narrow down what might be going on.

**Comment by kgignatyev-inspur** [comment]
here it is, note that the values file has customizations 
[consul-helm.zip](https://github.com/hashicorp/consul-helm/files/2659223/consul-helm.zip)

**Comment by adilyse** [comment]
Good catch! There was a hot loop for syncing Kubernetes services to Consul. This has now been [fixed](https://github.com/hashicorp/consul-k8s/pull/33) and should be included in the next release.
