### ISSUE TITLE
Helm upgrade overwrites custom anonymous policy

### ISSUE THREAD

**Issue by leanst-daniel** [hashicorp/consul-helm#894]
We've successfully deployed multiple Consul environments with the Helm chart but in some cases we unfortunately have to modify the default anonymous policy and add certain permissions.
If we change a configuration variable and redeploy the Helm chart these changes are overwritten and the default anonymous policy is "restored"

Is this expected behavior?

Thanks!

**Comment by ishustava** [comment]
Hey @leanst-daniel 

I'm not sure I fully understand your question. Are you referring to the Consul ACL policy? Could you include more information in your issue and reproduction steps? Which configuration variable are you changing?

Also, as a side note, it'd be helpful if you had used one of the templates to create the issue. It would really help us answer your question better 🙏

**Comment by david-yu** [comment]
Closing as we have not received a response for some time, this is a duplicate I believe of the following issue: https://github.com/hashicorp/consul-helm/issues/425
