### ISSUE TITLE
Consul Client Only Mode Nodes Show Unhealthy

### ISSUE THREAD

**Issue by ivelichkovich** [hashicorp/consul-helm#94]
I'm running the helm chart with client only mode on EKS and connecting to consul servers hosted on EC2. The client pods connect up to consul and appear healthy but the servers show that the nodes are failing health checks.

Serf Health Status: Agent not live or unreachable

The nodes occasionally flip to healthy temporarily and then flip back

**Comment by debjitk** [comment]
I am facing the same issue.
