### ISSUE TITLE
Chart version in tag references

### ISSUE THREAD

**Issue by darrylb-github** [hashicorp/consul-helm#95]
If you look at Chart.yaml in the v0.3.0 tag, the version states `0.1.0` instead of `0.3.0`. 

https://github.com/hashicorp/consul-helm/blob/v0.3.0/Chart.yaml#L3

Same issue applies to earlier versions. This causes problems when trying to lock the chart to an older version.

Why is the chart version reset to 0.1.0 when tagging release versions?

**Comment by adilyse** [comment]
Hi @darrylb-github 

This was an oversight in our release process that we've recently fixed. Starting with v0.4.0, the version in the Chart.yaml is updated and matches the release version, as will future versions. We won't be updating the old versions though, so I would recommend using v0.4.0 if you need to lock the version moving forward.

Thanks!
