### ISSUE TITLE
Consul agents not leaving the cluster gracefully on node termination

### ISSUE THREAD

**Issue by choppedpork** [hashicorp/consul-helm#956]
Hello,

I'm quite happily using `consul-helm` (currently on chart version 0.22.0, Consul version 1.9.3) in order to deploy an agent daemonset into k8s which is connecting to a non-k8s stable server cluster (3 nodes). As part of recent work on autoscaling workloads within k8s I've noticed that sometimes (I don't think this happens always) following a k8s node scale-in event the nodes Consul agent fails to leave the cluster gracefully resulting in an alert about an unhealthy Consul node. I've currently worked around this by just ignoring alerts relating to k8s worker nodes but wanted to dig in a little bit deeper into this.

I've done some searching through issues and PRs in this repo as well as on SO and it looks like this can happen when using spot instances as sometimes there will simply not be enough time between the SIGTERM and the underlying instance being halted. I've seen this happen in non-spot scenarios as well though (both EKS and GKE), where I'm assuming there is more than 2 minutes for all shutdown tasks to be completed. I've started looking through the chart code to see if the graceful termination period is configurable which led to me realising that it's not and that it's set to 10s for agent nodes. Is it possible that 10s can be not enough for the `leave` to be executed successfully? The Consul clusters I'm dealing with are in the low dozens of nodes (biggest one would be ~80 or so but usually closer to 12-30 nodes inclusive of servers).

Thanks!

**Comment by lkysow** [comment]
Hi @choppedpork,
This is because until Kubernetes 1.21, Kubernetes does not support sending a SIGTERM to daemonset pods so the Consul agents don't get the time to leave gracefully for spot instances.

What we recommend users do is set https://www.consul.io/docs/agent/options#advertise_reconnect_timeout to a small timeout like 15m. Then the nodes will get cleaned up quickly. By default it's 72h.

```yaml
client:
  extraConfig: |
    {"advertise_reconnect_timeout": "15m"}
```

**Comment by choppedpork** [comment]
Many thanks @lkysow - that does indeed explain everything. Will use the reconnect timeout setting until an upgrade to 1.21 is possible. Glad I've asked!
