### ISSUE TITLE
Problem with IPs joining existing cluster

### ISSUE THREAD

**Issue by tushar00jain** [hashicorp/consul-helm#96]
It's mentioned in the following link that joining an existing cluster is possible https://www.consul.io/docs/platform/k8s/run.html.

I'm in a similar situation where I have an existing consul cluster running outside the kubernetes cluster and I want to have just the consul agent inside the kubernetes cluster. However, the problem is with the IP addresses. In order for the nodes outside the cluster to access the pods inside kubernetes, I have set up a node port service and the advertised IP is set to the node's IP. The problem is that the pods inside the cluster see the incoming request as from the pod's IP not the node's IP, whereas the nodes outside kubernetes have no way to interact with kubernetes with the pod IP.

Of course running only 1 agent inside kubernetes works because this conflicting IP issue does not occur. Any solutions for this? Some possible solutions perhaps but I haven't tried

Configuring iptables such that the IP address is changed to use the node's IP address when accessing consul ports inside kubernetes. But this will require manually configuring kubernetes nodes.
Use AWS CNI so that the nodes can communicate directly with the pods using the pod's IP address but this could only work for AWS
Is there any other way that this issue can be resolved?

**Comment by tushar00jain** [comment]
I have addressed a solution that seems to be working here

https://github.com/hashicorp/consul-helm/blob/master/templates/client-daemonset.yaml#L52

I suppose a line `hostNetwork: true` can be added here in case `global.enabled` is set to `false`

**Comment by lkysow** [comment]
I think this is the same as #90. [This comment](https://github.com/hashicorp/consul-helm/issues/90#issuecomment-542797609) is a good response to this too so I'm going to close since it's tracked in the other issue.
