### ISSUE TITLE
Modify failurePolicy for MutatingWebhookConfiguration to fail pods when injector not running

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-helm#962]
### Overview of the Issue

When the injector isn't running pods with the connect annotation should fail to schedule rather than be scheduled without the annotation.

Look at using https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-objectselector to scope the webhook so that the Consul component pods aren't blocked.

**Comment by david-yu** [comment]
Closing as now addressed by https://github.com/hashicorp/consul-helm/pull/1024
