### ISSUE TITLE
Why is so important to contact the local node? How do you ensure startup order?

### ISSUE THREAD

**Issue by alsyia** [hashicorp/consul-helm#966]
#### Question

Hello,

Doc says that a pod should always contact its local Consul agent:
>The Consul HTTP API should be accessed by communicating to the local agent running on the same node. While technically any listening agent (client or server) can respond to the HTTP API, communicating with the local agent has important caching behavior, and allows you to use the simpler /agent endpoints for services and checks.

Even after reading this I still don't totally understand why this is so important. I understand the caching argument, I guess the cache would end up distributed across all agents and since there is no guarantee different requests from the same pod would be routed to the same agent, hit rate could be low.

Our setup mostly uses DNS resolution and we have Kube node DNS cache, so that's already that. We only do Consul KV requests at the startup of each pod, so, not that often. Do you think it could still be an issue?

I also don't get the point about the `/agent` API. Is it available only if you contact the local agent and not through the global service?

The thing I'm really interested in, though, is this: when a node is added to the cluster, what is the preferred way to ensure pods won't start before the agent (and thus, fail?). We setup priority and such, but this not a strong guarantee and we still see pod failures from time to time when they request an agent and the agent has not started yet. 
We thought about adding a K8S controller or something that either taint nodes until the agent is ready, or maybe injects an init container into each pod that checks if the agent is ready, but it seems quite cumbersome. Obviously, using a Kube service instead of contacting the local agent would fix that, but it seems this is not recommended.

Thank you! :)

**Comment by thisisnotashwin** [comment]
hey @alsyia 

within consul, the local agent is considered the source of truth wrt the services registered as well as the status of those services. while the cache does end up getting distributed across all the agents, it does ensure that the results of a query to the API are accurate, in terms of state of the world.
in the case where your primary usecase is k/v, i do not think it should be an issue.

the `/agent` api queries the state of the targeted agent and not the others. therefore in this case, the response would be specific to the agent that the query was issued against. we do have "global" apis like the `/catalog` api which queries the consul catalog which is the shared cache state across agents.

re: a new node getting created, there currently isnt a straightforward way to ensure that no workloads are provisioned on a node where the consul agent isnt running yet. we expect the node to be in a steady state (ie has the agent succesfully deployed onto it) before workloads are scheduled, but this is something we can investigate locally. let me talk to the team about this and try and find a sustainable workaround.

thanks again!

**Comment by alsyia** [comment]
Hey! Thanks for taking some time to answer :)

I understand that using the Consul service would probably be ok in our use cases, although not recommended. I guess the alternative would be to setup something like the local dns cache that hijack requests to route them to the local pod, but we would rather not do that!

Please tell me if you and the team have a workaround in mind! :)

**Comment by kschoche** [comment]
Hi @alsyia!
In addition to the guidance @thisisnotashwin provided I wanted to add a little bit more context which might help you achieve your target of not scheduling pods on nodes where the agent is down.

> The thing I'm really interested in, though, is this: when a node is added to the cluster, what is the preferred way to ensure pods won't start before the agent (and thus, fail?). We setup priority and such, but this not a strong guarantee and we still see pod failures from time to time when they request an agent and the agent has not started yet.

In the latest beta release which we're hoping to GA toward the end of the month, we've actually heavily refactored how mutation, service registration, and the init containers work. In the new model should your connect injected pod be scheduled on a "new" node who's agent has not yet started the pod would remain in a CrashLoopBackoff failing startup on the init containers until the local agent is online.

I hope that helps!

**Comment by alsyia** [comment]
Hi @kschoche!

We don't use connect-inject yet: we mostly use KV and service catalog features for now, even though we are thinking about adding the full connect layer. Our pods reach out to the agent using the client library, so I'm not sure it helps, but I take good note that this would also solve our issue.

Thanks!

**Comment by david-yu** [comment]
Hi @alsyia hopefully we have answered your question sufficiently. I'll go ahead and close this issue let us know if we have not. Thank you!
